### ISSUE TITLE
unable to use floatThead inside bootstrap modal table

### ISSUE THREAD

**Issue by mafar** [mkoryak/floatThead#109]
Hi,
I have been messing with floatThead  but unable to use it inside bootstrap 3 modal.

JSFIDDLE: http://jsfiddle.net/bababalcksheep/1fmkhd4c/
click `Launch demo modal`` button

Let me clarify my issue:
1. I have Bootstrap 3 modal with scrolling inside modal-body. // I am using modal overhaul from http://stackoverflow.com/questions/18422223/bootstrap-3-modal-vertical-position-center
2. Inside modal body I am using fancytree Plugin which renders in table. https://github.com/mar10/fancytree
3. I am trying to fix table header with floatThead but unable to freeze it. 

Required effect is that if tree header should be fixed  (which is inside modal-body)

Any help will be much appreciated.

**Comment by rlindabury** [comment]
Your jsfiddle linked to above doesn't work. The table headers is scrolling with the table. Can you update this because I'm having the same issue with latest jquery and bootstrap 3. 

The floating header works fine when not in a modal.

Thanks.

**Comment by mkoryak** [comment]
That fiddle is 3 years old so the resources it links might not be there. Have you tried using the latest versions of everything?

**Comment by rlindabury** [comment]
Yes I'm using the latest versions of everything the head works fine except
in the modal in bootstrap 3

**Comment by mkoryak** [comment]
ok, so that old fiddle had a bunch of scripts not loading because it was old. I updated them and now everything works fine:

http://jsfiddle.net/1fmkhd4c/38/

**Comment by rlindabury** [comment]
Ok.. great!  I see it's working on the fiddle. I'll see if I can get it to work on my project. Mine is a ASP.NET webforms project so using a master page (template) and then content pages with bootstrap modal popups and asp:repeater table inside of it. The table is dynamically generated with the repeater.  My issue may have something to do with the dynamic table and timing. ??  Not sure.

**Comment by mkoryak** [comment]
Probably that. It's hard to say since I've never .neted

You can search issues for other dynamic table / ajax things. Add tag
"problem" for non bug things.

But the basic answer is that you need to trigger the reflow even once your
table dom is done being created. Do it in a settimeout of 5 seconds just to
test that theory

**Comment by mkoryak** [comment]
either way, if you cant figure it out and are able to create a fiddle where it does not work, please open a new issue.
