### ISSUE TITLE
problem with colspan and rowspan in IE8

### ISSUE THREAD

**Issue by gituser10** [mkoryak/floatThead#126]
problem with colspan and rowspan in IE8:
it does not work in IE8, if you have colspans or rowspans on html table cells in 
header (wrapper) `<th colspan="2">something</th>`

 and also in data 

```
<tr  colspan="2">something</tr>    
```

**Comment by dineshedlapalli** [comment]
I have encountered the same problem when first row below header is hidden in IE10 but it works without any issues in chrome. When I included headerCellSelector in options, the same behaviour is replicated in chrome and still doesn't work in IE10.
jQuery version - 2.1.1
floatThead version - 1.2.10

Any workarounds to resolve this issue?
Thanks
