### ISSUE TITLE
Can't apply to multiple tables at once

### ISSUE THREAD

**Issue by cdw9** [mkoryak/floatThead#142]
I have multiple tables that all have the same class.  Ideally, I'd like to do:

    $("table.ram").floatThead();

and have it work on all the tables. Instead, it seems I need to call each one separately.

**Comment by swaprks** [comment]
Did you find a solution to this? I am facing the same issue.

**Comment by cdw9** [comment]
@swaprks I had to do it for each:

    $(".mytable").each(function(){
        floatHeading($(this));
    });

**Comment by mkoryak** [comment]
if you can create a jsfiddle with the issue, ill take a look. it shouldnt be a problem

**Comment by swaprks** [comment]
I am doing the same. Let me clear my cache and check one. My table is
inside a jquery tab.

On Thu, Aug 13, 2015 at 9:07 PM, Misha Koryak <notifications@github.com>
wrote:

> if you can create a jsfiddle with the issue, ill take a look. it shouldnt
> be a problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mkoryak/floatThead/issues/142#issuecomment-130732376>.
>



-- 

*Thanks*

*Regards*

*Swapnil Khamkar ( swaprks )*
* <http://mGinger.com/index.jsp?inviteId=1023566>*

**Comment by mkoryak** [comment]
ah, well that is a key piece of information. see this:

https://github.com/mkoryak/floatThead/issues/202

**Comment by swaprks** [comment]
In my case. The table is not getting wrapped in the float container. This
is happening only for table inside the tab.

**Comment by mkoryak** [comment]
ok, please provide a jsfiddle if you want me to help you

**Comment by swaprks** [comment]
is there an issue using this plugin with jquery tabs??

**Comment by mkoryak** [comment]
Read the faq

**Comment by swaprks** [comment]
Hi,
  One more issue. I have a chart at the top and a table of content below.
All this is present inside a modal box. I want to float the table header at
the top when the user scrolls the pop up vertically. Any suggestion.

On Sat, Aug 15, 2015 at 5:02 PM, Misha Koryak <notifications@github.com>
wrote:

> Read the faq
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mkoryak/floatThead/issues/142#issuecomment-131355732>.
>



-- 

*Thanks*

*Regards*

*Swapnil Khamkar ( swaprks )*
* <http://mGinger.com/index.jsp?inviteId=1023566>*

**Comment by swaprks** [comment]
@cdw9  I have my table inside a pop up i.e jquery ui. the problem is when i keep changing the tabs, the headers go on increasing in number.

**Comment by mkoryak** [comment]
I need to see a jsfiddle. I can't give you advice about code I've never seen

**Comment by mkoryak** [comment]
latest version adds support for tables within bootstrap3 and jqueryui tabs. they should "just work" now without any code on your part.
