### ISSUE TITLE
Width goes out of control when using Angular translate for titles

### ISSUE THREAD

**Issue by m3Lith** [mkoryak/floatThead#151]
I have a table and I'm using Angular translate to multi-localize headers. With 'Type' and 'Licence plate' declared as {{'VHC_LIST_TYPE' | translate}} and {{'VHC_LIST_PLATE' | translate}} it looks like that (all other header names are hardcoded):
http://i.imgur.com/4i4FTXE.png

Now, if I add a third translate tag, say {{'VHC_LIST_NAME' | translate}}, it looks like that:
http://i.imgur.com/tRXwcCX.png
The width of every column is increased, and as a result horizontal scrollbar appears.

I'm not sure what's the problem here, would love to get some help.

**EDIT**: heh, just noticed there's a new version of the plugin released hours ago, so I updated and it looks like my issue is solved. Just gonna keep this open while I do some more testing.

**Comment by mkoryak** [comment]
There was a bug with header widths that was fixed in that release.  See if setting enableAria to true in the options makes your bug come back.  I'm guessing it will.

If not,  and you still have issues,  give me a jsfiddle with issue and I'll help

**Comment by m3Lith** [comment]
Yup, enabling it messes the headers again.

Anyways, all is good now, closing.
