### ISSUE TITLE
IF: Is there a method to get IE working when all rows contain colspans?

### ISSUE THREAD

**Issue by k-risc** [mkoryak/floatThead#153]
http://mkoryak.github.io/floatThead/examples/row-groups/ describes how you can specify a row in a table that contains a full set of cells (if the first body row doesn't).

But what do you do if all rows contain colspans? As in http://jsfiddle.net/vvhp2e9g/14/

The first table renders o.k. as the first body row contains a full set of cells.

But the second table contains colspans in every row, just at different positions.

**Comment by mkoryak** [comment]
there is no way to do it with the plugin, unfortunately. But, you can hack it:
http://jsfiddle.net/vvhp2e9g/18/

if you know how many columns you have ahead of time.

**Comment by k-risc** [comment]
That's what I had in mind. Just wanted to make sure there isn't another way.

**Comment by mkoryak** [comment]
I wish there was man, but IE sucks.
