### ISSUE TITLE
Header/Column widths

### ISSUE THREAD

**Issue by jjjjjeff** [mkoryak/floatThead#155]
in window scrolling, when the header sticks, the header widths and the table column widths suddenly "disconnect" and they are both sized separately.  I was setting up this test file to demonstrate the issue and it happened before there was any scrolling...

http://valuinsight.com/TheadTest2.html

In the original file there were many more table rows and the issue did not appear until the headers scrolled to the top of the page.  In this test file,  there are few rows but the issue occurs immediately.

floatThead works well on other files that I would have thought very similar to this one.  I do not know what the difference is.

**Comment by mkoryak** [comment]
any update?

**Comment by mkoryak** [comment]
I guess not
