### ISSUE TITLE
Compatable Sorting Library

### ISSUE THREAD

**Issue by scotepi** [mkoryak/floatThead#157]
Are there any recommended sorting library's that are compatible? I have always used sorttable and it doesn't work well floatThead.

**Comment by mkoryak** [comment]
Sorry, I dont know - hopefully some user might chime in. If you provide a jsfiddle with sorttable giving you crap, I can take a look and see if its fixable on this end.

**Comment by mkoryak** [comment]
check here:
https://github.com/mkoryak/floatThead/issues/37
the jsfiddle has outdated script refs, but you might have luck with that sort plugin

**Comment by mkoryak** [comment]
cleaning up open issues
