### ISSUE TITLE
First row below header is hidden in IE 10

### ISSUE THREAD

**Issue by dineshedlapalli** [mkoryak/floatThead#160]
I have encountered an issue when first row below header is hidden in IE10 but it works without any issues in chrome. When I included headerCellSelector in options, the same behaviour is replicated in chrome and still doesn't work in IE10.
jQuery version - 2.1.1
floatThead version - 1.2.10
Here's the jsfiddle: http://jsfiddle.net/dineshe/833eLyod/
Any workarounds to resolve this issue?
Thanks

**Comment by dineshedlapalli** [comment]
Sorry, just figured out a way to resolve this issue by using getSizingRow option.

**Comment by mehdi-kha** [comment]
Hello!
I am facing the exact same problem on IE 11. The following Fiddle does not work properly:
http://jsfiddle.net/haasey/mb48z7j5/
Any idea?
Thanks in advance

**Comment by mkoryak** [comment]
Have you looked at the docs about getSizingRow?

**Comment by mkoryak** [comment]
You will need to add a non visible row (height 0) to your tbody and return it from that function. 

If you need more help open a new issue. It's hard to keep track of closed issues

**Comment by mehdi-kha** [comment]
Thank you very much for your response. I could finally work it around by adding a first fake row that I remove afterward dynamically with jQuery.

**Comment by mkoryak** [comment]
You probably shouldn't remove it. Does it still work if you resize the
window? If the table size changes it will break
