### ISSUE TITLE
Installing via bower main file is wrong

### ISSUE THREAD

**Issue by beazergood** [mkoryak/floatThead#161]
I'm installing via Bower and specifying ~1.2.10 yet when I look in bower.json when it's downloaded, the main file is "jquery.floatThead.js" which doesn't match the main stated in the bower.json file here.

Not sure why this is happenening, probably something i'm doing wrong, but I'm stumped!

**Comment by mkoryak** [comment]
its because that property was wrong in 1.2.10's bower. if its really giving you trouble and you have no workaround - ill cut 1.2.11 with a fix. let me know

**Comment by beazergood** [comment]
that would be great if you don't mind. I've tried this in my project bower.json file but it's just skipping the package altogether.
 "overrides": {
    "jquery.floatThead": {
      "main": "/bower_components/jquery.floatThead/dist/jquery.floatThead.js"
    }

**Comment by mkoryak** [comment]
sounds like you are using wiredep, in which case the correct override would be
```json
  "jquery.floatThead": {
    "main": "dist/jquery.floatThead.js"
  }
```

**Comment by mkoryak** [comment]
version 1.2.11 is out - let  me  know if it works any better

**Comment by beazergood** [comment]
That's done the trick. And thanks for the wiredep tip, that worked too. Top marks!
