### ISSUE TITLE
Flickering issue in safari 8

### ISSUE THREAD

**Issue by kamthamc** [mkoryak/floatThead#162]
Thank you for the great plugin. It works great in chrome and safari 7. But, when I use it in safari 8 I see the flickering issues. And I am using the basic configuration 
  scrollingTop: 0,
  useAbsolutePositioning: true (I Need to use this it causing alignment issues)

Can you please help me resolve it?

**Comment by mkoryak** [comment]
Maybe. I don't officially support safari, and debugging in it is a pain. If you provide a jsfiddle ill take a look

**Comment by kamthamc** [comment]
Thanks. I know its a lot of pain to debug in safari. I have created plunker [Demo](http://run.plnkr.co/60I9xyA9HRzLzYfY/) and [Source](http://plnkr.co/edit/Wvm2loKnpJuH0XosCBBi?p=preview).

**Comment by mkoryak** [comment]
when i load this in chrome, the header is not floated. Also, I am slammed at work right now so ill likely not get to this for some time. Sorry.

**Comment by mkoryak** [comment]
I wont be able to help you unless the header is floated on that plunkr. also, this is angularjs. if you can provide a simple jquery only example, it will be much easier to debug.

**Comment by mkoryak** [comment]
no response = closing
