### ISSUE TITLE
Using scroll wheel

### ISSUE THREAD

**Issue by Chris-S-** [mkoryak/floatThead#163]
I have a large table (about 50 columns) and many rows, and I use window scrolling.
All works OK when I scroll by dragging the scrollbar on the side of the page, however, when using the scroll wheel on the mouse, the header lags behind and bobs up/down when scrolling. When I stop scrolling, it settles in position.
What can work, is when the script detects scrolling, to hide the header, and when the scrolling stops, to display the header, so the header won't be visible while scrolling (thus no bobbing), but will become visible the moment scrolling stops.

**Comment by mkoryak** [comment]
have you played with the `useAbsolutePositioning` option? that might fix your problem

**Comment by Chris-S-** [comment]
The same, if this is the script:
$('#GridView1').floatThead({useAbsolutePositioning:true});

OS is Windows 8.1 and browsers IE 11 latest and Chrome's latest (40.0.2214.115 m).
Interesting, it works just fine on Firefox.
I'll display a message saying don't use the scroll wheel :-)

**Comment by mkoryak** [comment]
thats a good fix, or better yet, send all your users mice from 1994 :)

I can look at this issue on ie11 but not on windows 8, i only have vms for 7 - but only if you provide a real jsfiddle

**Comment by Chris-S-** [comment]
Misha, the thing is that the scroll wheel works like a ratchet, so it is not a smooth scroll, it sends start/stop scroll events all the time.
If I use the PgUp/PgDn keys, or the scroll bar, or not the scroll wheel :-), then all is OK.
Most of the people use laptops in any case (thus no scroll wheel), so I'll just use yours it as is. However, should you ever change this, and this message is still on the thread, please let me know!

**Comment by mkoryak** [comment]
`$('#GridView1').floatThead({useAbsolutePositioning:false});` would solve the problem. it will use fixed positioning and the `top` of the header would stay as 0 as you scroll.

**Comment by Chris-S-** [comment]
Nice! Not just another pretty face! :-)
So I am now using useAbsolutePositioning and it fixes the issue (I'm not going to ask why this is not the default).
I also had to use "reflow", as it gets a bit confused after postback.
Thanks Misha, I owe you the coffee that you mentioned on your Web site!

**Comment by mkoryak** [comment]
It should be the default for window scrolling. At least it was that way when I coded it 2 years ago. Next time I am in there ill check to see if I broke it :)

It might not be the default because that positioning mode does not place nice with tables that move within the dom because of elements added / removed from dom, hence it requires triggering `reflow` more often. 

Glad it solved your problem though.

**Comment by Chris-S-** [comment]
Believe me I am more glad than you that it solved my problem 😊
Now that we have the header working, how are we going to pin column(s) on the left hand side so they don’t scroll…






From: Misha Koryak
Sent: ‎Tuesday‎, ‎February‎ ‎24‎, ‎2015 ‎8‎:‎50‎ ‎PM
To: mkoryak/floatThead
Cc: Chris Botha





It should be the default for window scrolling. At least it was that way when I coded it 2 years ago. Next time I am in there ill check to see if I broke it :)

It might not be the default because that positioning mode does not place nice with tables that move within the dom because of elements added / removed from dom, hence it requires triggering reflow more often. 

Glad it solved your problem though.

**Comment by mkoryak** [comment]
You will need to find another plugin for that or write one. this plugin doesnt support that. Let me know what you end up doing - people like to request this feature

**Comment by Chris-S-** [comment]
Hi Misha, yes I am actually aware of the fact that your plugin doesn’t do this, I was just probing… 😊

I don’t think I’m going to bother right now with pinning the 1st column(s) on the left, though it definitely can come in handy (and will impress a user or two).

I am happy with your plugin though, thanks! 😊








From: Misha Koryak
Sent: ‎Wednesday‎, ‎February‎ ‎25‎, ‎2015 ‎10‎:‎35‎ ‎AM
To: mkoryak/floatThead
Cc: Chris Botha





You will need to find another plugin for that or write one. this plugin doesnt support that. Let me know what you end up doing - people like to request this feature

**Comment by michaelmmcrae1** [comment]
@Chris-S-  - I'm implementing an infinite scroll table - using web forms/POST-back, and we may have similar issues.

Sometimes, if I am scrolling during the post-back, the header will simply disappear, even if `reflow` and `floatThead` were called during the page load. Did you experience something like this?
