### ISSUE TITLE
Why floatThead-Container overflow:hidden?

### ISSUE THREAD

**Issue by ithielnor** [mkoryak/floatThead#166]
https://github.com/mkoryak/floatThead/blob/master/jquery.floatThead.js#L250

I need it to be visible for my implementation. I could use a style with `!important`, but that seems like a poor solution. Is it important for it to be `overflow:hidden`?

**Comment by mkoryak** [comment]
yes, it is important for it to have overflow hidden. it comes into play when there is horizontal scrolling. the header scrolls within that container. you can remove it only if you are sure that your tables will never have horizontal scrolling.

**Comment by ithielnor** [comment]
I'm using window scrolling. Does window scrolling support horizontal scroll?

**Comment by mkoryak** [comment]
yes, you can remove the overflow on window scrolling. the only reason it is there is because I never had any need to have it be any different :)

you can test it here:
http://mkoryak.github.io/floatThead/tests/big-table/

**Comment by mkoryak** [comment]
this change is now on master
