### ISSUE TITLE
offsetWidth = integer variable in IE problem

### ISSUE THREAD

**Issue by mhwlng** [mkoryak/floatThead#167]
in IE11, cell width of a table cell is a float e.g. 90.44

![ie11](https://cloud.githubusercontent.com/assets/1388886/6449009/04cb2306-c11e-11e4-8505-3c94eb33255e.png)
In IE11, offsetWidth returns an integer, so it is rounded to 90.
This causes the floathead cell text to be split over two lines
![iewrong](https://cloud.githubusercontent.com/assets/1388886/6449054/689d26ae-c11e-11e4-8d86-7bd3b0a738a8.png)

In Chrome, all is fine, the cells widths are also integers
![chrome](https://cloud.githubusercontent.com/assets/1388886/6449007/01b7dfba-c11e-11e4-864e-eead05d2a4b6.png)

I fixed the problem in IE, by replacing
$rowCells.get(i).offsetWidth
$fthCells.get(i).offsetWidth
with the getComputedStyle example code from :
http://vadikom.com/dailies/offsetwidth-offsetheight-useless-in-ie9-firefox4/

**Comment by mkoryak** [comment]
Thanks for the solution. I dont have time to get to this this week, so if you create a PR that would be a huge help.

**Comment by mkoryak** [comment]
sorry, i just noticed that `getComputedStyle` is an IE9+ thing. This plugin supports IE8.

I do see an issue in your testcase which ill try to fix

**Comment by mhwlng** [comment]
I tried your latest version using getBoundingClientRect in IE11
It doesn't work for me :
![getboundingclientrect](https://cloud.githubusercontent.com/assets/1388886/6571659/14a57af4-c70b-11e4-866f-f98d275f7a83.png)
![getcomputedstyle](https://cloud.githubusercontent.com/assets/1388886/6571660/18997b10-c70b-11e4-9cd5-1d7ee1d0c0f1.png)

**Comment by mkoryak** [comment]
Ill check it out. getBoundingClientRect might be slower than computedStyle. I realized this morning that i dont need to add padding and borders, so the code will be about 4 lines

**Comment by mhwlng** [comment]
This new version is even worse
tested in IE11 :
![untitled](https://cloud.githubusercontent.com/assets/1388886/6582333/f1bb8c16-c75c-11e4-984c-353c94cf9483.png)
