### ISSUE TITLE
code cleanup notes

### ISSUE THREAD

**Issue by jurko-gospodnetic** [mkoryak/floatThead#170]
Just some notes taken while researching this library. Hope they help.

```javascript
    if(createElements){ //make sure this is done only once no matter how many times you call the plugin fn
        //because chrome cant read <col> width, these elements are used for sizing the table. Need to create new elements because they must be unstyled by user's css.
        document.createElement('fthtr'); //tr
        document.createElement('fthtd'); //td
        document.createElement('fthfoot'); //tfoot
    }
```

1. The comment in [line 160](https://github.com/mkoryak/floatThead/blob/master/jquery.floatThead.js#L160) seems to indicate that it was the author's purpose not to create `fthtr`, `fthtd` & `fthfoot` DOM elements in case the plugin function gets called multiple time, but I don't think that is what the `if` in front of it does. It just avoids creating the elements on specific browser types but for those that it does allow creating those element, it does not prevent them from being created multiple times.

2. the `fthtr` element created there does not seem to be needed as it is not referenced anywhere in the rest of the floatThead sources, and some other `fthrow` elements seem to be used instead

3. for that matter `fthtd` & `fthfoot` elements do not seem to be needed either since such elements get created later on separately for each table and these initial ones do not seem to be used and just kludge up the DOM

**Comment by mkoryak** [comment]
1. 
that whole if statement can be removed. it was once used to create elements for ie8, but I have since changed the code to not create those elements in IE, so that statement does nothing

2.
fthrow should be renamed to fthtr to be consistent. 

3.
yep

Thanks for taking the time to read through the code AND to fix stuff, its very appreciated
