### ISSUE TITLE
Floating thead is drawn over the rest of the table

### ISSUE THREAD

**Issue by altxt** [mkoryak/floatThead#179]
It looks like table header does not reserve space for itself, and regular rows get scrolled to fill that space. More obvious with scrollingTop: 200
http://jsfiddle.net/ny2nw8zt/
Tested in Opera 12 and Firefox 36
I see a similar problem in jsfiddle for issue #160

**Comment by mkoryak** [comment]
not sure what i am looking at here. I checked your fiddle in FF 36 on mac and it looked just fine. maybe provide a screenshot ?

here is an updated fiddle, does this look broken to you?
http://jsfiddle.net/ny2nw8zt/1/

**Comment by altxt** [comment]
Huh, I did not realize that the header was, indeed, floating above the rest of the table, not moving the table down to make itself some room, and so it needed an opaque background. Dumb of me.
Thanks for the plugin and for quick feedback!
