### ISSUE TITLE
Floating header not aligning with table on window resize/shrink

### ISSUE THREAD

**Issue by alex-silverman** [mkoryak/floatThead#181]
I've seen a similar issue reported (and fixed) in a few places. The symptom of the similar issue I've seen was that the last column was being hidden. My issue is different in that the problem is the floating header is not staying aligned with the table (see attached image) when the window is resized down. At max window size, everything works perfectly. Then, as the window shrinks, the table becomes more and more misaligned.

I've tried reflow, debounce, useAbsolutePositioning = false, changed css in the inspector to see what that did. If it helps, I'm using Caspio, which may be part of the problem. I found instructions on implementing the floatTheader code in their datapages via their javascript solutions page: http://forums.caspio.com/index.php/topic/4678-j-freeze-header-in-a-tabular-report/

Finally, I've also attached an image of the html code via the inspect element feature in Chrome. Seemed easier than typing everything out. Please let me know what else you need, e.g. the css, a fiddle, etc.

Thanks!

Screenshot of issue:
![image](https://cloud.githubusercontent.com/assets/3285721/6966440/152dc8ea-d927-11e4-8711-e2ebd9388984.png)

Screenshot of html:
![image](https://cloud.githubusercontent.com/assets/3285721/6966450/22cc99d6-d927-11e4-9655-e65fa77e2719.png)

**Comment by mkoryak** [comment]
hard to say by looking at that what your problem might be. can you copy the generated code and paste it into jsfiddle so I can atleast inspect it?

**Comment by alex-silverman** [comment]
Can you be more specific about what part of the code you'd like to see? The code to create the floatThead table is here:

var $table = $("#cb_data_container table[name=cbTable]");
$table.find('tr > th').css('padding','5px');
$table.wrap( "<div class='wrapper'></div>" );
var v_tr = $("#cb_data_container table[name=cbTable] tr:nth-child(1)"); 
var v_clone = v_tr.clone(); 
var v_thead = $('<thead>'); 
v_thead.append(v_clone); 
$table.prepend(v_thead);
$(v_tr).hide();
$table.floatThead({
    scrollContainer: function($table){
        return $table.closest('.wrapper');
    }
});

As I said, we are working in Caspio, and the way their system works is to deploy these datapages, which essentially build some of the code in the backend. The result is a table with names, classes, and IDs set by Caspio. They also include minified scripts. I wouldn't be able to copy this "building" code. 

I wonder if it would be easier to give you a login to the site...let me see which I can do.

**Comment by alex-silverman** [comment]
working on the jsfiddle (not finished yet): https://jsfiddle.net/orf3s5fj/

you can see all the script stuff that Caspio has pre-written.

**Comment by mkoryak** [comment]
would it be possible for you to put in the non-rendered html in there and run the plugin code on it, or is it too difficult to rip out?

**Comment by mkoryak** [comment]
the code you pasted looks wrong. shouldnt it be
`
var v_thead = $('<thead></thead>'); 
v_thead.append(v_clone); 
$table.prepend(v_thead);
`

**Comment by alex-silverman** [comment]
you're right. I don't know where I got that from. Here's the code actually being implemented:


var $table = $("#cb_data_container table[name=cbTable]");
$table.find('tr > th').css('padding','5px');
$table.wrap( "<div class='wrapper'></div>" );
var v_tr = $("#cb_data_container table[name=cbTable] tr:nth-child(1)"); 
var v_clone = v_tr.clone(); 
var v_thead = $('<thead></thead>'); 
v_thead.append(v_clone); 
$table.prepend(v_thead);
$(v_tr).hide();
$table.floatThead({
    scrollContainer: function($table){
        return $table.closest('.wrapper');
    }
});

To answer your question, no, I think it would be too difficult to rip out. I'm working on setting up a test account for you, if that would be okay. I'm on a windows machine, btw, which I know has been part of the problem in the past.

**Comment by alex-silverman** [comment]
what's going on!? it won't copy that part of the code:

var $table = $("#cb_data_container table[name=cbTable]");
$table.find('tr > th').css('padding','5px');
$table.wrap( "<div class='wrapper'></div>" );
var v_tr = $("#cb_data_container table[name=cbTable] tr:nth-child(1)"); 
var v_clone = v_tr.clone(); 
var v_thead = $('<thead></thead>'); 
v_thead.append(v_clone); 
$table.prepend(v_thead);
$(v_tr).hide();
$table.floatThead({
scrollContainer: function($table){
return $table.closest('.wrapper');
}
});

**Comment by alex-silverman** [comment]
see above.

**Comment by mkoryak** [comment]
You can set up an account for me, but I dont promise that ill look at it today. I have a lot of stuff to do at work today :)

**Comment by mkoryak** [comment]
use three backticks for codeblocks. even better, three backticks followed by js, edit your last example to see what i did

**Comment by alex-silverman** [comment]
unfortunately, adding an account for you is too complicated when the data is so sensitive. Thanks, anyway!

**Comment by mkoryak** [comment]
well, i will poke around this some more tonight, but it might be too much of a mess to be able to figure out what happened

**Comment by mkoryak** [comment]
I looked at your html some more, its very hard to tell what is happening. It might have to do with css styles. I noticed that you have some inline styles on the table that has the header in it that dont match the styles on the "real" table.  There is a style that sets border to `0 none` which doesnt match the original table. The styles on the tables must match (aside from the styles that the plugin adds)
rule of thumb is to not use any inline styles and make your selectors target your table by class.

also, noticed this style:

```
.floatThead-wrapper tbody {
overflow-y:scroll;
height:400px;
} 
```

you do not need that, i have no idea what kind of bad things it will do.

Thats about it, im closing this because there is nothing more I can do here. Good luck

**Comment by mkoryak** [comment]
you might also want to read this

http://mkoryak.github.io/floatThead/faq/

**Comment by alex-silverman** [comment]
Thanks for looking into it. Really appreciate your time. I'll let you know
what, if anything, fixes it.

**Comment by alex-silverman** [comment]
Misha,

I have another page on which this problem is not occurring. I'll refer to
that table as CORRECT. The only difference between the two pages, I
believe, is the number of columns in the table. There are some differences
between them though:

1) The CORRECT page's table within my wrapper div within floatThead-wrapper
has a minimum min-width of 723px. The INCORRECT table within
floatThead-wrapper has a minimum min-width of 826px. My guess is that this
is based on the number of columns(?).
2) The CORRECT page's *floatThead-table's width *decreases slightly as the
window is resized (width goes from 100% at max window size to 99.8% at
minimum window size). The INCORRECT page's *floatThead-table's width *actually
*increases* as the window is resized (width goes from 100% at max window
size to 113.9% at minimum window size).

It seems like (2) is the real issue here. Or is at a leas ta symptom. How
is this table's width calculated in this way?

Thanks!

**Comment by alex-silverman** [comment]
All set. Figured it out. It was a stylign issue. Thanks again!
