### ISSUE TITLE
Jquery floatThead doesn't work with percentage height

### ISSUE THREAD

**Issue by tusharughade** [mkoryak/floatThead#182]
Hello,
I working on a table which has height in Percentage,
Jquery floatThead doesn't work with percentage height.

Find jsFiddle: http://jsfiddle.net/DxX2T/203/

**Comment by mkoryak** [comment]
You have to use fixed positioning to work with percentage heights, also in your original fiddle the percentage wouldnt work anyway because no parent element had a pixel height. see working fiddle:

http://jsfiddle.net/DxX2T/205/

**Comment by tusharughade** [comment]
Thanks mkoryak,

That worked for me, Thanks a lot for you Help :+1: :100:

**Comment by vinika02** [comment]
Please try this. It's worked for me

  var $table = $('table.table-wages');
        $table.floatThead({
            scrollingTop: 0,
            useAbsolutePositioning: false,
            scrollContainer: function($table){
                return $table.closest('.table-wages-container');
            }

        });
// try to resize table thead. tr
$(".size-row,.floatThead-col").css("height", '48px');

**Comment by mkoryak** [comment]
This size will be changed next time the plug-in reflows. Try resizing the
window, and your size will change back to what it was before.

**Comment by vinika02** [comment]
Hi, you are right. Sometimes my layout have a little margin on right side.
Do you have an explanation about this? What is the best way to use
floatThead?
[image: image.png]

**Comment by mkoryak** [comment]
Your attached image didn't make it to GitHub, but either way please open a new issue and create a jsfiddle if you want anything more than a guess about what your problem might be.
