### ISSUE TITLE
reflow doesnt work if plugin ran on table with tbody which is later added

### ISSUE THREAD

**Issue by mkoryak** [mkoryak/floatThead#186]
tbody jumps when you start scrolling if it's not created before the first floatThead and scrolls smoothly if declared before?
( scrolling behavior http://jsfiddle.net/9eo8gjag/7/ vs http://jsfiddle.net/9eo8gjag/6/ )

**Comment by mkoryak** [comment]
an idea for a fix is to add a lazy flag to the floatThead data i attach to the element and not init if there is no thead or tbody, on reflow check the lazy flag and init if lazy is true

**Comment by mkoryak** [comment]
also, this is related: 
http://jsfiddle.net/9eo8gjag/9/

see fiddle for bug

**Comment by sentbyravens** [comment]
Sorry me, I am new on GitHub and dont know how to create new theme. I found a new bud of your script: Excel export don't work properly with it. In exported table.xls i can see only <tbody> content without <thead>. There is a part of export script (creates template for Excel):

template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8"></head><body><table class="parus-table floatThead-table">{table}</table></body></html>' 
![screenshot_23](https://cloud.githubusercontent.com/assets/11899659/7101338/845cbd56-e05d-11e4-8095-28561398c113.jpg)
Sorry for my English, hope you will understand me
