### ISSUE TITLE
Float Header have many tr and, td have colspan, rowspan

### ISSUE THREAD

**Issue by tanobi92** [mkoryak/floatThead#189]
I have a Table:
![screenshot 2015-04-13 17 05 35](https://cloud.githubusercontent.com/assets/11570162/7113595/90b4f7d2-e1ff-11e4-91ef-28e70465e9b6.png)
I use floatThead, I have checkboxs wich it show/hiden column. I put $('#'+tableid+'').floatThead() in function checkbox. I check the first, table show columns
![screenshot 2015-04-13 17 16 21](https://cloud.githubusercontent.com/assets/11570162/7113743/06ad6ab8-e201-11e4-8b70-a147e276e97b.png)
 but the second, it not show header. I don't find cell $('#'+tableid+'').find('tr:eq("'+row+'") th:eq("'+cell+'")').
I think $('#'+tableid+'').floatThead() inhibitory it active.
Help me, please! Thank you very much!

**Comment by mkoryak** [comment]
sorry, I don't understand what the problem is. If you put it on jsfiddle I may be able to help. I cannot help by looking at pictures

**Comment by tanobi92** [comment]
@mkoryak Thank you for answer! 
I created jsfiddle but have error add css, js exteral. I read code js function reflow(). I look you call unfloat(), refloat().Do you use unfloat() to remove fixed header? And refloat() call fixed header? If it true, How to call unfloat() like <script>$('#tbOPB').floatThead()</script>

**Comment by mkoryak** [comment]
sorry, not following you. Please include a working jsfiddle

**Comment by tanobi92** [comment]
Hi @mkoryak my demo: http://jsfiddle.net/TaNoBi/hsxpj0qo/7/
When load page, columns( KL4, Mở cửa, Cao nhất, Thấp nhất, Trung bình, NN mua, NN bán, Room còn lại) hiden.
$.each(OBJOPTION, function(){
				var defaults = Utils.Defaut('tbOPB',this[1]);
				
				Utils.ShowHiden(defaults[0],defaults[1], defaults[2]);
				//if(typeof checkcookie == "undefined"){
					SHOW.innerHTML += ('<input class="cbCheck" type="checkbox" id="'+("cb" + defaults[1].index())+'" />'+names+'');
				//}
			})
			//var defaults = Utils.Defaut('tbOPB',0);
			$('#tbOPB').floatThead();
			// Xu ly su kien checkbox
			$('.cbCheck').click(function(){
				var checked = this.checked;
				var strs = this.id.split("cb");	
				var defaults =Utils.Defaut('tbOPB',parseInt(strs[1]), checked,false);
				Utils.ShowHiden(defaults[0], defaults[1], defaults[2])
				
			})
After click checkbox table show/hiden the column. But the header fixed, not find tagName 'th'. => don't show/hiden 'th'. Help me! Thank you!

**Comment by mkoryak** [comment]
Hey, sorry but this code is a mess, I don't have time to try to figure out what is happening here. 
I noticed one problem. in your code you do this:
`x[6].colSpan = '6';`
this sets the colspan of a spacer column that floatThead has injected into your original table's thead. The sizer row contains the exact number of columns your table has without any colspans. Your code sets colspan of one of those columns to 6 which messes up the plugin. 

In the docs page that i linked to you about dealing with hidden columns I suggest that you cache references to your header cells before you run the plugin. You should do that - select them before the plugin is run and dont re-select them again

**Comment by tanobi92** [comment]
I also think select them before the plubin is run. But  problem is set colSpan. Because: Page load default colspan = 6 (two columns KL4 are hiden), when I click KL4 => show => colspan = 7, I need unfloat Thead. :( . @mkoryak, Do you not have idea to unfloat?

**Comment by mkoryak** [comment]
destroy the plugin and reinit

**Comment by tanobi92** [comment]
How to destroy the plugin and reinit?

**Comment by mkoryak** [comment]
```js
$table.floatThead('destroy').floatThead();
```

I also have a doc site, which you can read instead of asking me here

**Comment by tanobi92** [comment]
@mkoryak! WWWWOWWWWWWWWWWW! Thank you very much :+1: :) You are pro!
It run very good.
