### ISSUE TITLE
huge data bug on chrome

### ISSUE THREAD

**Issue by majimboo** [mkoryak/floatThead#190]
When working with a huge amount of data the tab with this plugin on chrome just suddenly stops working. Being used with angular as an directive.

**Comment by mkoryak** [comment]
https://github.com/mkoryak/floatThead#how-to-get-help-with-the-floatthead

**Comment by mkoryak** [comment]
While I try to support angular, this plugin will break if angular re-renderers some part of a the dom that this plugin caches a reference to. I cache references for performance reasons, and if you blow away those references with angular it will break. Do you have the same problem on a static table not rendered with angular?

**Comment by mkoryak** [comment]
no response, closing. reopen if you get a fiddle together reproducing the issue.
