### ISSUE TITLE
jQuery dependency in bower.json too high?

### ISSUE THREAD

**Issue by DukeyToo** [mkoryak/floatThead#191]
Is the jQuery dependency of >= 1.9.0 necessary?  I'm using 1.7.2 and not seeing any issues, but am worried that I'm missing something.

**Comment by mkoryak** [comment]
It might be too high, but you are also missing out on something: http://jqueryui.com/resources/download/jquery-ui-1.8.24.zip

you need that with 1.7.x 

bumping it down to 1.8 seems reasonable though. 

out of curiosity, why are you on such an old version?

**Comment by DukeyToo** [comment]
Thanks for the thoughtful response.  We are using a fairly new version of jqueryui, so that explains why it works for me.

Why an old version? Same old thing - a business app, and it risks regressions to update libs, so it is stuck on an old version unless there is good motivation to upgrade.
