### ISSUE TITLE
Print Style

### ISSUE THREAD

**Issue by ppalladino** [mkoryak/floatThead#192]
I am working on this on my end, however, any suggestions would be appreciated. I am trying to support printable large tables using print css. Because the table is large (~150% of view port) and overflow is set to scroll, the table is cut off when printing. I am resolving this by re-sizing the table via print css. The only issue with this is that floatTheader uses JS to calculate its col widths, so print css will not work. I was thinking about hiding the floatTheader table and show the original thead, but floatTheader removes the content from them, so that will not work either. Any ideas about direction?

**Comment by mkoryak** [comment]
2 thoughts here:

I dont know much about how print css works, but you can try hiding the following elements with display:none within your table (select it by class to be sure to select the floated table as well): 
```css
colgroup, col, fthfoot {
  display:none;
}
```
that will deactivate the cols that floatThead adds widths to, so maybe the widths you set with css will take effect. 

if that doesnt work, you can destroy the plugin on print and reinit after printing is done

finally another useful method might be `.floatThead('getRowGroups')` which Returns the table's `thead`, `tbody` and `tfoot` elements, you might be able to clone them and shove them into a new table used solely for printing


Let me know what you end up doing, I would be interested in putting a code sample on the docs page about how to do this

**Comment by ppalladino** [comment]
Ah! Awesome suggestions. I will certainly report back....

**Comment by mkoryak** [comment]
so, how did it go?

**Comment by ppalladino** [comment]
Hey!

I got pulled in another direction at work. I'll be revisiting this in the
next few days.

Regards,
Paul Palladino

**Comment by ppalladino** [comment]
Ok, so I finally have been able to come back to this. But, unfortunately, the plugin no longer works. I have multiple tbody elements (which is perfectly legal) and seems to be breaking things. I am sure this is an edge case.....

**Comment by mkoryak** [comment]
I didnt know that having multiple tbody elements is legal, but now that I do, ill file myself a bug and fix it

**Comment by ppalladino** [comment]
Wow, OK that is awesome! Yeah, multiple tbody elements is kinda useful if you are aware that it is valid....

**Comment by mkoryak** [comment]
why is it useful though? easier selection of groups of stuff in scripts?

**Comment by ppalladino** [comment]
yeah exactly, so in this case, each record has 2 rows. One with basic info and another with optional info that can be collapsed. It makes scripting and styling much more simple. Again, I know this an edge case ;)

**Comment by mkoryak** [comment]
I like to think that the reason that this plugin is better than the others is that it works in non-trivial use cases. That being said, it appears to work with multiple tbody elements:

http://mkoryak.github.io/floatThead/tests/issue-201/

maybe you can create a jsfiddle with your code and ill see if I can make it work. You are probably missing a `$table.trigger('reflow')` somewhere after modifying the table's dom. 

One thing you can try (in latest chrome only) is initializing the plugin like this:
```js
$table.floatThead({autoReflow: true});
```
which uses MutationObserver to make the plugin magically work in most cases.

**Comment by ppalladino** [comment]
Sweet! Will do....

**Comment by mkoryak** [comment]
going to close this, but if you end up coming up with a style you can share, please reopen. Thanks!
