### ISSUE TITLE
size -row Header show brower Safari different size-row in f12 debug

### ISSUE THREAD

**Issue by tanobi92** [mkoryak/floatThead#193]
I use Safari see size -row of Thead on brower is 49px, and have a space between Thead and Tbody is 9px.
![screenshot 2015-04-16 11 08 28](https://cloud.githubusercontent.com/assets/11570162/7173911/49462b56-e429-11e4-8e27-1223fe47a1c8.png)
Chrome, IE, FireFox haven't space.
![screenshot 2015-04-16 11 08 57](https://cloud.githubusercontent.com/assets/11570162/7173965/482f5782-e42a-11e4-9c46-762028e4d3d6.png)
Demo: http://jsfiddle.net/TaNoBi/hsxpj0qo/12/
Help me, please! 
Thank you very much!

**Comment by mkoryak** [comment]
Sorry, safari is not supported by this plugin. Also, I couldnt reproduce your issue in my safari. 

few suggestions:
you have 2 window.onload functions that do the same thing in your code, this is probably causing issues.

you can try initializing floatThead like this
`$('#tbOPB').floatThead({useAbsolutePositioning:false});`

**Comment by tanobi92** [comment]
@mkoryak , I deleted one window.onload, and added $('#tbOPB').floatThead({useAbsolutePositioning:false}); but didn't success :(.

**Comment by mkoryak** [comment]
Sorry, I cant help you, both because I cannot reproduce it locally and because I don't have time or desire to support safari.

**Comment by tanobi92** [comment]
Ok @mkoryak , I'll try. Thank you

**Comment by tanobi92** [comment]
Hi @mkoryak I fixed error :). I subtraction 9 for height on funtion:
function setHeaderHeight(){
        var headerHeight = 0;
        $header.find("tr:visible").each(function(){
          headerHeight += $(this).outerHeight(true);
        });
		
        $sizerRow.outerHeight(headerHeight - 9);
        //console.log(headerHeight + 'abc' + $sizerRow)
        $sizerCells.outerHeight(headerHeight - 9);
        //console.log(headerHeight )
      }

**Comment by mkoryak** [comment]
why 9? sounds like a magic number that only works for your table :) 

You should try the latest code in [master](https://github.com/mkoryak/floatThead/blob/master/dist/jquery.floatThead.min.js) - I made some changes to that function that might solve your problem

**Comment by tanobi92** [comment]
Hi @mkoryak , I tried your lastest code, It fixed my error, but have new error.
![screenshot 2015-04-20 08 45 31](https://cloud.githubusercontent.com/assets/11570162/7222500/1b458396-e73a-11e4-829d-abb84b6782dd.png)
When I start move scroll, have space
![screenshot 2015-04-20 08 45 14](https://cloud.githubusercontent.com/assets/11570162/7222534/cedaeefa-e73a-11e4-9ce6-c8370cb5d3f8.png)

**Comment by mkoryak** [comment]
yeah - that fix is no good. I need a new fix, but not sure when ill get to it.

**Comment by tanobi92** [comment]
I hope you fix error soon. Thank you :)

**Comment by mkoryak** [comment]
commited some code. hopefully this fixed it for you
