### ISSUE TITLE
Can't get inner scrolling to work

### ISSUE THREAD

**Issue by pmeems** [mkoryak/floatThead#195]
I'm using the code sample from http://mkoryak.github.io/floatThead/examples/inner-scroll/
But I get 'pageTop is not defined.'
I'm not sure what it should be.
And I don't even know if this is solving my design issue.
I've been trying for hours now, trying all kinds of css tricks and hacks.
I'm using Bootstrap.

This is my situation:
I have a page with a header, some content and a table and two buttons.
I need the header and the two buttons (footer) to be visible at any height of the view port.
I put the content and table in a container and positioned it absolute, making my layout work as I want:
The container is scrollable and the header and buttons are always visible. 
But now the table headers are no longer sticky. When I remove the absolute positioning the table headers are sticky again, but now my container is not scrollable anymore and my buttons float over my table.

Could you please assist me combining these two requirements?

Thanks,

Paul

**Comment by mkoryak** [comment]
pageTop is not defined because its a function that returns the height of my navbar on my demo page. I am going to remove it from the example code because this has confused people in the past. 


I am not sure I understand your requirements. if you provide a jsfiddle I can help you further.

**Comment by pmeems** [comment]
Thanks for your fast reply.
I tried making a simple page to show-case by problem, but in that case your plug-in works great ;)

So I used one of my production pages, which are much more complex: http://jsfiddle.net/m5f09cvu/
This page has a fix header and a fixed footer and a scrollable middle.
This middle part also has a header and 1 or more tables. Each table has a title above it.
The table headers (blue in my example) should stick. The header of the first table is sticking, but already on scroll and not when the header is out of the view. The header of the second table are invisible and don't come back.

If you look at the HTML code you'll see a lot of knockout code. In my example they are irrelevant.
The page is an existing page in our application which I'm converting to Bootstrap. It is possible I have some wrong css, which might explain why I can't your plug-in to work.

Please advice how I can get my complex page to work with your great plug-in.

Thanks,
Paul

**Comment by mkoryak** [comment]
This is a bit closer to what you want:

http://jsfiddle.net/m5f09cvu/1/

the reason it cuts off like that is that the scrolling table sizes itself to be the width of the scrollContainer, and your table is actually wider than that container. You should be able to figure out how to make the scrolling container's width match the table width with css and that will fix that last problem.

**Comment by pmeems** [comment]
Thanks for your response and your sample.
I will incorporate it with our production design.
Do I understand it correctly you only changed the jquery part in your sample?

**Comment by mkoryak** [comment]
yes, i only changed the javascript - you will need to change the css to fix the remaining minor issue, you can also try to use javascript to set the width of `.floatThead-container` after the header is floated. 

If you use the latest code in master (that hasnt been released yet because of 1 outstanding bug) you can do something like this:

http://jsfiddle.net/m5f09cvu/2/

**Comment by mkoryak** [comment]
I assume you are all set now?
