### ISSUE TITLE
On Event isn't working

### ISSUE THREAD

**Issue by iansoper** [mkoryak/floatThead#196]
I tried to implement the example that you've included of adding and removing classes if the table is being floated. I used your example verbatim, except for changing the selector to my own table, and I can't get the even to trigger. Is there i
```js
$('table.treatments--list').on("floatThead", function(e, isFloated, $floatContainer){
    if(isFloated){
        $floatContainer.addClass("floated"); // the div containing the table containing the thead
        $(this).addClass("floated"); // $table
    } else {
        $floatContainer.removeClass("floated");
        $(this).removeClass("floated");
    }
});
```

**Comment by mkoryak** [comment]
probably because the docs refer to code that is in master, but has not been released yet. maybe I should note that somewhere, or add versions to things in the docs

**Comment by iansoper** [comment]
I tried installing master, but I still can't get this to work.

**Comment by mkoryak** [comment]
provide a jsfiddle and i can take a look. on the demo page though, there is a working example:

```js
$('table.demo2').on("floatThead", function(e, isFloated, $floatContainer){
            if(isFloated){
                $floatContainer.addClass("floated"); // the div containing the table containing the thead
                $(this).addClass("floated"); // $table
            } else {
                $floatContainer.removeClass("floated");
                $(this).removeClass("floated");
            }
        })
```

**Comment by iansoper** [comment]
It works! My mistake. thanks for the help.
