### ISSUE TITLE
Table Head Moves along with Horizontal scroll 

### ISSUE THREAD

**Issue by tusharughade** [mkoryak/floatThead#197]
Hello,
I have successfully integrated FloatThead.js in my project but now I am facing one Issue.
The problem in when we reduce the width of the browser Horizontal scroll appears as min-width of the on the wrapper is 1024px, When you move the scroll the Table head also moves along with it.
Please find my code below 
var $table = $('#kpiTable');
      $table.floatThead({
          scrollContainer: function ($table) {
              return $table.closest('.kpiTableContainer');
          },
          useAbsolutePositioning:false
      });

but when I change useAbsolutePositioning:true it works fine it doesn't with useAbsolutePositioning:false
the problem is I'll have to use useAbsolutePositioning:false as the wrapper height is in %.

Any solution for this?

please find screen shot below
![before-scroll](https://cloud.githubusercontent.com/assets/9526673/7413721/b5dd5ad0-ef6b-11e4-81ac-d6c5b5f0cd29.jpg)
![after-scroll](https://cloud.githubusercontent.com/assets/9526673/7413722/b5f0485c-ef6b-11e4-8149-4c7b79d55b41.jpg)

**Comment by mkoryak** [comment]
i need a jsfiddle reproducing this issue if you want me to help you. please provide one

**Comment by mkoryak** [comment]
no response - closing

**Comment by tusharughade** [comment]
Hello mkoryak,
Really sorry for the delay, I was trying to create the jsfiddle but unfortunately couldn't as the table gets dynamically created using Marionette.js.

But I noticed one difference between your table example and my implemented table 
when there is a horizontal scroll and on scrolling your table
"<div class="floatThead-floatContainer floatThead-container" aria-hidden="true" style="overflow: hidden; position: fixed; margin-top: 0px; top: 478.283px; z-index: 1001; width: 779px; left: 230px;">"
left position gets updated
But in my case it doesn't and that's the reason the table header flows along with the scroll.
