### ISSUE TITLE
Table Head Moves along with Horizontal scroll2

### ISSUE THREAD

**Issue by tusharughade** [mkoryak/floatThead#198]
Please refer to #197

Hello mkoryak,
Really sorry for the delay, I was trying to create the jsfiddle but unfortunately couldn't as the table gets dynamically created using Marionette.js.

But I noticed one difference between your table example and my implemented table 
when there is a horizontal scroll and on scrolling your table the Left position of **class="floatThead-floatContainer floatThead-container" aria-hidden="true" style="overflow: hidden; position: fixed; margin-top: 0px; top: 478.283px; z-index: 1001; width: 779px; left: 230px;"** gets change

But in my case it doesn't and that's the reason the table header flows along with the scroll.

**Comment by mkoryak** [comment]
sorry, i cannot do anything with this information. everyone's tables are different. try this:

let your js generate the table but dont run floatThead on it. view the generated html and paste it into jsfiddle, then add the floatThead code and see if you can reproduce your issue. 

I cannot provide help without seeing code - i really have no idea what is wrong

**Comment by tusharughade** [comment]
Ok, I'll do that and will provide you with the js fiddle

**Comment by tusharughade** [comment]
Please find the jsfiddle below
http://jsfiddle.net/tpyrxrej/

its doesn't get replicate in the Jsfiddle but it gets reproduce in my project
I did debugging the Markup but not able to understand whats going wrong there.

**Comment by mkoryak** [comment]
I am also not able to understand what the problem here is.

**Comment by mkoryak** [comment]
I can't help you with a problem I can't see

**Comment by tusharughade** [comment]
Yes I understand, Its very difficult to track the Issue.
I'll check at my end, Thanks for your quick reply's and Help!

**Comment by mkoryak** [comment]
closing this, just reopen in if you can make a working fiddle
