### ISSUE TITLE
Issues with Fixed Header on setting Dynamic Height.

### ISSUE THREAD

**Issue by vikashshukla** [mkoryak/floatThead#199]
Hi,

I am facing problem in Fixing header  height dynamically.

http://jsfiddle.net/VikashShukla/dFp6f/22/
Please go through above link and Click on any 'Save Click' button, 
After this my header is not sticking to the desired position below the iframe.

thanks in advance.

**Comment by mkoryak** [comment]
Here is the proper way to do it:
http://jsfiddle.net/dFp6f/24/

**Comment by vikashshukla** [comment]
Thanks you made my week end...
