### ISSUE TITLE
IE11 first row cut off

### ISSUE THREAD

**Issue by bluezed** [mkoryak/floatThead#200]
Hi there,

really like your plugin and have been using it for a while. 

However, in a new project I have to support IE11 and the plugin keeps cutting off the first row of my tables. I can even see this effect on your demo page when I go there with IE11.

I'm already using this Meta-tag in my page: 
```<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />```

Here a couple of screenshots:
![Before activation](http://s19.postimg.org/akqeeyc0v/before.png)
![After activation](http://s19.postimg.org/cqkp9gfhb/after.png)

Anything I'm missing here!?

Thanks!

**Comment by mkoryak** [comment]
you are missing a jsfiddle :P

**Comment by bluezed** [comment]
Strange... with jsfiddle I cannot reproduce it at all using the sample from your demo page. It seems to work ok with v1.2.11: http://jsfiddle.net/avar9gor
And also with v1.2.12dev: http://jsfiddle.net/avar9gor/1/

**Comment by mkoryak** [comment]
reopen this if you can reproduce the issue on jsfiddle

**Comment by nxtreme** [comment]
Hello I just suscribed on GitHub because I had the same problem on V1.2.11 with IE10 and a I found a solution by replaceing line 345:

var headerHeight = parseFloat(getComputedStyle($header[0])['height'])
by
var headerHeight = parseFloat($header[0].offsetHeight)

I hope this will help.
