### ISSUE TITLE
th compressed in bootstrap tabpanel

### ISSUE THREAD

**Issue by sintasy** [mkoryak/floatThead#202]
this is bug, feature or my mistake? :)
http://jsfiddle.net/muruadvm/
before scrolling second tab look like:
![scr_2015-05-20 15 37 12](https://cloud.githubusercontent.com/assets/7446682/7725758/211d8d70-ff06-11e4-9a29-7f09799312b5.png)

**Comment by mehrdd** [comment]
+1
I'm having this problem too,
and it will get worse with `scrollContainer()`

**Comment by mkoryak** [comment]
this is very related

https://github.com/mkoryak/floatThead/issues/116

**Comment by mehrdd** [comment]
You are right .. thanks for the answer ...

**Comment by sintasy** [comment]
thanks

**Comment by sintasy** [comment]
but here http://jsfiddle.net/qj93cz1n/7/ in chrome if you change window width and change nav tab this don't work:
![scr_2015-05-21 12 10 20](https://cloud.githubusercontent.com/assets/7446682/7745261/81998616-ffb2-11e4-9698-fabae87f9443.png)

**Comment by mehrdd** [comment]
oh ! i didn't know that ...
is there a clear-way to fix that issue ?

**Comment by mkoryak** [comment]
thats what reflow is for:

http://jsfiddle.net/qj93cz1n/14/

**Comment by mkoryak** [comment]
actually, that example is needlessly complicated, all you need to do is reflow the plugin when the tab is shown:

http://jsfiddle.net/muruadvm/1/

**Comment by sintasy** [comment]
great, thanks.
