### ISSUE TITLE
Problem with header while change tab pane.

### ISSUE THREAD

**Issue by qinshuang** [mkoryak/floatThead#204]
Here is an example : http://jsfiddle.net/qins/7gf2e9d3/2/
Change view from Tab1 to Tab2.  table2 header display error.

**Comment by mkoryak** [comment]
see https://github.com/mkoryak/floatThead/issues/202

**Comment by mkoryak** [comment]
http://jsfiddle.net/7gf2e9d3/3/

**Comment by qinshuang** [comment]
Thank you very much!
