### ISSUE TITLE
Need some hints with css: header with scrollbar seems to get distorted when applying floatThead

### ISSUE THREAD

**Issue by dszabo** [mkoryak/floatThead#205]
I am no css master at all :(

If you could help me sorting this out I would be very grateful! Thanks! See the comments in jsFiddle under the js script section.

https://jsfiddle.net/dszabo/j6vtodsq/1/

**Comment by dszabo** [comment]
https://jsfiddle.net/dszabo/j6vtodsq/4/

**Comment by mkoryak** [comment]
- you were not including floatThead javascript in the fiddle
- i styled the table a bit so you can see what is happening
- the wrapper that you supplied to floatThead was not the element with overflow:auto, which it should be
- always style and select your table by class
- you are using a top/bottom sticky layout, so this plugin must run with `useAbsolutePositioning:false`

https://jsfiddle.net/j6vtodsq/5/

good luck

**Comment by dszabo** [comment]
Thank you very much for your detailed responses!
