### ISSUE TITLE
Duplicate header appears when refresh browser window to a scrolled position

### ISSUE THREAD

**Issue by willapp** [mkoryak/floatThead#207]
Not sure if this has been raised before but it happens in Chrome 43.0.2357.81, Firefox 37.0.2 and IE 8.0.7601.17514.

We have a long table which goes off the bottom of the page. On initial load floatThead works fine (called via document.ready) and when you scroll down the header stays fixed to the top. However, once scrolled down and the header is in its fixed (detached) position, if you refresh the page using F5, the page reloads back to its scrolled position but now a second duplicate header appears beneath the bottom of the table. The upper header row behaves as normal (attaching/detaching as you scroll) while the duplicate stays on the bottom of the table.

A workaround exists by delaying the floatThead invocation using `setTimeout` e.g.:

    $(document).ready(function() {
        window.setTimeout(setFloatThead, 500);
    });

    function setFloatThead() {
        var table = $("#myTable");

        table.floatThead({
            useAbsolutePositioning: false
        });
    }

The delay can be lowered but during testing, values of 200ms or less sometimes resulted in the bug re-appearing but not at all times. Suspect this may be an issue with the ordering of events when the browser restores the current scroll position but it is consistent across the above browsers.

**Comment by mkoryak** [comment]
can you put this on jsfiddle so i can take a look?

**Comment by willapp** [comment]
Ok I will try. Have tried to reproduce it from scratch with a more simple html page but it doesn't seem to happen. I think it must be related to either the amount of content on the page and/or other scripts that may be running on page load so it could be hard to reproduce it reliably. Unfortunately the page we are using it on is not public and contains sensitive data but I will see if I can make it happen in another situation.

**Comment by mkoryak** [comment]
ok, then it makes sense that I cant fix anything on my end right?

**Comment by mkoryak** [comment]
closing, reopen if you can reproduce without your other js code possibly breaking stuff
