### ISSUE TITLE
Header not showing correctly when using Bootstrap Tabs

### ISSUE THREAD

**Issue by brothers28** [mkoryak/floatThead#210]
Hi together

First of all thank you @mkoryak for your awesome floatThead!
Everytime I was using it, it just worked perfectly. 

Until now...

In one of my new Projects I'm working on, I'm using floatThead inside a Bootstrap Tabstrip (http://getbootstrap.com/javascript/#tabs).
The problem now is, that when I have for example 2 Tabs with a table inside of each, the table in the second Tab won't show the table header correctly. 

![image](https://cloud.githubusercontent.com/assets/12660121/7884161/3552d580-061c-11e5-88bf-865bdd0e9b52.png)

I've created this little jsfiddle for you to show my problem: http://jsfiddle.net/ebakc4y5/1/  (NOTICE: You have to resize the result box, that you can Scroll inside the table)

Any help will be appreciated :smile:

**Comment by mkoryak** [comment]
Search issues, just had this same issue solved.  Also faq
