### ISSUE TITLE
Delegated events inside table get killed when attaching this

### ISSUE THREAD

**Issue by rclai** [mkoryak/floatThead#211]
This plugin is sooo good! But then it killed my row event handlers.

```js
// Kills all my event handlers inside .my-table
$('.my-table').floatThead();
```

**Comment by mkoryak** [comment]
i don't believe you, unless you were delegating them, in which case you need to change your delegation selector. Either way, if you want me do do something about it, please provide a jsfiddle.

**Comment by rclai** [comment]
Yes, they were being delegated I believe. It's kind of tough to provide a repo because I'm using it inside a Meteor app.

**Comment by mkoryak** [comment]
no, i don't know meteor.

if they were being delegated, then you just need to fix the selector. your thead is moved into another dynamically created table which goes under your table, and perhaps a wrapper depending on which options you used. 

you need to float the header, take a look at the dom inspector and see where it is located. you should be able to update your delegation selector to work for both floating mode and non-floating mode.

without seeing your code, this will work:
give your table(s) a new class `myTableFoo`, change the delegate selector to `.myTableFoo tr` - this will match `tr` element in both floating and non-floating mode.

**Comment by mkoryak** [comment]
still need help with this?

**Comment by rclai** [comment]
I haven't gotten a chance to try this out yet, I will try tomorrow.

**Comment by rclai** [comment]
Still no luck here. It must have something to do with the way the table gets wrapped in the `div`.

**Comment by mkoryak** [comment]
event delegation, if done right, should work. Perhaps meteor is doing some magic behind the scenes that you need to understand before you can solve this.

**Comment by mkoryak** [comment]
you can put up the equivalent of a jsfiddle for meteor if you want. I make no promises though since I dont know meteor

**Comment by mkoryak** [comment]
reopen if you can come with something reproducing the issue you are facing. Its not a bug with this lib though.
