### ISSUE TITLE
scrollingTop issue IE9 and IE11 with meta tag.

### ISSUE THREAD

**Issue by atsim** [mkoryak/floatThead#214]
Hey,

I added in the meta tag and the header is jumping around everywhere when I scroll. It's behaving the same as when there isn't the meta tag. Is this a known issue, and is there any way to fix it? Otherwise, it's working great in ff, chrome, and ie8. This is the example I was testing on: http://jsbin.com/kojapucibu/1/edit

**Comment by mkoryak** [comment]
try this
http://jsbin.com/carapovibi/2/edit

**Comment by atsim** [comment]
It jumps around as if the meta tag wasn't included. (IE11)

**Comment by atsim** [comment]
It does stick to the top but it's a little delayed. If you scroll fast enough, it'll constantly jump up and down around 3 pixel's height

**Comment by mkoryak** [comment]
this is because i spelled the option name wrong, try this:

http://jsbin.com/wejicosomi/3/edit

**Comment by mkoryak** [comment]
it jump around like that because IE sucks, it cant keep up.

**Comment by atsim** [comment]
Yea, IE is pretty bad. It's working perfectly now, thanks!

**Comment by mkoryak** [comment]
good luck with IE
