### ISSUE TITLE
how to fix bug thead?

### ISSUE THREAD

**Issue by tanobi92** [mkoryak/floatThead#215]
Hi @mkoryak ! You try go to link:
http://mkoryak.github.io/floatThead/examples/hidden-columns/
and:
I use middle mouse/ scroll wheel for scroll table, I feel thead of table which it convulse, it not smoothness like I use mouse move scrollbar of browser (I'm not sure the word used to exact, I not good English :) ).
How to fix it? Please, help me! Thank you very much!

**Comment by mkoryak** [comment]
useAbsolutePositioning:false

**Comment by tanobi92** [comment]
Hi @mkoryak!  I also use useAbsolutePositioning:false, but It have a problem. I hover menu:
<a href="http://imgur.com/DPbEMIJ"><img src="http://i.imgur.com/DPbEMIJ.png" title="source: imgur.com" /></a>
Help me! Thank you!

**Comment by mkoryak** [comment]
Your menu div needs to have a z index that is higher. Try setting it to 10000000

**Comment by tanobi92** [comment]
Thank you for answering, @mkoryak ! I fixed!

**Comment by tanobi92** [comment]
@mkoryak , How to fix position of Thead. I want to fix plan in red rectangle, Thead(screen rectangle) don't change position, when I move scrollbar.
<a href="http://imgur.com/lMWmzZB"><img src="http://i.imgur.com/lMWmzZB.png" title="source: imgur.com" /></a>

**Comment by mkoryak** [comment]
sorry, if I cant see your code, I cant help you. jsfiddle please.

**Comment by tanobi92** [comment]
Hi @mkoryak ! My Demo: 
http://jsfiddle.net/TaNoBi/t4jvqpvc/9/
