### ISSUE TITLE
Overflow Scrolling doesn't work

### ISSUE THREAD

**Issue by sillestadtkowsky** [mkoryak/floatThead#216]
Hi,
Here is a link to <a href='https://jsfiddle.net/6akdvnzt/7/' target='_blank'>jsfiddle</a>. 
Why not not work my example [Overflow Scrolling]?

I hope you can help me! :)

Many thanks!!!

**Comment by mkoryak** [comment]
because you dont have any overflow. add the overflow the scrolling container:

https://jsfiddle.net/6akdvnzt/8/

**Comment by sillestadtkowsky** [comment]
Thanks!!
Great Job!
