### ISSUE TITLE
Thead cutting off on mobile phone

### ISSUE THREAD

**Issue by shadyhh** [mkoryak/floatThead#217]
Hello,

I have a responsive Bootstrap table. It has horizontal scrolling. floatThead does it's job perfectly on the desktop. When I resize my browser window to a smaller size and use the horizontal scrollbar, I don't get any problems. However, when i view the table on a mobile phone, the thead get's cut off and only displays the th's which are visible when the table is loaded.

![image](https://cloud.githubusercontent.com/assets/11984468/8225377/2153409c-1594-11e5-83c0-40d6d6c13b43.png)
Desktop view

![image](https://cloud.githubusercontent.com/assets/11984468/8225388/4c5de3fa-1594-11e5-9887-47ce63926dd1.png)
Desktop view with smaller screen, scrolled to the right

![image](https://cloud.githubusercontent.com/assets/11984468/8225455/11ced298-1595-11e5-8a90-07b0865d2a4c.png)
Mobile view

![image](https://cloud.githubusercontent.com/assets/11984468/8225464/2b8c5dea-1595-11e5-8722-3249355845a1.png)
Mobile view, scrolled to the right

Thanks :+1:

**Comment by mkoryak** [comment]
mobile safari is mostly not supported. I suggest checking user agent and turning off this plugin for safari.

**Comment by mkoryak** [comment]
this plugin is pretty cpu intensive. it doesn't work that great on phones and I don't believe that it should be used on such small screens anyway.  Furthermore, debugging (mobile) safari is a pain in the ass. Pull requests are welcome :)

**Comment by mkoryak** [comment]
here is the issue in safari that exhibited same behavior - https://github.com/mkoryak/floatThead/issues/108

I fixed it a few versions ago. so make sure you are using the latest.  this was not a mobile safari bug though, so it perhaps is not fixed there. You cant pay me to debug mobile phones :P
