### ISSUE TITLE
Combining floatThread with Zurb

### ISSUE THREAD

**Issue by jch02140** [mkoryak/floatThead#219]
I found this Zurb responsive table with a sticky column modification on Zurb foundation framework.

http://zurb.com/playground/responsive-tables

Would it be possible to combine with floatThread so a single table can have both sticky column and table header?

Best Regards

**Comment by mkoryak** [comment]
probably not, for 2 reasons:
- This plugin doesn't work well on mobile safari (so I've been told)
- I looked at their code, and they clone the table, and don't cache selectors - which means that my plugin will be upset when the table it ran on no longer exists.

see https://github.com/zurb/responsive-tables/blob/master/responsive-tables.js
