### ISSUE TITLE
Header and Body alignment problem

### ISSUE THREAD

**Issue by warnes** [mkoryak/floatThead#220]
Using the latest jQuery and floatHead, the header and body columns are not aligning properly for my table. 

I've simplified the code to a minimal example at: http://jsfiddle.net/warnes/mhmfqwgv/. (The actual alignment issue is more extreme on my page than this example.)

O/S:  Mac OS X 10.10.3
Browsers:  
- Chrome Version 43.0.2357.130 (64-bit)
- Safari Version 8.0.6 (10600.6.3)
- Firefox 38.0.5

**Comment by mkoryak** [comment]
you have more cells in your tbody than in thead. 

https://jsfiddle.net/mhmfqwgv/3/embedded/result/

**Comment by mkoryak** [comment]
but there is a bug when the width of the page is smaller than the table like in the edit view.

**Comment by mkoryak** [comment]
fixed on master
http://jsfiddle.net/mhmfqwgv/5/

**Comment by warnes** [comment]
Thanks, it is much better!  

Sadly, there still has a slight offset of a few pixels ... visible when I increase the zoom.

**Comment by mkoryak** [comment]
there is an offset on the latest fiddle i posted? I dont see one in chrome/mac

**Comment by warnes** [comment]
Yes, there is still a small offset in the fiddle you posted.

I'm also running Chrome on Mac OS X.  Here's a screenshot of the fiddle:

![image](https://cloud.githubusercontent.com/assets/6144863/8491638/fd9f166c-210a-11e5-993c-e1690d783527.png)

You'll probably need to zoom in on the image to see the offset, since its only a pixel or two in this example, but is larger in my application.  

Still, it is *much better* than it was.   

Thanks again!

**Comment by mkoryak** [comment]
weird. I dont see that happening on that fiddle on osx 10.9 and chrome 43. Your version of chrome looks very different than mine - what is it?

can you copy the generated html of that fiddle where you see the gap, and paste it into a new fiddle so I can try to reproduce?
