### ISSUE TITLE
Header stops floating on fullscreen mode using the HTML5 fullscreen api

### ISSUE THREAD

**Issue by deanpeterson** [mkoryak/floatThead#221]
Everything works fine until I make the table fullscreen using the HTML5 fullscreen api.  The header stops floating.  When I exit fullscreen mode it begins to work again.

chrome: Version 43.0.2357.124 m

**Comment by mkoryak** [comment]
jsfiddle please

**Comment by mkoryak** [comment]
cannot reproduce your issue, see: http://mkoryak.github.io/floatThead/tests/issue-221/
feel free to reopen when you have a jsfiddle
