### ISSUE TITLE
FloatHeader works only secod scroll first time it is not working in IE

### ISSUE THREAD

**Issue by gnunna** [mkoryak/floatThead#224]
FloatHeader works only secod scroll first time it is not working in IE

**Comment by mkoryak** [comment]
you would like me to do something about this?

**Comment by gnunna** [comment]
Is there a fix for this ?

Thanks,
Gopal Nunna

**Comment by mkoryak** [comment]
First you must state the problem in a way that I can understand it. Read the contributing.md

**Comment by gnunna** [comment]
Sorry for brief description, i am using Jquery float thread plugin to float my table header. when i scroll the page dow the header is not floating the first time, once i scroll back to top and scroll down again i do see floating header. How do i fix this, please help.

Thanks,
Gopal Nunna

**Comment by mkoryak** [comment]
please read contributing.md, follow instructions about providing me with enough info to help you

**Comment by mkoryak** [comment]
https://github.com/mkoryak/floatThead/blob/master/CONTRIBUTING.md

**Comment by mkoryak** [comment]
Reopen this once you have a jsfiddle
