### ISSUE TITLE
Print preview in firefox

### ISSUE THREAD

**Issue by Soullighter** [mkoryak/floatThead#226]
I have problem printing table with fixed thead. Problem appears in width of table, causing 20% of table to overflow paper and be hidden. Another problem is in Firefox, thead is not showing on all pages like it should be, because its absolute positioning. So is there a way to add double text value, for example in thead > tr.size-row > th.floatThead-col ? Because that thead is repeating on all pages, and because there is no text in <th> result is blank thead

**Comment by mkoryak** [comment]
having trouble following the problem(s?) you are having. take a look at this for print style help:
https://github.com/mkoryak/floatThead/issues/192

if you have other issues, please create a jsfiddle and see contriburing.md for guidelines on opening issues

**Comment by mkoryak** [comment]
no response, closing
