### ISSUE TITLE
Keyboard focus order wrong

### ISSUE THREAD

**Issue by robinpoort** [mkoryak/floatThead#230]
Awesome plugin you've created here!

While I was implementing it I stumbled upon the following issue. When you're using your keyboard to navigate the page and the table has got any 'focusable elements' (links, checkboxes etc.) in them it will focus on 'focusable elements' in the `<tbody>` first. After that it brings focus to elements in the `<thead>`. 

I'm using this plugin for a backend system that is using tables to list items. In this system you can sort columns by clicking on the different table headers. And you can click on the first table cell of each row in the `<tbody>` to open the specific item.

I created a JSFiddle to demonstrate what I'm talking about: http://jsfiddle.net/fqo2k6zz/1/
Just tab through it to see what I mean.

I think there's a very easy way to fix this: instead of `appending` the `floatThead-container` to the table you could just `prepend` it. In that case the keyboard navigation order will be good. Because this container has `aria-hidden` it will also never be a problem for screenreaders.

**Comment by mkoryak** [comment]
thanks for the fiddle! Want to create a PR for this too ;) ?

**Comment by robinpoort** [comment]
I'm on holiday for two weeks now. I can take a look afterwards :+1:

**Comment by mkoryak** [comment]
this is now on master
