### ISSUE TITLE
FloatThead with jQuery custom content scroller

### ISSUE THREAD

**Issue by sentbyravens** [mkoryak/floatThead#231]
Hi! 
We don't know how to make work well together floatThead with jQuery custom content scroller (site: http://manos.malihu.gr/jquery-custom-content-scroller/ 
GitHub: https://github.com/malihu/malihu-custom-scrollbar-plugin). That plugin always sets content wrapper scrollTop/scrollLeft  to 0. So your plugin can't initiallize properly with that options: scrollTop: 85.

Теперь понятным языком: нужна плавная прокрутка, и нужна прилипающая шапка таблицы. Причем также должна учитываться шапка сайта, которая как раз и составляет 85 пикселей. В обычной ситуации хватило бы вписать в floatThead scrollTop: 85. Но дело в том, что 
плагин того товарища делает scrollTop и scrollLeft постоянно равными нулю, а само body всегда равно 100%, что и делает невозможным инициализацию дефолтной прокрутки, на которую рассчитан floatThead (надеюсь, объяснили правильно).

**Comment by mkoryak** [comment]
sorry, cant respond in russian, but 2 things:

can you use this: http://mkoryak.github.io/floatThead/examples/perfect-scrollbar/ ?

if not, please create a jsfiddle and I will try to help you get that one working

**Comment by sentbyravens** [comment]
I can't use a "Perfect Scrollbar" because I need smooth scrolling.
JSFiddle: http://jsfiddle.net/4kojLhah/

**Comment by mkoryak** [comment]
Does not look like I can support that lib. it does not set `.scrollTop(x)` instead it uses css `top:x`, it also does not trigger and scroll events on the element being scrolled.  

My plugin relies on scrollTop and scroll events. Making these 2 things work together would require writing another plugin to bridge the gap :P

**Comment by sentbyravens** [comment]
How did we solve that:

 var OurTable = $('.table');
    
    //Если мы в личном кабинете и у нас есть таблица с данными
    if (OurTable .length != 0){
        OurTable .floatThead({
            useAbsolutePositioning: false,
            scrollTop: 85
        });
    }


        $('body').mCustomScrollbar({
            theme:"minimal-dark",
            callbacks : {
                onScroll: function(){
                    ScrollerTop = this.mcs.top;
                 },
                whileScrolling: function(){

                    if (OurTable .length != 0){
                        if (this.mcs.top <= -220){
                            $('.floatThead-table').css('marginTop', 85);
                        }else{
                            $('.floatThead-table').css('marginTop', 0);
                        }
                        
                        OurTable .floatThead('reflow');
                    }

                }
            }
May be now you will create a patch ;)

**Comment by mkoryak** [comment]
this does look like code I can put in the main plugin, but I can add a page to the docs about it if you tell me what `220` is?

**Comment by sentbyravens** [comment]
It is like 85 in JSFiddle. Just in our desidn we don't need initialize that right after nav bar.

**Comment by mkoryak** [comment]
glad you found a hack to solve your problem

**Comment by michaelmmcrae1** [comment]
@mkoryak - did you end up adding this into the plugin? Just curious. I'm having issues with mCustomScrollbar and your plugin playing nicely (particularly when there's a POST-back in my web forms app when the infinite-scroll request is made).

**Comment by mkoryak** [comment]
sorry, i think that was a typo, i meant 'cant put into main plugin'. 

have you tried trigger `reflow` on the table whenever weird things happen?

**Comment by michaelmmcrae1** [comment]
First off - thanks for your time (and plugin).

For some context. Here's an image of the "weird" thing that happens:

![image](https://cloud.githubusercontent.com/assets/2359146/15374358/8d9594c0-1d0f-11e6-95d3-cd434261a199.png)

Occassionally, (can't figure out the consistent cause) when the POST-back is made, and the page refreshes - the table header is slightly off - with some weird spacing as you can see in the photo. Normally it looks like this:
![image](https://cloud.githubusercontent.com/assets/2359146/15374385/c03588b8-1d0f-11e6-9159-e1f4b537f1e2.png)

I can confirm that every time the page refreshes it calls this code:
![image](https://cloud.githubusercontent.com/assets/2359146/15374452/117a974a-1d10-11e6-884f-690537c7f5c2.png)

(I see that console.log each time) You mention using the `reflow` call. I tried doing that by calling it immediately after I call floatThead() every time, but that didn't seem to fix it. Maybe I'm doing it wrong.

I've read your docs but I'm not positive - how would you suggest I go about triggering `reflow`/checking when weird things happen?

**Comment by mkoryak** [comment]
what you should be doing is that every time more rows are inserted into the table, you should do the reflow: `$table.trigger('reflow')`

if that doesnt work try doing it within a `setTimeout` of 0ms

**Comment by michaelmmcrae1** [comment]
By placing the `$table.trigger('reflow')` after `$table.floatThead()`, both called on page load (which happens after rows are added), it seems to resolve the slight layout issue.

It's a partial page reload (from a POST-back) that causes more rows to be loaded up into the table.

But there's another odd issue I've bumped into: If the user is scrolling within the table while the page is reloading, the header simply disappears.
![image](https://cloud.githubusercontent.com/assets/2359146/15375465/d5a0f8cc-1d14-11e6-9506-79643c06bf13.png)

The even more odd thing is that simply by scrolling the browser page (up or down) in the slightest, it comes back. 

I tried hooking into the "floatThead" event to check when this happens, in order to recall-`reflow` (in above image), but it doesn't help since it doesn't hit this event when the header disappears. Any thoughts on this one?

Much appreciated.

**Comment by mkoryak** [comment]
This one I have no idea about, if you can put it on jsfiddle I can probably find a fix, if you do, please create a new issue.

**Comment by michaelmmcrae1** [comment]
Just wanted to follow up.

The odd behavior I described was being caused by the fact that my table was inside of a smaller, overflowing div, yet I was not initializing `floatThead` with

`scrollContainer: function($table) { return $table.closest('.wrapper'); }` -- or similar for your needs -- as I should have been.
