### ISSUE TITLE
Fixed Positioning Floating Header to the Table, Then the Window

### ISSUE THREAD

**Issue by niemeier23** [mkoryak/floatThead#233]
Greetings.

I work for a company which exclusively uses IE (currently v.11), so I'm developing for that browser specifically.

For simplicity's sake, I'll call <b>table1</b> the original table ($table).
I'll call the cloned/duplicated/copied thead table <b>table2</b>  (contains the thead content after being initialized).

I've set the useAbsolutePositioning property to false.  So, I'm relying on fixed positioning.

Is there any way to dynamically switch between fixing table2 to the top of table1 and then fixing table2 to the top of the window?

It seems in IE 11 that as table2 has to adjust to being a variable distance from the top of the window (I mean, the initial scrolling until the top of the window meets the top of the table), table2 noticeably shifts/skips/jumps until it has a top:0px; style.

Is there any way to switch between the two points of reference (table1 and the window) for fixed positioning so that IE doesn't have to keep (noticeably) changing the top position style of table2?

I hope I've worded that adequately well.
Here's a fiddle: https://jsfiddle.net/p6SRV/106/
Thanks for your help.

**Comment by niemeier23** [comment]
The frustrating thing is that Chrome doesn't jump/skip/shift with this configuration.  It's just IE that handles it poorly.  :/

**Comment by mkoryak** [comment]
This was a big problem in IE8, but I didnt think it was a big deal in 11.
see: https://github.com/mkoryak/floatThead/blob/master/jquery.floatThead.js#L254

might be able to change that to true and see if helps you, then i can make a change to expose it

**Comment by niemeier23** [comment]
In my opinion, the minor lag isn't a big deal.
But, I have a customer who really would like the thead stuck to the table, and then stuck to the top of the window, and to scroll with the rest of the page's content instead of appearing to lag a split second behind each scroll.

Here's a fiddle with both the jquery.floatThead.js and jquery.floatThead._.js files included in the HTML section in a <script> tag, with that line changed like you had suggested (line 262).
https://jsfiddle.net/p6SRV/109/

There's definitely a handful of other things that rely on that, which broke.

**Comment by niemeier23** [comment]
Oops.   I guess I can't use html tags.

https://jsfiddle.net/p6SRV/109/

I changed the line (262) that you were suggesting.

**Comment by mkoryak** [comment]
there is currently a bug where padding on the table or scroll container makes fixed positioning not work properly. your fiddle seems to have this problem for me on chrome, and probably ie11. if you can get around it via css then you can do this:

https://jsfiddle.net/p6SRV/111/

does that look better in ie11? if it doesnt actually work how you want it, then you can try listening to the floated event and destroy the table and reinit it with the positioning you require:

(didnt actually run this code)
```js
$table.on("floatThead", function(e, isFloated, $floatContainer){
    if(isFloated){
        $(this).floatThead("destroy").floatThead({....}).trigger("reflow");
    } else {
        $(this).floatThead("destroy").floatThead({....}).trigger("reflow");
    }
});
```

**Comment by niemeier23** [comment]
I did a bit of IE researching and found that by unchecking IE's "Use smooth scrolling" setting, this issue no longer exists.  You can do this by clicking the settings cog/gear -> Internet Options -> Advanced (tab) -> Browsing  -> "Use smooth scrolling" (uncheck).

I did remove the ieVersion <= 9 condition from this line.
```Javascript
var absoluteToFixedOnScroll = {ieVersion <= 9 &&} !locked && useAbsolutePositioning;
```
And I initialized the floatThead like this:
```Javascript
$table.floatThead({
	useAbsolutePositioning: false
});
```
I think this is how I'm going to move forward with this project.

Thanks for your help!

**Comment by mkoryak** [comment]
sounds good, ill make that be an option you can set for the next version

**Comment by mkoryak** [comment]
wait, if you init with `useAbsolutePositioning: false` then `absoluteToFixedOnScroll` ends up as false, so maybe you only need to do the `"Use smooth scrolling" (uncheck)` part?

**Comment by niemeier23** [comment]
Perhaps.  I didn't test it with useAbsolutePositioning: true, so I'm not sure if it's still an issue there.

**Comment by dallaslopez** [comment]
Not to bring back up this sore subject, but this seems to happen on Edge, now, too. However, I don't really see and option to uncheck smoothing.

**Comment by mkoryak** [comment]
there is nothing I can do about this as far as I can tell. Does editing the source and changing `absoluteToFixedOnScroll` to be always true help with anything?

**Comment by dallaslopez** [comment]
No. That does not help. I've even attempted to change the setting in your code to:
`if (pos != null && (oldTop != pos.top || oldLeft != pos.left)) {              
                if (ieVersion === 8 || ieVersion === 9 || ieVersion === 10 || ieVersion === 11 || /Edge\/\d./i.test(navigator.userAgent)) {
              $floatContainer.css({
                top: pos.top,
                left: pos.left
              });
            } else {              
              var transform = 'translateX(' + pos.left + 'px) translateY(' + pos.top + 'px)';
              $floatContainer.css({
                '-webkit-transform' : transform,
                '-moz-transform'    : transform,
                '-ms-transform'     : transform,
                '-o-transform'      : transform,
                'transform'         : transform,
                'top': 0,
                'left': 0
              });
            }`


if you watch edge as you scroll, it's very 'notchy' (forgive me if I'm not using the right term). It will jump several numbers at once in the `pos.top`.

**Comment by mkoryak** [comment]
sounds like this is a bug i cannot fix, it has to do with the speed of the
javascript engine / cpu

**Comment by dallaslopez** [comment]
What's ironic is that it's not happening in Chrome or Firefox.

**Comment by mkoryak** [comment]
Why is that ironic? Things have never worked right in ie
