### ISSUE TITLE
Latest Release breaks binding

### ISSUE THREAD

**Issue by edorsey** [mkoryak/floatThead#234]
We use Backbone to bind events to links in the Table Headers and the latest releases completely breaks our binding.

**Comment by mkoryak** [comment]
I dont use backbone, so you are going to have to tell me why it breaks it

**Comment by mkoryak** [comment]
nothing in here jumps out at me as a cause for that:
https://github.com/mkoryak/floatThead/compare/v1.2.12...master

**Comment by edorsey** [comment]
I just noticed that links in headers never worked with floatThead when he page is scrolled down. 

With the latest version, it looks like you are no longer only showing the duplicated header when the page is scrolled down, but all the time. This is what caused it. Duplicating the original elements like that is always going to destroy any events attached to the originals I believe.

**Comment by mkoryak** [comment]
I agree, which is why I don't duplicate any elements, I move them. Are you sure you are using my plugin?

**Comment by mkoryak** [comment]
perhaps your events are bound via delegation? When I move your thead, the selectors to the elements change, so your delegation selector might become busted. The fix is to make the selectors a bit more generic.

**Comment by edorsey** [comment]
Yeah, backbone binds via delegation.

We had it scoped down to the table, which worked when you were at the top of the table previously, but if I remove that specificity it works fine. Thanks for the help!

**Comment by mkoryak** [comment]
you're welcome. You are lucky I dont work at your competitor anymore or you might still have a busted table header ;)
