### ISSUE TITLE
Add floatThead to the jsDelivr CDN

### ISSUE THREAD

**Issue by PhilippWendler** [mkoryak/floatThead#236]
We already use the jsDelivr CDN for all our JavaScript libraries, and we would like to use your great plugin, preferably without adding another CDN.

Could you please consider adding floatThead to jsDelivr? The [guidelines for submitting new projects](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md) look as if this is not a big effort, and I think jsDelivr is a popular CDN such that other users would benefit from this as well.

**Comment by mkoryak** [comment]
Why cant you add it?

**Comment by PhilippWendler** [comment]
I could but I thought you might prefer to add it yourself. If you wish, I could propose inclusion.

**Comment by mkoryak** [comment]
Please do, ill add it to the docs once it on there.

**Comment by PhilippWendler** [comment]
It is now available on Jsdelivr.
