### ISSUE TITLE
Header overlap row when scrolling up

### ISSUE THREAD

**Issue by mikeerickson** [mkoryak/floatThead#237]
I have an issue which I am not sure how to fix.   If you have a look at this screenshot, you can see the issue.   In short, when I am scrolling down and it is time for the header to be fixed, the rows continue to scroll and you will see the issue.

![header](https://cloud.githubusercontent.com/assets/183153/9507197/53600220-4c01-11e5-915c-e66de13c0372.png)

**Comment by mikeerickson** [comment]
I am curious if I need to apply some other markup on my page? 

I have a typical table layout, nothing fancy at all.


<div id="container">
  <table>
    <thead>
      <th>header</th>
    </thead>
    <tbody>
      <tr><td>value</td></tr>
    </tbody>
  </table>
</div>

**Comment by mkoryak** [comment]
Add a background color to the thead, see docs
