### ISSUE TITLE
Scroll to row

### ISSUE THREAD

**Issue by puicheng** [mkoryak/floatThead#240]
We have a requirement to refresh the page when click on a row. Is there a scroll to row function when the page is loaded? Thanks.

**Comment by mkoryak** [comment]
This plugin doesn't provide one.  You should get the "scrolling to row" working first, and then apply the plugin

**Comment by mkoryak** [comment]
reopen if you have any more questions

**Comment by puicheng** [comment]
Thanks. Resolved by obtaining the container of the table, finding the top position of the table then do a $('.main-tble-container').animate({scrollTop: rowpos}, 100 );
