### ISSUE TITLE
Doesn't work in IE 9 when there is a row with a colspan

### ISSUE THREAD

**Issue by homer2** [mkoryak/floatThead#241]
I have a table with multiple `tbody` sections. The first row of each section is used as a header row so it spans the entire table. It looks like `floatThead` doesn't know what to do when the header is visible. As I was writing up this issue I thought of a workaround that seems to get the job done:

1) Hide header rows
2) apply `floatThead`
3) show header rows

I have a [Fiddle](http://jsfiddle.net/6jnnmkea/3/) that can be used to reproduce the problem.

**Comment by mkoryak** [comment]
I think you missed the point the `getSizingRow` method. it needs to return a row where no colspans exist. it can be a row that is hidden from the user. currently your code returns `<td colspan="13">section 1</td>`, it also looks like its copied straight out of the docs, so the selector doesnt apply to your table.

**Comment by homer2** [comment]
Opps, I've fixed the selector in `getSizingRow` in the Fiddle now, but the problem remains. I think I got the cause wrong. I think it might be the `rowspan` and `colspan` in the `THEAD` that is causing the problem.

**Comment by mkoryak** [comment]
your sizingRow function is still wrong. it should return td or th elements. I fixed it, and it seems to now work for me in IE9:

http://jsfiddle.net/6jnnmkea/4/

Let me know if that works for you, or if something else is busted
