### ISSUE TITLE
Multiple tables within a scrollable div

### ISSUE THREAD

**Issue by eceyhan** [mkoryak/floatThead#242]
I have a scroll-able div and in that div, there are multiple table elements. As the user scrolls, the corresponding table header needs to stay fixed.

Here is the to the jsfiddler : http://jsfiddle.net/eceyhan/f0rjzqL9/

Any help is greatly appreciated.

Thanks..

**Comment by mkoryak** [comment]
it helps if you include jquery and this plugin as deps in the jsfiddle, otherwise it doesnt work very well.

how about something like this:

http://jsfiddle.net/f0rjzqL9/2/

**Comment by eceyhan** [comment]
Thank you for your response. 

It works great but I see table borders are displayed beneath the scrollable div. Please see the attached file. 
![jsfiddle net_f0rjzql9_2_](https://cloud.githubusercontent.com/assets/14202886/9770357/6aaadcc6-56f5-11e5-9af3-ce04ce19fb97.png)

**Comment by mkoryak** [comment]
it happens because of fixed positioning. I dont have time to play around with this right now, but I think this can be fixed with css.

**Comment by mkoryak** [comment]
There was a bug with absolute positioning that I just fixed, see updated fiddle:
http://jsfiddle.net/f0rjzqL9/3/

note that this fix only exists on master at this time.
