### ISSUE TITLE
using search in chrome makes the header and body mis-align

### ISSUE THREAD

**Issue by Progdom** [mkoryak/floatThead#243]
![image](https://cloud.githubusercontent.com/assets/2650030/9776535/494b9304-570e-11e5-9e32-4a2b2d8c5e7b.png)

when using search to search a column if the table is scrolled to the right and the column containing the value is far to the left then only the header is moved for searching while the body stays where it is.
(This is the CTRL + F command in chrome)

**Comment by mkoryak** [comment]
not for me on osx, what OS are you on and what version of chrome?

**Comment by Progdom** [comment]
I'm on windows 7  enterprise and my version of Chrome is Version 45.0.2454.85

**Comment by Progdom** [comment]
Steps to reproduce on demo site.
1. scroll the demo box all the way to the right.
2. CTRL + F "click me"

At this point you should see that the header moves to the far left and highlights the click me text, but the body of the table stays where it was.

**Comment by mkoryak** [comment]
It works fine on OSX, they both scroll. I suspect that this will not be a bug that ill be able to fix, since there is probably no event that tells me that search happened, its all native browser/OS stuff that I have no access to.

**Comment by mkoryak** [comment]
I was able to reproduce on a windows VM. As I suspected, searching changes the scrollLeft of the float container div to 0, and I have no way to know about this short of setting a timeout to check it, which I will not do. You can do it though, if this bug is a deal breaker for you.

**Comment by mkoryak** [comment]
something like this:
```js
var $cont = $('table.demo0').closest('.floatThead-container');
var $wrap = $('table.demo0').closest('.wrapper');
setInterval(function(){ 
  if($cont.scrollLeft() == 0 && $wrap.scrollLeft() != 0){
    $wrap.scrollLeft($cont.scrollLeft());
  }
}, 100);
```

**Comment by Progdom** [comment]
I think there's a method called scrollintoview that it uses which is cross browser.

**Comment by mkoryak** [comment]
if it calls that method on the element, it doesnt help me, since I have no way to know if that method was called, and on which element
