### ISSUE TITLE
enableAria:true causes javascript exception when using Colgroup

### ISSUE THREAD

**Issue by zuverza** [mkoryak/floatThead#246]
The library crashes when enableAria is true and there is a colgroup element.

Error:
Uncaught TypeError: Cannot read property 'eq' of undefined  jquery.floatThead.js:407 

If the <colgroup> element is removed OR enableAria is set to false, it works fine.

Fiddle: https://jsfiddle.net/tm03s8y4/

**Comment by mkoryak** [comment]
will fix

**Comment by mkoryak** [comment]
on master
