### ISSUE TITLE
Table top border hidden by floatThead div in IE11

### ISSUE THREAD

**Issue by mwilsonray** [mkoryak/floatThead#248]
We have an ASP.NET web page containing 4 GridViews. The floatThead works great on all 4 Gridivews, but on last 2 GridViews the floatThead div is hiding the top border of the table. This is happening before scrolling to a point where the floating headers are displayed and after scrolling back to the same point.

Using the F12 developer tools, I can modify the top of the floatThead div to -1px and it no longer hides the top border. I'm unable to create a simple example that exhibits the issue. Any suggestions?

**Comment by mkoryak** [comment]
try setting `useAbsolutePositioning` to true and false and see if that helps. That is the best I can do without seeing any code
