### ISSUE TITLE
Transpose Table

### ISSUE THREAD

**Issue by bennettl** [mkoryak/floatThead#249]
Can you please make this library work with a transpose table?  THANK YOU!!!
![screen shot 2015-09-18 at 11 52 32 am](https://cloud.githubusercontent.com/assets/1672224/9968176/d14ef8a6-5dfb-11e5-925a-bdcbac673625.png)

**Comment by mkoryak** [comment]
a link to "transpose table" would help

**Comment by bennettl** [comment]
Click on "Construct", then "transpose". Now this seems kind of tricky to do so it'll be a challenge =)

https://vm-dev-030.misd.isi.edu/Chaise-Detail/detail.html#c=6&t=target&id=110

**Comment by mkoryak** [comment]
That link is on a university intranet, it cannot be accessed from outside. 
Is transpose table a plugin that is on github?

**Comment by bennettl** [comment]
Strange. I can access it from my home. Basically for the transpose table, the header is on the left (dark gray) and the user scrolls from left to right. So for every row, the first cell is the header

'
<tbody>
<tr>
<th>header1</th>
<td>cell1</td>
<td>cell2</td>
</tr>
<tr>
<th>heade2r</th>
<td>cell3</td>
<td>cell4</td>
</tr>
</tbody>
'

**Comment by mkoryak** [comment]
Ok now I understand. That is an entirely different problem than the one this plugin solves in terms of implementation. It would be easier to write a new plugin than to modify this one. 

That is why I will not support that use case
