### ISSUE TITLE
floatThead and Wordpress

### ISSUE THREAD

**Issue by lucein1774** [mkoryak/floatThead#250]
Hello,
I can get a stand alone html page working with floatThead. The table header locks to the top of the screen just as I want.

But inserting this into Wordpress I can not get it to work. 

Jquery is already loading and floatThead.js is loading with the script function on the page with no errors.  But the it just isnt working.

Any suggestions?

I look forward t your reply.

**Comment by mkoryak** [comment]
nope, no suggestions. I need to look at some example of something not working to have any of those.

**Comment by lucein1774** [comment]
Ok, totally understand.  I created a fiddle that is based on my local HTML test doc that is working fine, but when i try to insert into to WP nothing works.
https://jsfiddle.net/lucein/5kw5v39v/

Below is the link to my dev site with the page that I am trying to get it working on.
http://dev.afscenter.org/memory-care-services/moderate-to-late-stage-services/

I am inserting the floatThead.js and an external fixedHeader.js that holds the JS function via the functions.php. Both of which get inserted into the head of the page. 

Functions.php
<pre>
function my_floatThead_scripts() {
	wp_register_script( 'bootlint-script', 'https://cdnjs.cloudflare.com/ajax/libs/floatthead/1.2.13/jquery.floatThead.js', array( 'jquery' ), '1.2.0', true ); // -- From an External URL
    wp_register_script('my-floatThead-custom', get_stylesheet_directory_uri() . '/js/afs_fixedHeader.js', false, null, true);
if(is_page('moderate-to-late-stage-services')){
	wp_enqueue_script('bootlint-script'); 
    wp_enqueue_script('my-floatThead-custom'); 
}}
</pre>
Here is the script in the afs_fixedHeader.js
<pre>
( function( ) {
		$('table.afs_pstable').floatThead({
			useAbsolutePositioning: true
			// absolutePositioning is better for
			// highly dynamic sites
			// (which this is not)
		});
		$('table.afs_pstable').floatThead();
		$('table.afs_pstable').floatThead('reflow');
	});
</pre>

I have also read that WP loads JQuery in "No Conflict" mode and it is suggested that "$" alias doesn't work.  So it is recommended that the function is wrapped like this:
<pre>
(function($) {
	$(document).ready(function () {
		$('table.afs_pstable').floatThead({
			useAbsolutePositioning: true
			// absolutePositioning is better for
			// highly dynamic sites
			// (which this is not)
		});
		$('table.afs_pstable').floatThead();
		$('table.afs_pstable').floatThead('reflow');
	});
})(jQuery);
</pre>
Which I have tried as well, both ways load the page without any errors but I am scratching my head to why it wont work. 
Any help would be greatly appreciated.

**Comment by mkoryak** [comment]
your table html looks very malformed to me:
```html
<table class="afs_pstable" border=".5" cellspacing="0" cellpadding="3">
<tbody>
<col class="col1"/>
<col class="col2_mls" align="center"/>
<col class="col3_es" align="center"/>
<thead>
<tr>
<td id="psb">Program/Service Benefits</td>
<td id="mls"> Moderate-Late Stage</td>
<td id="es">Early Stage</td>
</tr>
</thead>
</tbody>
<tbody>
<tr>
<td id="td_col1_td_head">Nursing</td>
<td id="td_col2"></td>
<td id="td_col3"></td>
</tr>
<tr>
<td id="td_col1">Basic First Aid</td>
<td id="td_col2">●</td>
<td id="td_col3">●</td>
</tr>
...
```

the unclosed `tbody` tag at the top probably causes the plugin to break.  `col` elements are only valid within a `colgroup` tag but id advise you to remove those because you will get a better result with this plugin if you do not use them. 

I think what happens is that brower parses your html as best it can, builds something that floatThead cant use.

**Comment by lucein1774** [comment]
Thank you for the help!  I was able to get it working now.
