### ISSUE TITLE
Column headings not aligned with data 

### ISSUE THREAD

**Issue by mwilsonray** [mkoryak/floatThead#252]
We have a table with the column widths defined as percentage. If the user has their browser width set small, the column headings do not line up with the data. If they widen the browser and refresh the page, the heading are aligned. This is not a resizing issue; it happens when the page first loads.

https://jsfiddle.net/kyhjb3da/

Narrow:
![narrow_browser](https://cloud.githubusercontent.com/assets/14338121/10028473/57ee0fc6-6132-11e5-87b7-e2ba4bfc283e.png)

Wider:
![wider_browser](https://cloud.githubusercontent.com/assets/14338121/10028478/5ea09a1e-6132-11e5-8ebf-ca370b8d9620.png)

**Comment by mkoryak** [comment]
did you even look at the console? it was telling you that an option you used was no longer around in 1.3.

aside from that, the first row of the tbody was what was messing it up. usually you only need a single row in the thead to establish column widths. The one in your tbody didnt do anything before the plugin ran, and afterwards it broke things. 
Things will work even better if you put the styles into css.

https://jsfiddle.net/kyhjb3da/1/
