### ISSUE TITLE
When <body> is set to position:absolute, Window Scrolling with position:absolute stops working

### ISSUE THREAD

**Issue by constancecchen** [mkoryak/floatThead#253]
Hey there! First of all, thanks so much for this really wonderful and useful plugin. I understand this is a pretty odd combination of settings, so if it's simply not doable, no worries at all.

Here's the outcomes I'm hoping for:

- `<body>` set to `position: absolute` - this allows me to customize the position of the default scrollbar
- Overflow-Y scrolling, because I have a ton of columns to show. To get this working correctly, I use window scrolling combined with the `position: "absolute"` config

Unfortunately, it seems like this particular combination of positions causes floatThead to stop working completely. Please see this JSfiddle:

https://jsfiddle.net/qgauh2sm/3/

If you comment out `position: absolute` in the CSS `body` selector, all works well. But as I mentioned, I'd really like to be able to set `position: absolute`. Setting floatThead to `position: "fixed"` does cause floatThead to start working again, but then the Overflow-Y scrolling ceases to work.

Any help or thoughts on this would be incredibly appreciated! :)

**Comment by mkoryak** [comment]
well thats certainly a strange setup. I wouldn't recommend doing it, but you must have a really good reason for this abomination :)

This isn't supported by the plugin, but the following hack works: https://jsfiddle.net/qgauh2sm/4/

**Comment by constancecchen** [comment]
Haha! It's probably not as good of a reason as it should be. I'll consider that carefully. Thank you infinitely for your time and help - sending a donation your way as appreciation! :)

**Comment by mkoryak** [comment]
Thanks for the donation!

why cant you do this? https://jsfiddle.net/qgauh2sm/5/
