### ISSUE TITLE
Scrolling a table within iframe

### ISSUE THREAD

**Issue by OraEtLabora** [mkoryak/floatThead#254]
I have a quick question.  I am trying to use your floatThead code and I can't seem to get it to work in this layout.

My application resides within an iframe.  I want to float a header for a table which is located within the iframe.  The iframe and the container code for the iframe are both on the same domain, so I am able to access the elements in the parent.

So, the situation is:

    <html>
    <body>
    ...
    <iframe>
    ...
    <table><thead>...</thead>...</table>
     ...
    </iframe>
    more stuff here (footer for page)
    </body>
    </html>

So, the window within the iframe does not scroll, but the window which contains the iframe scrolls.  Is it possible to do this?

**Comment by mkoryak** [comment]
Someone else wanted to this a while back and I think there was even a PR, but he never provided a test case where I could test his code so I closed it. Maybe you can find it and reopen it after you get it working

**Comment by OraEtLabora** [comment]
Thanks for the information.  I did find  PR #113 and #114 about the same issue.
