### ISSUE TITLE
need a callback on plugin Init

### ISSUE THREAD

**Issue by serGlazkov** [mkoryak/floatThead#255]
how can i call some function if floatThead initialize?

**Comment by mkoryak** [comment]
I'll add one today

**Comment by mkoryak** [comment]
for some values of today

**Comment by mkoryak** [comment]
whats wrong with doing this:
```js
$table.floatThead();
// hey it initialized!
```

**Comment by serGlazkov** [comment]
i try it, but DOM not be in time to initialize

**Comment by mkoryak** [comment]
do you have images in your table?

**Comment by mkoryak** [comment]
docs updated, search for `reflowed` event. you will probably need to isolate a good time to do your stuff, my hunch is that it should be done on the 2nd time this fires.
