### ISSUE TITLE
IE site example..

### ISSUE THREAD

**Issue by natocTo** [mkoryak/floatThead#256]
I try to use this library but have problem with IE..
I looked to your web example with IE and colspan but your code (page) not working in IE also.

http://mkoryak.github.io/floatThead/examples/row-groups/ (rows are wrong in IE 11)

![floatthead](https://cloud.githubusercontent.com/assets/12331181/10363875/852aa85a-6db7-11e5-9dc8-f893b6b2946b.png)

**Comment by mkoryak** [comment]
That's not good. I'll take A look at this in a few hours when I wake up

**Comment by mkoryak** [comment]
it was actually a typo in my example. Thanks for spotting it.
