### ISSUE TITLE
Documentation doesn't show markup or CSS

### ISSUE THREAD

**Issue by jgbishop** [mkoryak/floatThead#257]
None of the documentation (that I can find) lists the markup or CSS for each demo. One must open the page source and try to figure it out, or use developer tools to do the same. Explicitly showing the markup and CSS would be immensely helpful to newbies like myself.

See any of the [DataTables examples](https://datatables.net/examples/basic_init/zero_configuration.html) for ideas on how this could work in practice (they show JS, HTML, and CSS for each example).

**Comment by mkoryak** [comment]
thats kind of the point. you shouldnt need to change your table html or markup, just drop in the lib. 

ok, there are some exceptions, like the plugin expects standards compliant html and css, but you should be writing that anyway.

**Comment by mkoryak** [comment]
If dropping the plugin into your existing markup doesnt work, feel free to post an issue here and ill help you out.

**Comment by philiprenich** [comment]
Maybe I skimmed the documentation too much, but I had to create a wrapper around the table and then tell the plugin to use that wrapper. I thought I could just have table markup, run the plugin, and then have CSS to set the height/overflow on the generated class. So there is a little need to know that a wrapper is needed, etc.

**Comment by mkoryak** [comment]
Yes a wrapper is needed, it would still be needed if you didnt use this plugin. If you want to have an area on your page that will have a scrollbar in it, you create a div with overflow:auto and a width and a height, then you stick stuff in it. People commonly stick tables into such containers.

If you dont use a wrapper then the plugin will assume that you want the header floated as your scroll the page. 

I dont want to start writing documentation about how to write html and css. The idea is that you start with written html and css, and hopefully there is a table there that you want to float the header on
