### ISSUE TITLE
Table Issue position: fixed

### ISSUE THREAD

**Issue by warlockdn** [mkoryak/floatThead#258]
I am trying to make this work.

I have a one table under which I have 3 more tables. First two being simple ones and the third has a overflow-x: scroll. So when I fixed the headers for 3 tables the first two seem to work properly but the third table doesn't fix the headers. Can you please help me out may be why is the error. 

$('table#shipwiseall').floatThead({
     position: 'fixed',
     scrollContainer: function($table){
         return $table.closest("#scrolltable");
    }
});

When the third table appears the first 5 column thead appears but then all is blank. (see blank.png)

This is my code 
```
<div class="cerollTable">
 <div id="scrolltable">
  <table id="shipseawall">
   <thead>.....</thead>
  </table>
 </div>
</div>
```
.cerollTable has width: 500px and overflow-x: auto

I tried fixed, absolute and auto but no luck till now. Can you please help ?

![blank](https://cloud.githubusercontent.com/assets/3439710/10509704/417ff73c-734c-11e5-85e2-4f9271983e93.png)

**Comment by mkoryak** [comment]
1. jsfiddle demo is required for code help, i dont work with images. 
2. you said you have 3 tables, but how can you select 3 tables with `$('table#shipwiseall')` ?

**Comment by warlockdn** [comment]
http://jsfiddle.net/uor01kox/

Here. If you see, there are three table inside one master table 

vessel, latest and oil majors. 

oil major has a overflow-y auto coz the data is long. I just couldn't figure out why the row below oil major isn't fixed like all other. Can you please check. Thanks.

**Comment by mkoryak** [comment]
because you never ran the plugin on it:

http://jsfiddle.net/uor01kox/2/

**Comment by warlockdn** [comment]
Am not sure. I did add the code to it. Can you help me fix it, something I
might be missing. At the moment the thing is fixed but doesn't horizontal
scroll.

Where am I doing it wrong ?

**Comment by mkoryak** [comment]
`.ltr_vettingtable` doesnt exist in your fiddle, so that might have something to do with it. This code is a mess. any way you can clean it up a bit?

**Comment by mkoryak** [comment]
ok, i see what the problem is here. http://jsfiddle.net/uor01kox/4/
`cerollTable` provides the horizontal scroll, but not the vertical scroll. That isnt supported. a scroll container must provide both scroll directions.

**Comment by warlockdn** [comment]
I have added scrolltable as a id and calling that container doesn't work as
well.

I know but for the moment um stuck with this.

**Comment by warlockdn** [comment]
Ok but now the head doesnt stick above. ?

**Comment by mkoryak** [comment]
cerollTable provides the horizontal scroll, but not the vertical scroll. That isnt supported.

scrollContainer must be a div with BOTH horizontal and vertical overflow. What you have is a div with horizontal scrolling, but the page body supplies the vertical scrolling - this is not supported.

**Comment by warlockdn** [comment]
ok so I gave cerollTable as overflow: auto; as you asked but doesn't work still ?

**Comment by mkoryak** [comment]
sure it did, something like this:
http://jsfiddle.net/uor01kox/6/

please read the docs if you are unsure about how to configure the plugin. its all there

**Comment by mkoryak** [comment]
the scroll container must provide both vertical and horizontal scroll. in your case your whole window scrolls, so that isnt a very good option from the ux perspective.

**Comment by warlockdn** [comment]
so no solution ?

**Comment by mkoryak** [comment]
That is correct.
