### ISSUE TITLE
floatThead on centered table

### ISSUE THREAD

**Issue by MacGyver27** [mkoryak/floatThead#259]
Hello,

I have issue with using your floatthead plugin for table which is centered. I tried with obsolete align="center" or table.center{margin-left:auto;margin-right:auto;} same buggy result.

Was doing it 2 ways:
1) using position: 'absolute', It will result into this: ![issue1](http://i62.tinypic.com/24orj0m.png)

2) using position: 'fixed', this makes header to be re-rendered - for the short time 2 headers can be seen, one over other:
![issue2](http://i62.tinypic.com/2zefi1w.png)

    <div class="table-wrapper">
    	<div class="table-responsive">
    		<table float-thead="floatTheadOptions" class="center table table-bordered table-striped"
    			   style="white-space: nowrap; width: auto;">
    			<thead >
    			<tr>
    				<th >Hostname</th>
    				<th >Hostname</th>
    			</tr>
    			</thead>
    			<tbody>
    				<tr ng-repeat="ne in networkElements" >
    					<td>{{ ne.hostname }}</td>
    					<td>{{ ne.hostname }}</td>
    				</tr>
    			</tbody>
    		</table>
    	</div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            var $table = $("table");
            $table.floatThead({
                position: 'absolute' /////////////////////////////////////// OR 'fixed' in case 2)
            });
    
            $table.floatThead('reflow');
    
            setTimeout(function () {
                $table.floatThead('reflow');
            }, 500);
        });
    </script>
    <script type="text/javascript">
        $(function () {
            var $table = $("table");
            $table.floatThead({
                position: 'absolute', ////////////////////////////////////////// OR 'fixed' in case 2)
                scrollContainer: function (tableTo) {
                    return tableTo.closest(".table-wrapper");
                }
            });
        });
    </script>

So my question is, how to properly use floatThead with center alignment? I am trying to go with absolute position as it was recommended.

Appreciate any input/concerns. Thanks a lot for great plugin. 

BTW I am not using script for floeatThead as shown,, I recreated it to do exactly what my implementation of angular directive for floatThead does for it.. [pastebin](http://pastebin.com/w0JxusA2)

**Comment by mkoryak** [comment]
since you didnt provide a jsfiddle, I will reuse one from another issue:

http://jsfiddle.net/fqo2k6zz/3/

the key here is that the table has a class that is styled via a stylesheet:
```css
table.demo {
    width: 60%;
    margin: 0 auto;
}
```

when the plugin runs, the floated header gets put into a table with the same classes as the original table, thus looks the same.

**Comment by mkoryak** [comment]
ah, i noticed that you were using a container. updated fiddle:
http://jsfiddle.net/fqo2k6zz/4/

you will need to update your css to 
```
table.demo {
    width: 60%;
    margin: 0 auto !important;
}
```
Id have to check the code to see why i ended up setting margin to 0 on the floated table. Im sure I had some reason to do it. Its a bit weird to have a scrollbar not right next to the table

**Comment by MacGyver27** [comment]
Hey mkoryak,

Thank you for speed-light response. I tried what you suggested and it didnt help.. 

For better clarification I created jsfiddle where my issue is occurring: http://jsfiddle.net/MacGyver27/1m35smyp/

Thank you again.

(please bear with me, not an expert or mid)

**Comment by mkoryak** [comment]
you are initializing the plugin twice, once without a scroll container, and once with one, moreover the scroll container `.table-wrapper` does not have any styles defined in the css section.

**Comment by mkoryak** [comment]
anyway, in your example using fixed helps, though it looks to me like that fiddle is probably wrong based on the bugs i mentioned:

http://jsfiddle.net/1m35smyp/1/

**Comment by MacGyver27** [comment]
Thank you for inputs. I fixed it and did an update: http://jsfiddle.net/MacGyver27/1m35smyp/2/
Initially it was like this, without the wrapper.. (I use it in case of enabling all columns so I can scroll horizontally - but now I see it is quite redundant.. - so please disregard wrapper use if possible).

BTW using fixed, on bigger table makes me to see table header twice for short time and it doesn't match final one.. my very last screen capture

So 1 more time if I may bother. Thank you.

**Comment by mkoryak** [comment]
you are probably seeing that because of the set timeout in your code. 
with angular you might be better off with a better way to hook into angular's 'rendering is done' event on the table. perhaps something like this:
http://www.jomendez.com/2015/02/05/angularjs-ng-repeat-onfinishrender-directive/

then you can init the plugin when the table renders. 

you can test if this works by changing the fiddle to be a giant table and see if you still have your problem without angular

**Comment by mkoryak** [comment]
or, try this hacky fix:
http://jsfiddle.net/1m35smyp/3/

I make no guarantees that it wont fuck something up though.

**Comment by MacGyver27** [comment]
Works great! Didnt break anything for me yet. If I observe something will post it here.
Appreciate your time, really.

**Comment by MacGyver27** [comment]
Hey mkoryak,

Found a little problem with that hacky fix.. check here: http://jsfiddle.net/1m35smyp/4/

    .floatThead-container {
         width: 100% !important;
    }

Problem is when your window get narrow enough for triggering horizontal scroll.. then this effect appear:
![i3](http://i61.tinypic.com/104kb41.png)

Problem is that header gets "cut" to container width -> ignoring that I have triggered horizontal scroll..
If I make container wider than whole scroll-able table than it is fine.. http://jsfiddle.net/1m35smyp/5/  so basically rule is container needs to be wider than whole table inside horizontal scroll..


Do you think there is some easy fix or I should try completely different approach?

Thank you.

**Comment by mkoryak** [comment]
yeah, this method voids the warranty of the plugin. I think your best bet would be to init the plugin when angular is done rendering the table with `fixed` position. a cheap way might be to just init it with a `setTimeout`, a better way would be to put a `$watch` on `$last` which is going to be available within the scope of ngRepeat and init the plugin when it becomes true. The directive that I linked above does that, maybe you can use that. It means you will have to modify the source of that angular directive I  think

**Comment by mkoryak** [comment]
maybe i spoke too soon. your problem has nothing to do with my plugin:

http://jsfiddle.net/1m35smyp/7/

thats what happens you dont run the plugin.

**Comment by MacGyver27** [comment]
I agree, thats what I wanst sure about, if my approach is compatible with what your plugin expects.. now I get it, thanks again.. and sorry to bother you
