### ISSUE TITLE
Table columns appear distorted on IE(all versions including edge)  

### ISSUE THREAD

**Issue by raghavak** [mkoryak/floatThead#260]
Table columns appear distorted on IE(all versions including edge) when i apply floatThead.

This is the method i applied.

var $table = $('table.customclass');
	 $table.floatThead({
		 position: 'absolute',
	     scrollContainer: function($table){
	         return $table.closest('.closestDiv');
	     }
	 }); 

Every thing appears just fine once the user re-sizes the browser window of IE. What can be the possible cause for this problem?

**Comment by mkoryak** [comment]
it could have something to do with this: http://mkoryak.github.io/floatThead/examples/row-groups/

I require a jsfiddle reproducing the issue in order to help with code

**Comment by mkoryak** [comment]
no response, closing
