### ISSUE TITLE
Working with responsive tables

### ISSUE THREAD

**Issue by benlevywebdesign** [mkoryak/floatThead#263]
This plugin works exactly as it should. It works great on desktop but when comes to smaller screens the header does not move with the columns and it also does not hide inside the surrounding containing element. I'll link to my web page shortly.

**Comment by mkoryak** [comment]
only if your webpage has a simple example on it.

**Comment by benlevywebdesign** [comment]
Here is the current page with out the script: [projectrequests.php](http://benlevywebdesign.com/aaudining/projectrequests.php)

Here is the link to a test page on my site: [projectrequests_fixedheader.php](http://benlevywebdesign.com/aaudining/projectrequests_fixedheader.php)

It works alright on mobile for me (the table isn't best viewed on mobile anyways and will most of the time be viewed on a desktop screen). The one issue for the header is when the window is smaller than 1200px (see the image below). 
![Image of header](http://i.imgur.com/6Cu1dxx.png) 
It overflows outside of my containing element. Why its CPU heavy?

**Comment by mkoryak** [comment]
i noticed that at the smaller resolution `.table-responsive` starts acting like a scrolling container. my plugin expects that window will be firing the scroll-x events, but probably the scrolling it happening on that div. 

i think the y scrolling is happening on the window still. my plugin currently does not support 2 different containers providing the scroll events, though I am considering adding that functionality. Your example is the first one ive seen where you arent doing something incredibly stupid :)

**Comment by benlevywebdesign** [comment]
So disable it below 1200px. A lot of the plugins that I have found require your table to have a fixed height and yours doesn't which is good because my table will continue to grow and get longer.

**Comment by benlevywebdesign** [comment]
So disable it below 1200px. A lot of the plugins that I have found require your table to have a fixed height and yours doesn't which is good because my table will continue to grow and get longer.

**Comment by benlevywebdesign** [comment]
So disable it below 1200px. A lot of the plugins that I have found require your table to have a fixed height and yours doesn't which is good because my table will continue to grow and get longer.

**Comment by jfly** [comment]
:+1: This is a pretty big omission for anyone using Bootstrap. The Bootstrap documentation for [responsive tables](http://getbootstrap.com/css/#tables-responsive) tells you to use this exact problematic `.table-responsive` wrapper. I've worked around this by adding a scroll listener to the wrapping `.table-responsive` as so:

```javascript
  var $tablesToFloatHeaders = $('table.floatThead');
  $tablesToFloatHeaders.floatThead();
  $tablesToFloatHeaders.each(function() {
    var $table = $(this);
    $table.closest('.table-responsive').scroll(function(e) {
      $table.floatThead('reflow');
    }); 
  });
```

It would be mighty nice if the `scrollContainer` option did this for me.

**Comment by mkoryak** [comment]
thanks for the link do the table-responsive docs. I havent seen these. This issue in on my radar, ill be getting to it for next release

**Comment by mrdulin** [comment]
Have the same issue~ seems the best way is to disable it.
![image](https://cloud.githubusercontent.com/assets/17866683/13810694/10d08704-ebac-11e5-9fff-79ff2ee2eed3.png)

**Comment by mkoryak** [comment]
I looked into a quick fix for this. not possible without hacking it. The lib was never designed to be able to change the element which was treated as the scroll container. I would really like to come up with a solution that does not involve destroying the instance.
