### ISSUE TITLE
Header misalignment (windows, when inside of a floated element)

### ISSUE THREAD

**Issue by eug48** [mkoryak/floatThead#264]
I'm having alignment problems when using absolute positioning - please see http://jsfiddle.net/6pxhhuke/15/

Interestingly resizing the jQuery UI dialog seems to fix the alignment (still imperfect in Firefox) but adds unwanted horizontal scrollbars. Your help would be much appreciated! This is a really great plugin.

**Comment by mkoryak** [comment]
what browser/os ? looks fine here on chrome/osx

**Comment by eug48** [comment]
For example Chrome 46 on Windows 10: http://i.imgur.com/nsmtoRW.png. Very similar with Firefox 42 on Windows 10 and MS Edge.

**Comment by mkoryak** [comment]
I was able to reproduce on a window7 vm in chrome. do you know if it works without the ui dialog?

**Comment by eug48** [comment]
Without the UI dialog it's still broken but can be fixed by using position:fixed - however position:fixed does not work with the dialog.

**Comment by mkoryak** [comment]
actually the bug has to do with the styling of the .floater

see
http://jsfiddle.net/6pxhhuke/17/

**Comment by mkoryak** [comment]
That took a few hours to track down, but I finally found the bug in my code. It should be better now. There is still a question about horizontal scrollbars appearing there when they probably should not, but at least you can work around that by setting a min-width on the wrapper or floater.  Ill revisit this one again about the scrollbars.

**Comment by eug48** [comment]
Thanks, that is definitely better. The alignment is now almost perfect in Chrome but a few pixels off in Firefox and Edge.

**Comment by mkoryak** [comment]
Have you tried setting a min width on the floater and see if it helps?

**Comment by eug48** [comment]
min-width does fix it but I'm not sure it'd be practical since I need the tables to float next to each other.

**Comment by mkoryak** [comment]
this is still on my radar, i just need to find the time

**Comment by eug48** [comment]
I think I've found a solution! Setting .wrapper to use "overflow-y: scroll; display: inline-block;" seems to do what I want.

**Comment by mkoryak** [comment]
thats good. im pretty sure there is still a bug in my code, but it smells like "im fighting the browser's layout" bug which lead to lots of code to fix. 

im going to mark it as workaround and let it be.
