### ISSUE TITLE
Floating Thead Covers Part of the Table on IE

### ISSUE THREAD

**Issue by TwentyOneSolutions** [mkoryak/floatThead#266]
Hi,

I'm seeing an issue on IE where the floating thead covers the top part of the table data.  I have searched the issues here and tried the `meta http-equiv="X-UA-Compatible"` but it doesn't seem to do anything.

The table head has two rows, with some of the cells spanning over more than one column.  When I use only one row it works fine, so I'm thinking that the issue is with the part that calculates the thead-height.

Is it possible to specify the height?  Or if you could point me in the direction of where it is calculated I will be able to provide more information.

Works well on Chrome.

Thank you!

**Comment by TwentyOneSolutions** [comment]
I have added

    console.log(headerHeight);

at the end of `setHeaderHeight()` and the correct value of 81.5 is shown on both Chrome and IE.

I also tried to add

    headerHeight = Math.ceil(headerHeight);

in case the issue was with the fraction, but that didn't help either.

**Comment by mkoryak** [comment]
Put up a jsfiddle and then I'll help you

**Comment by TwentyOneSolutions** [comment]
Thank you for your help.  Please see fiddle at https://jsfiddle.net/1m1pstL4/1/ and the results at https://jsfiddle.net/1m1pstL4/1/embedded/result/

I'm attaching screenshots below from IE11 and Chrome.  Notice how the red TH covers the top of the table contents, while Chrome displays it properly.

Also -- as a separate known issue -- I know that you have a page explaining the issue with colspans on IE, but I don't quite understand what I need to do to fix that.  Do I just need to pass values from the first row that contains the TD cells aligned with the TH?

Thanks again!

IE11:
![image](https://cloud.githubusercontent.com/assets/885907/11281787/0e9c1d16-8eb1-11e5-8bfc-682923922b22.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/885907/11281800/1de2d274-8eb1-11e5-90d5-937308b0025e.png)

**Comment by mkoryak** [comment]
I should try to update those docs to make them more understandable. 

you were missing a tbody tag, you should always use them, they are required by the spec.

here is the fix:
https://jsfiddle.net/1m1pstL4/3/

**Comment by TwentyOneSolutions** [comment]
Thank you very much for your help.

It looks like the tbody tag is not needed once the `getSizingRow()` function is passed.  I simply added the class `data-row` to the data rows and selected the first one via `$table.find("tr.data-row:first>*")`

If I had realized that `getSizingRow()` takes care of this issue as well I would have spent more time looking into it, but I thought that it was just for the column aligning.

Thanks again!

**Comment by TwentyOneSolutions** [comment]
Looks like both Chrome and IE11 add `tbody` if it does not exist.

How do you feel about adding something like this to the plugin to find the sizing row?

    var longestRow = [0, 0];

    $("tbody > tr").each( function(i, e) { 
        
        if (i > 10) return;

        var c = $(e).children().length; 
        if (c > longestRow[0]) 
            longestRow = [c, i]; 
    } );

    sizingRow = longestRow[1];

**Comment by TwentyOneSolutions** [comment]
FYI:  The generic solution below works for me, and IMO can/should be used as a default if getSizingRow() is not passed.

I can provide a pull request if it resonates with you.


	$(".float-thead").floatThead({

		getSizingRow: function($table){

			var row = { count: 0, children: null };

			$table.find("tbody>tr").each( function(i, e) {

			    if (i > 10)		return;

			    var c = $(e).children();
			    if (c.length > row.count) {

			        row = { count: c.length, children: c };
			    }
			} );

			return row.children;
		}
	});

**Comment by mkoryak** [comment]
I dont want to assume anything about the tables this plugin operates on. It should be up to the programmer to add a more sane implementation of this function. Also this might be bad on a table with a very large number of rows.

**Comment by TwentyOneSolutions** [comment]
> I dont want to assume anything about the tables this plugin operates on. It should be up to the programmer to add a more sane implementation of this function.

I understand, but providing a sane solution can be very helpful in most situations.  It would have saved me (and actually, you too) time.  

I guess the docs can be updated to explain what getSizingRow() should return, which is actually the children of the row.

> Also this might be bad on a table with a very large number of rows.

That's why the function exists after about 10 rows, and avoids large table scans.  It assumes that the sizing row is in the first 10, but even if you set it to 100 it wouldn't be noticeable.

Anyway, that's my suggestion.  It's fine if you disagree.  Thank you again for your help.

**Comment by mkoryak** [comment]
the `$table.find("tr")` is the problem if the table has a lot of rows. The return does not terminate the loop, it shortcuts the logic.

also there is a bug there which the original implementation does not have because it lacks the complexity. 

I will update the docs with the better wording and your suggested impl

**Comment by mkoryak** [comment]
I take that back, your first comment didnt have the bug :)
