### ISSUE TITLE
When will be the next release?

### ISSUE THREAD

**Issue by imnutz** [mkoryak/floatThead#267]
Hi,

I'm currently using floatThead in my project, it works very well. Thanks for the great lib.

Recently, we want to catch "reflowed" event to do some other works after floatThead reflowed. Unfortunately, the "reflowed" event triggering is only in master, it hasn't been released yet. So we cannot use the new feature with ```bower```.
Do you have any plan to release it soon?

**Comment by mkoryak** [comment]
released, should be on npm and bower now

**Comment by imnutz** [comment]
:+1:  Thanks for this.
