### ISSUE TITLE
Only move thead when needed

### ISSUE THREAD

**Issue by Worst45** [mkoryak/floatThead#269]
Hello,

just a little feature proposal: for now, the thead is moved in javascript even when it is not already needed (for example, when the user begin to scroll page, but the thead is still in the page viewport).

We can see small "jumps" of the thead (of one or two pixels) on IE / FF when it rescall 

It would be great if you can improve your plugin so that the thead only move when it's position is before the 'top' property.

(Great job)

**Comment by mkoryak** [comment]
Pull requests are always welcome :)

Did you try using a different position mode?
see:
http://mkoryak.github.io/floatThead/examples/window-scrolling/
