### ISSUE TITLE
Works only if the  container height is in px. Support for % height

### ISSUE THREAD

**Issue by dragonnn** [mkoryak/floatThead#273]
Like in the title. It is possible to get floatthead when div have height in %?

**Comment by mkoryak** [comment]
https://jsfiddle.net/tm03s8y4/4/

**Comment by mkoryak** [comment]
let me know if you have any more issues here

**Comment by dragonnn** [comment]
Ah, I know where the problem is, it breaks if the table is initalized before the content is visiable. Thank you for help
