### ISSUE TITLE
IE issue: Table inside th

### ISSUE THREAD

**Issue by kris6** [mkoryak/floatThead#274]
Hello.

I have an issue in IE (tested on IE11). 
I'm using bootstrap 3. It works correctly in Chrome and Firefox.

I have something like this in the table header, another table inside th element. I think this is what causes the problem on IE.

<table>
<thead>
<tr>
<th></th>
<th>
      <table>
             <tr>
                <th></th>
               <th></th>
                <th></th> 
           <th></th>
           <th></th>        
             </tr>
     </table>
</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
</table>

The table is this way because in the tbody I need dynamic rows. Sorry if this issue has been addressed before, couldn't find it in the "Closed" section.

This is how the table looks after scrolling.

![screenshot_3](https://cloud.githubusercontent.com/assets/16428249/11996192/9b2808b2-aa5e-11e5-8d61-51ed54236165.png)

**Comment by kris6** [comment]
The problem was in my code.

I had a column:
<td style="display:none;">...</td>

which caused the error for IE, but not for the other browsers.

**Comment by mkoryak** [comment]
My favorite kind of issue :)
