### ISSUE TITLE
Strange offset on x scrooling

### ISSUE THREAD

**Issue by dragonnn** [mkoryak/floatThead#275]
I have a table with many columns, when I scrool it to the end this happends:
http://i.imgur.com/owwm7Zy.png
This offset get only visiable is on the end of the table. On 90% of the scrool it works fine.

**Comment by mkoryak** [comment]
Jsfiddle please

On Dec 28, 2015 2:31 AM, "Mateusz" <notifications@github.com> wrote:
>
> I have a table with many columns, when I scrool it to the end this
happends:
> http://iimgurcom/owwm7Zypng
> This offset get only visiable is on the end of the table On 90% of the
scrool it works fine

**Comment by dragonnn** [comment]
http://codepen.io/anon/pen/dGOOxd test it here, when you scrool x to the end the header get missalgined. Didn't use jsfiddle because with my gtk theme I don't see text in the editor Oo.

**Comment by mkoryak** [comment]
sorry, this doesnt work for me in chrome:

```
Refused to execute script from 'https://raw.githubusercontent.com/mkoryak/floatThead/master/dist/jquery.floatThead.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
pen.js:167 Uncaught TypeError: $(...).floatThead is not a function
```

**Comment by mkoryak** [comment]
you are using `.table-responsive` this is a known issue and is being tracked here: 

https://github.com/mkoryak/floatThead/issues/263
