### ISSUE TITLE
Bootgrid + floatThead - headers doesn't update on reflow after hide column

### ISSUE THREAD

**Issue by dragonnn** [mkoryak/floatThead#277]
http://codepen.io/anon/pen/OMbbYr
When you test it and hide a column from the bootgrid menu even after maunal reflow the header isn't update.

**Comment by mkoryak** [comment]
you are using `.table-responsive` this is a known issue and is being tracked here: 

https://github.com/mkoryak/floatThead/issues/263

**Comment by dragonnn** [comment]
http://codepen.io/anon/pen/OMbbYr without table-responsive the problem still exist. So I don't think it it connected with it.

**Comment by mkoryak** [comment]
ok, on chrome/ osx your example does this for me:

```bash
OMbbYr:1 Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewogICAgLy8gaHR0cHM6Ly9k…ogICAgZ2EucmVtb3ZlID0gbm9vcGZuOwogICAgd2luZG93W2dhTmFtZV0gPSBnYTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' http://preprocessor.codepen.io http://*.pubnub.com https://*.pubnub.com http://platform.twitter.com http://connect.facebook.net http://www.google-analytics.com https://*.google-analytics.com https://*.google.com http://wufoo.com https://wufoo.com http://*.wufoo.com https://*.wufoo.com https://*.stripe.com https://*.instapaper.com http://*.instapaper.com http://dc8na2hxrj29i.cloudfront.net http://s3.buysellads.com http://srv.buysellads.com/ https://www.fullstory.com https://stats.buysellads.com http://stats.buysellads.com https://*.braintreegateway.com https://www.paypalobjects.com http://assets.codepen.io http://assets.codepen.io/ https://assets.codepen.io https://assets.codepen.io/ http://assets.cdpn.io".

index.html:1 Refused to execute script from 'https://raw.githubusercontent.com/mkoryak/floatThead/master/dist/jquery.floatThead.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
pen.js:14 Uncaught TypeError: $(...).floatThead is not a function
```

fix that, and I will take a look

**Comment by dragonnn** [comment]
http://codepen.io/anon/pen/vLxKxd now it should work, works on Chromium too so it should be ok.

**Comment by mkoryak** [comment]
sorry, this is a problem with bootgrid. it does not cache elements in the table, so when it removes columns it will only remove them from the table, not from the floated header, which is no longer  part of the table. 

you should try this plugin, as it does not move the header outside of the table:
https://github.com/jmosbech/StickyTableHeaders
