### ISSUE TITLE
table layout changes from auto to fixed when manipulating the rows.

### ISSUE THREAD

**Issue by datzap** [mkoryak/floatThead#279]
This is a question.  I have 2 tables that I apply floatThead to.  It works great.  I do some sorting on the table when the user clicks one of the headers.  I do a reflow and the table layout has been changed from auto to fixed. 

The question is what can I look at to figure this out?

**Comment by mkoryak** [comment]
this plugin changes the table layout from auto to fixed in order to work. if the table layout is still broken after a reflow, please create a jsfiddle the reproduces the issue.  also make sure that everything works correctly without the plugin

**Comment by datzap** [comment]
I cant do jsfiddle.  I am not allowed to post code outside the company.  

The sort function that appears to be causing the issue does the following.  The rows are gathered and sorted then added back into the table.  Would that cause an issue?

**Comment by datzap** [comment]
I figured it out.

Because I was adding the rows back in, floatThead needed to be removed first then recreated after the rows were added back in.

Thank you for your help.

**Comment by mkoryak** [comment]
did you try calling/triggering `reflow` from the docs?

**Comment by datzap** [comment]
Yes That did not work.  Instead I destroyed the floatThead added the rows back in and then added the floatThead.
