### ISSUE TITLE
Reflow after container style change

### ISSUE THREAD

**Issue by Anubhav-Bhojne** [mkoryak/floatThead#281]
@mkoryak  Many thanks for a wonderful plugin.

The fix mentioned at https://github.com/mkoryak/floatThead/issues/268  works for me if we have a table with vertical scroll. However it does not work if we have only 2 rows without a vertical scroll.
Any suggestions

**Comment by mkoryak** [comment]
need jsfiddle

**Comment by mkoryak** [comment]
no response, closing. reopen when you have a jsfiddle
