### ISSUE TITLE
Error with datatable textbox filter

### ISSUE THREAD

**Issue by zendre4** [mkoryak/floatThead#284]
When use this plugin with the filter of datatable, this plugin bind an event call "filter" and make a reflow of the header.

The problem is, if the filter wich was call reflow is a textbox filter , this textbox lose the focus like this : 

![datatable1](https://cloud.githubusercontent.com/assets/9673982/12847108/52ee6044-cc11-11e5-8ce0-08cabdef2d75.PNG) 
->
![datatable2](https://cloud.githubusercontent.com/assets/9673982/12847117/5fe5c1ca-cc11-11e5-971f-048788d6a6c1.PNG)

So the user can't type many character right now.

For fix it I offer this solution : 

```
/**
 * returns a function that updates the floating header's cell widths.
 * @return {Function}
 */
function reflow(){
  var i;
  var numCols = columnNum(); //if the tables columns changed dynamically since last time (datatables), rebuild the sizer rows and get a new count

  return function(){
    $tableCells = $tableColGroup.find('col');
    var $rowCells = getSizingRow($table, $tableCells, $fthCells, ieVersion);

    if($rowCells.length == numCols && numCols > 0){
      if(!existingColGroup){
        for(i=0; i < numCols; i++){
          $tableCells.eq(i).css('width', '');
        }
      }

      /** add for fix it **/
      var focusTextBox=null;
      var activeElement=document.activeElement;
      if(activeElement && $(activeElement).parents($table).length > 0) {
        if (activeElement.tagName && activeElement.tagName.toLowerCase() == "input" && activeElement.type.toLowerCase() == "text") {
          focusTextBox = activeElement;
        }
      }

      unfloat();
      var widths = [];
      for(i=0; i < numCols; i++){
        widths[i] = getOffsetWidth($rowCells.get(i));
      }
      for(i=0; i < numCols; i++){
        $headerCells.eq(i).width(widths[i]);
        $tableCells.eq(i).width(widths[i]);
      }
      refloat();

      /** add for fix it **/
      if(focusTextBox) {
        $(focusTextBox).focus();
      }

    } else {
      $floatTable.append($header);
      $table.css(layoutAuto);
      $floatTable.css(layoutAuto);
      setHeaderHeight();
    }
    $table.triggerHandler("reflowed", [$floatContainer]);
  };
}
```
If the active element is a textbox and is a descendant of the table i replace after reflow the cursor in the textbox.

Can you integrate this modification in this plugin ? I can open a pull request if you want ...

Thanks for this awesome plugin !

**Comment by mkoryak** [comment]
This code looks too specific to a problem one user has to force it upon everyone. 

I would rather add another event that will be triggered before the reflow logic takes place and you can bind to that and to `reflowed` and put this logic in there.

The solution this plugin provides is floating your table's header, doing stuff with `document.activeElement` is outside of that scope.

**Comment by mkoryak** [comment]
closing with no response. reopen if you have a reply

**Comment by zendre4** [comment]
Sorry, I was on vacation, but your solution is ok for me !
