### ISSUE TITLE
This plugin is not working if using jquery datatables with col-resize plugin

### ISSUE THREAD

**Issue by falinsin** [mkoryak/floatThead#287]
This is tthe plugin

https://github.com/Silvacom/colResize

This plugin alows user resize columns like excell so the datatable  grows width.

**Comment by mkoryak** [comment]
you seemed to have ignored the issue template.

**Comment by mkoryak** [comment]
moreover, that plugin has 33 stars and 11 issues, some from last year. It is a datatables plugin. I can sometimes find a fix for a jquery plugin that will make it compatible, but I know nothing about datatable plugins.
