### ISSUE TITLE
Associate floated table with original table

### ISSUE THREAD

**Issue by kindler** [mkoryak/floatThead#288]
Hello - great work on the floating header!

I'm trying to overcome an issue where I have a sortable table and when the <thead> is cloned to the floating table, my click handlers break.

I was looking to setup an alternate click handler where, when I click on a floated column heading, it would sort the associated table by the corresponding column.  I was looking to have some sort of attribute on the table that would tie the floated table to the table it pulled the <thead> from (make sense?)

So, maybe something like this:

```
<table class="floatThead-table" data-relatedto="A712F43">...</table>
```
which would relate to
```
<table class="...." id="A712F43">...</table>
```

If the original table does not have an ID, you could generate one randomly.

Thoughts?

Thanks again!

**Comment by mkoryak** [comment]
hmm, this method isnt documented, I should update docs:

```js
const $table = ....
$table.floatThead(...);
const $floatingTable = $table.getFloatContainer().find('table');
```

**Comment by mkoryak** [comment]
another idea would be to bind the click events to a container around the table, and delegate them into column headers, because then it will just work, and thats how it is meant to work.

**Comment by mkoryak** [comment]
updates?

**Comment by mkoryak** [comment]
no response, closing

**Comment by kindler** [comment]
Apologies – I had to go on a last-minute trip out of town and I am just returning, so I have not had an opportunity to address this issue.

I like the idea of binding the column header click events to a container around the table then delegate them to the table for sorting, but I will still need an association between the floating table and the underlying table unless I can always assume they will be adjacent to each other.  I saw your other post regarding your “getFloatContainer()” method and that may do the trick for me.

I will try to get back to this issue in the next week.  Thank you for your responses.

Rich
___________________________________________________
Rich Kindle
Brokerage Internet & Intranet Group
Wells Fargo Advisors | 1 N. Jefferson, E5 13N | St. Louis MO 63101
MAC H0005-051
Tel  314 875 4397
rich.kindle@wellsfargoadvisors.com<mailto:rich.kindle@wellsfargoadvisors.com>
Upcoming PTO: None
