### ISSUE TITLE
floatTheader breaks if <thead> element has multiple rows

### ISSUE THREAD

**Issue by hongjos** [mkoryak/floatThead#29]
If the table has multiple rows in the header:

eg
```
<thead>
  <tr>
     (the title of the table)
  </tr>
  <tr>
     (the column headers in multiple <th>
  </tr>
</thead>
```
This plugin breaks - what if we want to include the column headers as part of the scrollable part along with the table title?

**Comment by casey6** [comment]
Your examples don't seem to be working in IE.

**Comment by mkoryak** [comment]
they actually dont work in any browser. I broke it at some point, thanks for reminding me about this.

**Comment by mkoryak** [comment]
err, you reminded me about a different issue. this should work. What version of IE do you use?

**Comment by casey6** [comment]
In IE11 it's not working for me.

**Comment by mkoryak** [comment]
was the example not working because it was linking to floatThead in a place that no longer exists?

this works:
http://jsfiddle.net/P8GFy/4/

**Comment by casey6** [comment]
That example works for you in IE11? It does not for me.

http://i.imgur.com/aO1Oabi.png

**Comment by mkoryak** [comment]
no, it doesnt work, but look at the console. it cant find jquery, yet jquery is on the page (or so it claims)

**Comment by mkoryak** [comment]
here we go, using an ancient version of jquery makes it work:
http://jsfiddle.net/P8GFy/6/
