### ISSUE TITLE
Datatable Buttons

### ISSUE THREAD

**Issue by ankurmitujjain** [mkoryak/floatThead#290]
I am using datatables with Buttons plugin, I am using latest floatThead plugin 
I tried to fix header , search box and button to be fixed but somehow it seems that only table headers are fixed.
Is there any way I can fix search box and buttons?

Thanks
Ankur

**Comment by mkoryak** [comment]
I cant provide help related to 3rd party datatables plugins, especially if you cant provide a jsfiddle.
