### ISSUE TITLE
After triggering the table, it takes 2 seconds to adjust or load the table in the correct way

### ISSUE THREAD

**Issue by mvarun459** [mkoryak/floatThead#293]
Please help me help you by providing the following information with your issue:

I had initialized the Table By following code

$scope.floatTheadOptions = {
                scrollContainer: function ($table) {
                    return $table.closest('.table-responsive');
                }
            };

After my APi success i am writing 

**$('.table').trigger('update');**

After adding the Some data  i am triggering the table again by **$('.table').trigger('update');**

But it takes 2 seconds to adjust the table correctly.

Please let me know on this.

- browser name/version   All Browsers
- OS name       All OS
- jQuery version if not latest   -   2.1.4
- floatThead version if not latest   -    1.4.0

- jsfiddle that reproduces your issue in its simplest form possible [required]

A description of the issue and steps to reproduce

Thanks!

**Comment by mkoryak** [comment]
read docs about `responsiveContainer`. you need that instead of `scrollContainer`, I think.

I dont know what `$('.table').trigger('update');` it is not part of my API

**Comment by mkoryak** [comment]
feel free to reopen when you have fully read the docs, and have a jsfiddle
