### ISSUE TITLE
FloadThead horizontal scroll reset after data table new row

### ISSUE THREAD

**Issue by fbuscaroli** [mkoryak/floatThead#295]
I've a table with 10 columns 4 are overflowed. When i scroll to the right to view the hidden columns and add a new line (change the underlying data - i'm using angular) FT scrolls header back to its initial view (columns 1-6).

Reflow does not seem to work. 

Using scrollContainer and autoReflow.

Is there any way to tell FT to keep the current scroll position while reflowing?

Thanks

**Comment by mkoryak** [comment]
there is no way to tell it to keep the current scroll position. you can use the event it provides and write it yourself i suppose

**Comment by mkoryak** [comment]
without a jsfiddle/or some other live example, that is the extent of a help i will be able to provide

**Comment by fbuscaroli** [comment]
The example is tedious to write considering it involves actions to produce error.
I'm sending 3 pictures that shows the error.
Anyway it seems that after removing autoReflaw from the init options everything works fine.
![snip_20160404162251](https://cloud.githubusercontent.com/assets/18258240/14251202/28dc1d9c-fa82-11e5-8b29-ca114f06dc7a.png)
![snip_20160404162527](https://cloud.githubusercontent.com/assets/18258240/14251201/28dafc32-fa82-11e5-8b94-4606a30474b1.png)
![snip_20160404162720](https://cloud.githubusercontent.com/assets/18258240/14251200/28d9c542-fa82-11e5-80a2-93d012f4b3d6.png)

**Comment by mkoryak** [comment]
right, autoreflow will trigger reflow when you modify the table contents or attributes. if you are just adding a row that shouldnt have any effect on the floated header position. Are you using the angular plugin from my readme?

is your issue solved?

**Comment by fbuscaroli** [comment]
Yes, the problem occurs only when the underlying table content is modified, not while just scrolling.
No i'm using jquery plug-in.
Yes the error evaporates as i switch from autoReflow: true to false.

**Comment by mkoryak** [comment]
ok, closing with workaround then
