### ISSUE TITLE
floatThead not rendering properly in Bootstrap Accordian collapse

### ISSUE THREAD

**Issue by chinm3** [mkoryak/floatThead#296]
Hi Misha,

I’m currently doing a Ruby on Rails project where I’m using Bootstrap as my front-end. I’m also using jQuery.floatThead as the solution to my DataTables sticky header. Everything works great, except one issue, which I’m not sure if you’re aware of this, but there seems to be an issue when floatThead is being rendered  inside an Accordion Panel (Bootstrap).

I’ll try to explain it the best I can. So when u collapse one panel which have DataTables and floatThead inside it, it works fine. But when you have two or more panel collapse, one being open, and one being closed. The floatThead sticks in mid air (like it freezes) until you scroll the screen once, then it behaves correctly.

As you can see in the jsFiddle version, the bug is reproduced if you try to open close them a few times.
I've made the screen wider in jsFiddle so it's more obvious.

- http://jsfiddle.net/ebRXw/1668/
- Mozilla & Chrome both latest version as of 6th Apr 2016
- OSX 10.10.5
- Using jquery-rails 4.1.1
  Using jquery-ui-rails 5.0.5
- floatThead version 1.4.0

![screen shot 2016-04-06 at 4 09 31 pm](https://cloud.githubusercontent.com/assets/11044476/14305591/05b1b502-fc12-11e5-822f-1876712777cf.png)
(As you can see in this picture, it gets stuck in mid-air only until you scroll. This is the same issue I'm having in my rails version.)

Hope this clarifies,
Thanks.

**Comment by mkoryak** [comment]
here you go:

http://jsfiddle.net/ebRXw/1675/

absolute positioning is better when you want the floated header to live in the same container as the table

you also want to trigger reflow when a new collapse is shown to tell the plugin that it should update itself

**Comment by chinm3** [comment]
That seems to fix the issue, although it doesn't feel natural :(. But thanks anyways! Amazing work on floatThead :+1:

**Comment by mkoryak** [comment]
it may not feel natural, but it is the only way to do what you want.
