### ISSUE TITLE
Padding and Margin Causes Header Mis-alignment

### ISSUE THREAD

**Issue by kev22257** [mkoryak/floatThead#297]
I'm having an issue where using the library and Bootstrap together is giving me alignment issues (sometimes).  I don't have an issue on FF.  On Chrome the header is 15px too far to the left and also 15px too short.  On IE the header is positioned correctly left to right, but is still 15px too short.  This fiddle sort of demonstrates the problem.  I think I've boiled it down to having negative margin with positive padding.

https://jsfiddle.net/w8hq7kg5/

Windows 7 (Version 6.1.7601)
Firefox 45.0.1
IE 11
Chrome 49.0.2623.110 m
jQuery.floatThead 1.4.0
jQuery v2.1.4

![chrome](https://cloud.githubusercontent.com/assets/18400800/14431826/73401430-ffd5-11e5-87ed-112606c2f2cf.png)
![firefox](https://cloud.githubusercontent.com/assets/18400800/14431825/733aebf4-ffd5-11e5-8eb7-b13a9a8ac5ad.png)
![ie](https://cloud.githubusercontent.com/assets/18400800/14431827/7348b450-ffd5-11e5-9ede-a3f5580695fb.png)

**Comment by kev22257** [comment]
Sigh.  Since GIT couldn't be bothered to keep my filenames for the images they are, in order, Chrome, FF and IE.

**Comment by mkoryak** [comment]
Sorry, figuring out complex layouts like that is beyond the scope of what this plugin should do. You can work around it by making sure that the generated html still works by messing around with the css. 

https://jsfiddle.net/w8hq7kg5/1/

**Comment by kev22257** [comment]
Thanks!

**Comment by kev22257** [comment]
I discovered my issue today.  It appears that I was mostly being confused by a confounded behavior in IE (surprise!).  When floatThead goes to set the left and right padding of the div around the headers it makes them match the left and right padding of the div around the table.  For some reason while the page is first being rendered IE returns the padding of the table div as 0px for left and right when in my case the right answer is 15px.  Chrome and Firefox do NOT do this.  I made another ugly hack to get around it.

`
setTimeout(function() {
                        $("div.floatThead-container").css("paddingLeft", 
                                $("div.floatThead-container").siblings("div").css("paddingLeft"));
                        $("div.floatThead-container").css("paddingRight", 
                                $("div.floatThead-container").siblings("div").css("paddingRight"));
                    }, 100);
`

**Comment by mkoryak** [comment]
Ah, good old IE. 15px is the width of scrollbar in most browsers. There might be some bug with me not detecting it properly. You should look at the function that gets scrollbar width and see if it reports different values for different browsers.
