### ISSUE TITLE
'shown.bs.tab' definition is too broad

### ISSUE THREAD

**Issue by D144** [mkoryak/floatThead#298]
https://jsfiddle.net/xoqam2v6/3/

Anytime a bootstrap tab is clicked, no matter if the tab is related to the table itself, the reflowEvent fires.

In the example in the jsfiddle, activity in the tabs leads to the contents of the table being updated, but when the reflowEvent fires, the `thead` in the table is removed, causing the floatThead to block the first row.

If I comment out `$window.on(eventName('shown.bs.tab'), reflowEvent)` and fire a manual `$('#table').floatThead('reflow')` after updating the table contents, the thead issue does not occur

**Comment by mkoryak** [comment]
Taking that out that functionality will upset all the people who never read the docs and complain that the tables look weird when they switch to a tab with one of them in there. 

Perhaps the right thing to do here would be to introduce a way to opt out of this behavior?

**Comment by mkoryak** [comment]
```js
$table.floatThead({
  support: {
     bootstrap: false
  }
});

actually, i think that will also opt you out the 3 other frameworks i support, ill fix that later, but I think you dont care. 

another way would be

```js
$table.floatThead({
  support: false
});
```

opt out of eveything

**Comment by mkoryak** [comment]
this is on master, 
let me know if you have issues
