### ISSUE TITLE
feedback can go here

### ISSUE THREAD

**Issue by mkoryak** [mkoryak/floatThead#30]
There is some stuff in here that I want to eventually do. 

### simplify options object keys
i cant remember what some of the options are called. make them simpler and bump major version

### Data attributes and plugin init

I am going to add the ability to initialize the plugin via data attributes

When using data attributes it would make sense to be able to init the plugin on when using overflow scrolling like this:

```
<div style='overflow:auto; height:100px' data-provide='floatThead'>
   <table>.... </table>
</div>
```

which would be the equivalent to this (in the current version):
```
$('table').floatThead(scrollContainer: function($table){ return $table.closest('div'); })
```

except that I am thinking that it makes sense to allow you to run the floatThead plugin on non-table elements, and doing so will make the plugin assume that this is the <code>scrollContainer</code> element. It will then find the first table element within that DOM element and initialize it with overflow scrolling. 

Right now I throw an error if you run the plugin on non-table elements. 

The alternative would be to support this kind of syntax:
```
<div style='overflow:auto; height:100px' id='my-container'>
   <table data-provide='floatThead' data-fth-scroll-container='#my-container'>....         </table>
</div>
```

Doing this will not introduce any 'breaking' changes but its not quite as nice.

**Comment by janbrus** [comment]
To get the plugin to handle predefined table witdhs in percent or pixels would be highly appreciated.

**Comment by mkoryak** [comment]
@janbrus I might be wrong, but you can configure custom widths if you included your own `<colgroup>` in the table with col tags that specify the widths:
``` html
`<table>
<colgroup>
<col style='width:30%'/>
<col style='width:70%'/>
</colgroup>
<thead>
<tr><th>bar</th><th>foo</th></tr>
</thead>
....
</table>
````

**Comment by mkoryak** [comment]
@andri I added perfect-scrollbar support. its not released yet, but is on master. here is a demo:
http://mkoryak.github.io/floatThead/examples/perfect-scrollbar/

**Comment by ccjmne** [comment]
Great job - _really_!
I'd love to be able to have my table being dynamically set a given class whenever the header is "actively" fixed.
I mean: when using window scrolling for example, having that custom class being added to the container div as soon and as long as its css property `top` is set to `0px` (`<scrollingTop>px` to be pedantic).
Would be a nice way to add a lil' shadow just underneath my header when it's hovering over some rows.

**Comment by mkoryak** [comment]
Thanks, 
I've heard this request before and I think it makes sense. I think ill set it up to fire an event on the table when the header is un/floated, that way you can do whatever you want based on those events. 

I would have done this sooner, but there is some complexity there because based on `useAbsolutePositoning` the header is sometimes not actually unfloated back into the table, it just looks like it is. anyway, I have all the information to do it.

**Comment by ccjmne** [comment]
Oh yeah, that'll be just fine, if not better. Thanks :+1:
