### ISSUE TITLE
`floatThead` event is not fired when the page loads mid-way through a table

### ISSUE THREAD

**Issue by rinogo** [mkoryak/floatThead#301]
If the page loads mid-way through a table (e.g. if the page is reloaded at a non-zero scroll position), the `floatThead` event is not fired.  However, the header is, actually, already floated, even though the event hasn't fired.  This can cause code that relies upon `floattHead` to malfunction since it implies an incorrect state of the floated header.

Fiddle: https://jsfiddle.net/0hju0ex4/6/

Browser, OS, and jQuery versions appear to not be relevant to this issue.  Regardless, this appears on my up-to-date Chrome Canary and Firefox browsers.

**Comment by mkoryak** [comment]
thanks for the report. ill try to get to it this week

**Comment by mkoryak** [comment]
by the way, did you ever need to change the meaning of `.fontSize16` to say `font-size:1.6rem;` or `font-size:12px`  ?

**Comment by mkoryak** [comment]
Its not a bug, the problem is that your event handler was bound after the event happened. try this:

https://jsfiddle.net/0hju0ex4/7/

**Comment by rinogo** [comment]
Excellent.  Thanks for noticing that; sorry for wasting your time!

I was going to submit a pull request to update the documentation, but I can't find it on GH; it looks like the docs are privately hosted on the web server only.  Here are some changes that might help others avoid this problem:

In "Events Produced" -> "floatThead":
"The plugin will trigger this event on the table when the header is floated and unfloated. The 2nd and 3rd params in the method are of interest to you.  As shown below, be certain to add your event handlers before calling `.floatThead()`, or your code may miss `floatThead` events."

Code sample needs to be updated to move `.floatThead()` to come after the addition of the event handler:
```
var $table = $('table.demo2');
$table.on("floatThead", function(e, isFloated, $floatContainer){
    if(isFloated){
        $floatContainer.addClass("floated"); // the div containing the table containing the thead
        $(this).addClass("floated"); // $table
    } else {
        $floatContainer.removeClass("floated");
        $(this).removeClass("floated");
    }
});
$table.floatThead(...);
```

**Comment by rinogo** [comment]
@mkoryak - Here are some changes for the docs.  Thanks for the great plugin! :)

**Comment by mkoryak** [comment]
well, you can still submit a PR, check out the `gh-pages` branch, the docs are all there :)

and you are welcome
