### ISSUE TITLE
scrollContainer with other content inside wrapper, header won't scroll out

### ISSUE THREAD

**Issue by outiniemela** [mkoryak/floatThead#303]
fiddle: https://jsfiddle.net/g7ngf17n/ 
(base taken from the inner scroll-example, added just some br's in the same inner wrapper where the table is in)

Our layout is basically made by a body, and an inner div (that's scrollable), where the page's actual contents are in. outside this "inner content div" theres menus and other stuff.

The inner div that has a table with floatthead, but also other contents. Problem is, the header won't go away after the table is finished like the way if the table was outside the inner div

chrome 49, windows 7, jquery 2.2.1, floatThead 1.4.0

**Comment by mkoryak** [comment]
this is a bug, for now you can use this workaround:
```
$table.floatThead({scrolllContainer: function($table){ return $table.closest('.wrapper'); }});
```

**Comment by outiniemela** [comment]
Tried updating the fiddle with the workaround but it doesn't help (also tried bowering the 339699f -commit to the actual project but didn't help either)

**Comment by mkoryak** [comment]
i see, i fixed another issue i saw there.

**Comment by mkoryak** [comment]
here is a workaround that might be better than nothing until i fix this bug:

https://jsfiddle.net/g7ngf17n/2/

**Comment by outiniemela** [comment]
the workaround seems to be working (although using top-attribute with position:fixed and scrollContainer seems not to work), thank you :)

**Comment by mkoryak** [comment]
top attribute?

**Comment by outiniemela** [comment]
sorry, seems i was vague - meant top: 20 for instance ("Offset from the top of the window where the floating header will 'stick' when scrolling down")

$('table').floatThead({
    scrollContainer: true,
    position: 'fixed'
    top: 120
  });

**Comment by mkoryak** [comment]
right, `top` doesnt work with overflow scrolling because it doesnt make any sense to have the header be anywhere but at the very top, because otherwise you will see the table scrolling _above_ the header.

**Comment by mkoryak** [comment]
synopsis: 
this happens when `position: 'absolute'` but does not happen when `position:fixed`
