### ISSUE TITLE
IE 11 misalignment issue v1.2.12 (Would like to try v1.4, where is it?)

### ISSUE THREAD

**Issue by deanpeterson** [mkoryak/floatThead#306]
Everything works fine on every other browser.  

![floatthead](https://cloud.githubusercontent.com/assets/1156788/15189755/1d541e2c-1772-11e6-8fe4-01a66a3cd38e.png)

**Comment by deanpeterson** [comment]
Nevermind, even though I don't see the tag, bower still seems to pull the 1.4 version if I ask for it explicitly.

**Comment by mkoryak** [comment]
does this apply?

http://mkoryak.github.io/floatThead/examples/row-groups/

**Comment by deanpeterson** [comment]
Unfortunately that did not seem to fix the problem. :(

**Comment by mkoryak** [comment]
Ok, I need a jsfiddle reproducing the issue if you are looking for a solution

**Comment by deanpeterson** [comment]
For some reason jfiddle is stripping the columns but i think this might give you something to work with:
https://jsfiddle.net/qf9ax83q/51/

On IE 11, the header overlaps the checkboxes

**Comment by mkoryak** [comment]
Sorry, 
I don't have time to debug an angular app. Can you reproduce this without angular?

**Comment by mkoryak** [comment]
I just looked a bit, you have invalid html there. your tbody does not have any `td` or `tr` elements and is filled with checkboxes :P

this plugin requires valid html to work.

**Comment by deanpeterson** [comment]
I do mention above that jsfiddle is stripping those out.  I inject the td's and tr's correctly.  It's the best I could do with jsfiddle.  It still does the same thing when the td's and tr's are there (the header overlaps the content of the tbody).

**Comment by mkoryak** [comment]
Can you try getting the table html that angular renders for you (but without floatThead running), take that, paste it into jsfiddle and run floatThead on THAT. that will remove the need for angular and make the whole thing much easier for me to work with

**Comment by mkoryak** [comment]
no response, closing. will reopen if you can make a fiddle without angular

**Comment by fengshics** [comment]
I spent a whole day working on this issue and finally I got the solution. I did not specify the width of my original table while the table uses "table-layout:fixed". I found that I must specify the width of the table in order to let the IE(or other browsers) respect the column widths. So I added a css style to my original table as "width:100%" and then it works perfectly on every browsers!
