### ISSUE TITLE
addClass when thead starts to float?

### ISSUE THREAD

**Issue by andiszek** [mkoryak/floatThead#308]
Hello,
great jQuery plugin! Thank you for developing it!

Would you please consider adding an extra class to _.floatThead-container_ when the _thead_ starts floating? and removing it when the user scrolls back to the top of the table?

Thank you in advance!
andi

**Comment by mkoryak** [comment]
Is the event I expose when this happen not sufficient to implement this?

**Comment by andiszek** [comment]
Hello,
sorry for the late reply!

the problem is the following:

i`m using the script to float the Post Overview table header in Wordpress - see screenshot 1:
[https://dl.dropboxusercontent.com/u/857986/screenshot-1.png]
Due to the top WordPress Toolbar, i have to add a margin-top:31px; to the .floatThead-container (so it doesnt get covered by the WP Toolbar).

But when i scroll back up, and the thead is not floated, the margin-top is still active, and it gets in the way. see screenshot 2:
[https://dl.dropboxusercontent.com/u/857986/screenshot-2.png]

It would be great to have a class that add to .floatThead-container only when it floats, so i can add the margin-top only to the floated header.

i have "fixed" the issue temporarily by adding a scroll function: if i scroll down more than 320px, a class gets added to .floatThead-container - but this is not a perfect solution, depending on monitor size, etc.

Thank you & best regards!
andi

**Comment by mkoryak** [comment]
have you tried using the `top` option? 

this is straight from the first page of the docs:
```js
var $table = $('table.demo2');
$table.on("floatThead", function(e, isFloated, $floatContainer){
    if(isFloated){
        $floatContainer.addClass("floated"); // the div containing the table containing the thead
        $(this).addClass("floated"); // $table
    } else {
        $floatContainer.removeClass("floated");
        $(this).removeClass("floated");
    }
});
$table.floatThead(...);
```

**Comment by andiszek** [comment]
i think i have overlooked this:( sorry!

I'll take a look.

thank you!

**Comment by Neill83** [comment]
Hi @mkoryak,

there is no way to know when the table header has started floating and when it has stopped floating?

I tried your example above but it works only once and then not again.

Greetings
