### ISSUE TITLE
getOffsetWidth returns 0

### ISSUE THREAD

**Issue by sggcouronne** [mkoryak/floatThead#309]
IE 11
Windows 10
jQuery 2.1.4
floatThead : 1.4.1
jsfiddle : https://jsfiddle.net/sggcouronne/ke3wynh9/1/

When floatThead used with two tr inside thead, there is a bug for IE11 in Windows 10. It seems that function getOffsetWidth returns 0 (el.getBoundingClientRect() as only parameters 0 (width, etc.)). So col inside colgroup will have a width of 0.

I proposed this fix: 
inside function reflow(), after var widths =[];
```
if(ieVersion) {
                var $rowCellsTable = $table.find('tbody tr:first td');
                for(i=0; i < numCols; i++){
                  widths[i] = getOffsetWidth($rowCellsTable.get(i));
                }
            } else {
                for(i=0; i < numCols; i++){
                  widths[i] = getOffsetWidth($rowCells.get(i));
                }
            }
```
instead of just 
```
for(i=0; i < numCols; i++){
                  widths[i] = getOffsetWidth($rowCells.get(i));
                }
```

**Comment by mkoryak** [comment]
I have already thought of that, trace through the code for how $rowCells are created and you will see they come from a function called `getSizingRow` which is overridable via the plugin options. 

so instead of this fix, try creating the plugin like this:
```js
$table.floatThead({
  getSizingRow: function($table) {
    return $table.find('tbody tr:first td');
  }
});
```

also see docs about using this option
