### ISSUE TITLE
Scroll-container with overflow: auto: floating header overlaps scrollbar

### ISSUE THREAD

**Issue by janvanderhaegen** [mkoryak/floatThead#310]
Steps to reproduce:
- have a scroll-container with overflow: auto
- have two table rows in the table (overflow:auto = no scroll-bar)
- activate the plugin
- add rows to the table dynamically until the scroll-bar appears

[Try the fiddle](https://jsfiddle.net/notapedp/)

Expected result: 
- THead should resize along with viewport of scroll-container

Actual result:
- THead stays overlaps the scrollbar

**Comment by mkoryak** [comment]
Thanks for taking the time in creating the issue.

The solution is to notify the plugin about the dom changes by triggering the `reflow` event on the table after adding the rows. see:

https://jsfiddle.net/notapedp/1/
