### ISSUE TITLE
FloatHeader with column width Zero

### ISSUE THREAD

**Issue by ksgsharma** [mkoryak/floatThead#311]
When I set col width to 0% and hide all corresponding TH and TDs then floatheader is not getting applied. Please find the JSfiddle below. Could you please help me out asap, this is a prod issue for me.

https://jsfiddle.net/p6SRV/168/

- IE / 10
- Windows 7
- jQuery 2.1.4
- floatThead version 1.4.0

Thank you
Sarma K

**Comment by mkoryak** [comment]
I assume it works fine on other browsers?  Have you tested it?

Why are you using colgroup?  does this issue happen if you remove entire colgroup tag? If so, can you move the widths to the TH tags?

**Comment by ksgsharma** [comment]
Thanks for the reply,
We are implementing a project for the state and there are some strict guidelines. One of which is use of IE 10. But the jsfiddle which I provided does not work in Chrome / Firefox too. The grid design is a custom built using which we moved over 125 screens to production. So changing the grid design at this point is also not that feasible.

Could you please check the JSFIDDLE one more time as it does not work even in Chrome or FF.

Thanks You
Sarma K

**Comment by mkoryak** [comment]
it works fine, the container just didnt have a height, so it didnt scroll.

https://jsfiddle.net/p6SRV/170/

if you want to do window scrolling then dont specify the container:
https://jsfiddle.net/p6SRV/171/

**Comment by ksgsharma** [comment]
Thank you so much for the reply, Let me implement this in my project and I will get back to you with the result. Once again many thanks for timely reply.

**Comment by ksgsharma** [comment]
Hi,
I tried your suggestion but it did not work. Seems like I m doing something wrong. I have attached files with HTML code in them. Could you please take a look.

1. With **no hidden column** in the grid, float header is forming the DIV as attached in **NoHiddenCol.txt** file. 
[NoHiddenCol.txt](https://github.com/mkoryak/floatThead/files/340400/NoHiddenCol.txt)

2. With hidden column float header is forming the DIV as attached in **WithHiddenCol.txt**. 
[WithHiddenCol.txt](https://github.com/mkoryak/floatThead/files/340401/WithHiddenCol.txt)

3. Also please find attached Full Grid Code with hidden column and float header attached (**FullGridHtmlWithHiddenCol.txt**).
[FullGridHtmlWithHiddenCol.txt](https://github.com/mkoryak/floatThead/files/340413/FullGridHtmlWithHiddenCol.txt)



**Thanks once again for your amazing support.**

**Comment by mkoryak** [comment]
Sorry, but this is not how this works. I will provide support with a jsfiddle that reproduces the issue.
If you cannot reproduce your issue on jsfiddle, then you probably dont know what your issue is, and therefor neither you or I can solve it.

**Comment by ksgsharma** [comment]
Hi, Thanks for suggesting the process of debugging. I followed your process and created below JS Fiddle. The issue I found was in IE 10 when TD element has style "display none" then float header is not calculating the colgroup widths at all. But if I remove the "display none" style, it does. **Again this happens only in IE 10.**

https://jsfiddle.net/p6SRV/184/

Could you please run this JSFIDDLE in IE10 and use developer tools to check the formed HTML.

For your convenience I have added the sample HTML file also. You could run it directly in IE10.

[FloatHeader_Sample.zip](https://github.com/mkoryak/floatThead/files/342564/FloatHeader_Sample.zip)

Thanks
Sarma K

**Comment by mkoryak** [comment]
I havent had time to fire up my IE10 VM, but how about something like this:

https://jsfiddle.net/p6SRV/185/

**Comment by ksgsharma** [comment]
Sorry for the delayed reply. It was July 4th long weekend and could not respond. Tested your solution  and **works like charm**. Thanks so much for your amazing support !!
