### ISSUE TITLE
First row behind thead

### ISSUE THREAD

**Issue by piscitelli91** [mkoryak/floatThead#312]
Hi I have an issue. With IE the first row of the  body appears behind the fixed thead. Inspecting the code I notice that with Chrome there is a thead that in IE doens't appear. Why?

**Comment by mkoryak** [comment]
Likely you have invalid html that chrome gives you a pass on, but ie barfs.

How is your code different from examples on the docsite?

**Comment by mkoryak** [comment]
please reopen after you rewrite your issue so that it follows the issue template
