### ISSUE TITLE
afterPrint() is not getting called

### ISSUE THREAD

**Issue by simplestep** [mkoryak/floatThead#313]
Thank you so much for this plugin. It saved lot of time for pinning header.  

One issue I saw is that I tried to print table in Chrome, "beforePrint" event called and once I closed the print dialog, afterPrint event is not getting called.  and **Lost the functionality of the header**.
https://github.com/mkoryak/floatThead/blob/master/dist/jquery.floatThead.js#L889

After more debugging, found the issue that isPrintEvent is undefined and below lines of code setting "empty" function to before and after print.
https://github.com/mkoryak/floatThead/blob/master/dist/jquery.floatThead.js#L993-L996

1. Below line of code is calling destory on table and passing [true]
https://github.com/mkoryak/floatThead/blob/master/dist/jquery.floatThead.js#L879

2. and destroy is below line is getting undefined for isPrintEvent arugument
https://github.com/mkoryak/floatThead/blob/master/dist/jquery.floatThead.js#L959

**As a workaround**, in our code, I have added the print listener code and re-initialize the header in after print method.

**Comment by mkoryak** [comment]
Browser?

**Comment by mkoryak** [comment]
thanks for debugging it. I will look into this after the holidays here

**Comment by mkoryak** [comment]
thanks for the bug report. I was confusing the destroy plugin method with an event handler, which it is not.

**Comment by simplestep** [comment]
Thank you so much for fixing it. Any plans for releasing it soon?

**Comment by mkoryak** [comment]
not really, this is the first commit to master since last release. perhaps if you buy me a beer, I will ;)

**Comment by mkoryak** [comment]
i released a new version

**Comment by simplestep** [comment]
Wow, thank you so much, much appreciated.
