### ISSUE TITLE
Bad Reflow after jquery show/hide

### ISSUE THREAD

**Issue by mjarrison** [mkoryak/floatThead#314]
JSFiddle: https://jsfiddle.net/hw6sczz5/2/

Upon clicking the open or close button for my unrelated header div, the thead does not reflow to the correct position even when specifically calling reflow at the conclusion of the jquery.show or jquery.hide.

Browser: Chrome 51 and others
OS: Win10
JQuery, floatThead: latest

**Comment by mkoryak** [comment]
you put the reflow in the wrong async callback.

https://jsfiddle.net/hw6sczz5/3/

a better solution though is to use the `absolute` position option and skip all the callbacks:

https://jsfiddle.net/hw6sczz5/4/
