### ISSUE TITLE
IE9 issue: SCRIPT438: Object doesn't support property or method 'addListener'

### ISSUE THREAD

**Issue by claudchan** [mkoryak/floatThead#316]
Hi,
There is an error occur on IE9.
`SCRIPT438: Object doesn't support property or method 'addListener'`

- IE9
- Windows 7

I temporary remove this line (below) and it works fine:
`window.matchMedia("print").addListener(printEvent);`

Possible you could enhance the code to make IE9 run?

**Comment by mkoryak** [comment]
fixed on master
