### ISSUE TITLE
floatThead in combination with UpdatePanel

### ISSUE THREAD

**Issue by infor01** [mkoryak/floatThead#319]
Hi

First of all I would like to thank you for this great component. I have been using it for a number of cases I had and it works like a charm in all projects, expect the one I am working on now.

This is a project where there is an updatepanel to produce callbacks (not postbacks) to refresh part of the screen, the part where a table is used (actually a gridview, but that translates into a table). I can get the header to lock, as it is supposed to, when loading the page for the first time, but when I click a button in the updatepanel, the header is not locked anymore.
This makes senses, since the jQuery document ready function is not triggered in this case and the content of the updatepanel is overwritten.

So I have included the following piece of code in my page (to handle the callback):

```js
var xPos, yPos;
var prm = Sys.WebForms.PageRequestManager.getInstance();

function BeginRequestHandler(sender, args) {
            xPos = $("#divOperational").scrollLeft();
            yPos = $("#divOperational").scrollTop();
}

function EndRequestHandler(sender, args) {
            $("#divOperational").scrollLeft(xPos);
            $("#divOperational").scrollTop(yPos);

            HandleFixedHeader();
 }

 prm.add_beginRequest(BeginRequestHandler);
 prm.add_endRequest(EndRequestHandler);

 function HandleFixedHeader() {
            $("#gvOperational").floatThead({
                scrollContainer: function ($table) {
                    return $table.closest(".fixheaderwrapper");
                }
            });
 }
```
I initially used the Sys.WebForms.PageRequestManager to handle a scroll back to the position the screen was in (as you see in the code) but after adding the HandleFixedHeader function to the EndRequestHandler function, the UpdateProgress of the UpdatePanel stays.
So I guess your component doesn't finish handling the call (because any code after the HandleFixedHeader won't fire). If I debug in your script, I see that the execution indeed gets stuck.

Can you please check and provide a workaround?

**Comment by mkoryak** [comment]
I dont do .Net, so the terminology means nothing to me. 

That being said, have you seen the docs about triggering the `reflow` event. It sounds like you need to do this after your callback happens.

`$table.trigger("reflow");`

there are extensive docs and examples of it

**Comment by mkoryak** [comment]
ok, i formatted your code, and now I see. 

I think the solution is to replace the `HandleFixedHeader` function with:

```js
function HandleFixedHeader() {
            $("#gvOperational").trigger('reflow');
}
```

**Comment by infor01** [comment]
I tried using the reflow, but this doesn't work.

What the UpdatePanel does, is an Ajax callback, a partial refresh of all HTML within the panel. So the initial  $("#gvOperational").floatThead call gets lost. I have to redo this part.

I see that when I use the code as I provided it, it does work, but the callback never seems to finish (in order words, it's like the loading of the page never reaches the final part)

**Comment by mkoryak** [comment]
in that case, you should probably destroy the plugin before making the request:

```js
function BeginRequestHandler(sender, args) {
            xPos = $("#divOperational").scrollLeft();
            yPos = $("#divOperational").scrollTop();
             $("#gvOperational").floatThead('destroy');
}
```

**Comment by infor01** [comment]
This doesn't solve it unfortunately.

I had to fix it quite fast, so I made a workaround, so this no issue for me now, but maybe someone else could experience this too.

I am available if you care to look into this further.

**Comment by mkoryak** [comment]
Sorry, I don't know how .Net does it's frontend things, so I am not able to help you.

Out of curiosity, what was the hacky fix?
