### ISSUE TITLE
Populating the extra cloned thead

### ISSUE THREAD

**Issue by LamaBimal** [mkoryak/floatThead#320]
Hello #@mkoryak, i am using jquery.floatThead for the fix header. In my scenario , there is a table enclosed by the loop , how could i handle it.

**Comment by mkoryak** [comment]
the thead is not cloned by the plugin.

I don't understand what you mean by "there is a table enclosed by the loop".

perhaps you should follow the issue template and provide the information I require

**Comment by LamaBimal** [comment]
I am using the same table in the repetation way with different data and the floatThead is not working.

**Comment by mkoryak** [comment]
Jsfiddle please.

**Comment by mkoryak** [comment]
this might be related:

https://github.com/mkoryak/floatThead/issues/303

please search past issues

**Comment by mkoryak** [comment]
any updates?

**Comment by LamaBimal** [comment]
table must have an id through which we could select the table for scrollingn. But i have dynamic table and id of table are also dynamically setup and js files run before than the template generates. so, in my case i didnot use it.

**Comment by mkoryak** [comment]
No response. Closing
