### ISSUE TITLE
Commercial usage of FloatThead

### ISSUE THREAD

**Issue by iArnoldo** [mkoryak/floatThead#322]
Dear Mr Koryak,

I have a question concerning the license of your JQuery plugin FloatThead.

I would like to use this plugin in my commercial product and in the terms of usage it states that I"must give appropriate credit".
Would it be appropriate to share the link in a kind of external ressources list and not on the page that actually uses the plugin?

Kind regards

Arnold Brestel

**Comment by mkoryak** [comment]
Yes. That we is fine. Thank you for asking.
