### ISSUE TITLE
Can not reproduce demo

### ISSUE THREAD

**Issue by sona1111** [mkoryak/floatThead#326]
Hello, 

I feel a little silly posting this but I really can not figure out what I am doing wrong. I am trying to set up a simple example such as what you have on the project homepage. I have a fiddle here: https://jsfiddle.net/4zwhwfyy/5/

The header does not scroll. I have tried asking around IRC and trying many combinations of options but I would think something this simple should not need this effort. In the likely possibility that it is something simple and stupid, at least you get another free issue closed. :)

Thanks for taking a look.

**Comment by mkoryak** [comment]
you dont have enough stuff in the table to scroll. how about this:

https://jsfiddle.net/4zwhwfyy/6/

**Comment by sona1111** [comment]
Unfortunately this is what the fiddle looks like for me, which you have linked. My OS is ubuntu linkx 14.04 LTS , Browser is google chrome 48

![out2](https://cloud.githubusercontent.com/assets/4585193/18774264/58acb318-8125-11e6-80c4-0bbf416c849b.gif)

**Comment by mkoryak** [comment]
Fortunately I can reproduce on my phone, but it's 1am

**Comment by mkoryak** [comment]
where did you copy the lib code from? Its not correct. Specifically the line 

`var $floatContainer = $('<div>').css('overflow', '').attr('aria-hidden', 'true');` 

should be

`var $floatContainer = $('<div>').css('overflow', 'hidden').attr('aria-hidden', 'true');`

**Comment by mkoryak** [comment]
it works much better if you use the code from github:

https://jsfiddle.net/4zwhwfyy/7/

**Comment by sona1111** [comment]
Well, I can't complain! I cant imagine how that specific line was changed, but using the hosted source has fixed the problem. I greatly appreciate your time, even though I see it could have been avoided entirely.

Have a great weekend.
