### ISSUE TITLE
After Chrome's print dialog shows, reflowed event listener is detached from the table

### ISSUE THREAD

**Issue by DannyJJK** [mkoryak/floatThead#327]
Browser: Chrome
OS: macOS Sierra

Steps to reproduce:
1. Create table and apply floatThead to it
2. Assign an event listener for the reflowed event
3. View the page in Google Chrome. Currently the reflowed event works. Now if you open the print dialog, and close it with the cancel button, you'll notice that the **reflowed event no longer fires**. Viewing in the browser's dev tools it seems that the reflowed event still exists but the listener for the event becomes unbound from the table. Rebinding the event solves the issue.

https://jsfiddle.net/jstfgjan/

On this JSfiddle I have created a button which reflows the table and has a "reflowed" listener which creates an alert dialog. After opening Chrome's print dialog and then closing it, the button now does nothing

**Comment by mkoryak** [comment]
I understand why this would happen. thanks for the report

**Comment by mkoryak** [comment]
I dont know why I was destroying the table on print. All I needed to do was unfloat the header and refloat it afterwards. I had all the secret sauce but didnt use it.

This should make printing much less magical
