### ISSUE TITLE
Set col width after destroy and rebuild

### ISSUE THREAD

**Issue by Phil795** [mkoryak/floatThead#330]
Hello,

I have a application with a dynamic table layout configurator.

The user can select between 70-Columns to display on the mainpage.

After selecting some columns I use a simple function to rebuild the floatThead.

INFO: The available columns has a predefined width, the table width is bigger than the window width!

Example Columns:
Datetime      | width:180px
Value            | width:400px
Owner          | width:22px
Created_at    | width:180px
Updated_at   | width:180px

The problem is the column width attribute.
If I set it to the <th> element, it has no effect.

Here is a [fiddle ](https://jsfiddle.net/erdjcmdj/) with the problem. 

First I set the thead static. 
In the next step I want to set the thead by the given array of 3 columns.

The width of the 3 columns is set to "4000" for testing. But the colgroup resize this with (maxWidth / countColumns).
Is there a way to set the width dynamically?

- browser: Chrome 53.0.2785.116 x64
- OS name: Windows 10
- jQuery version: v3.1.0
- floatThead version: 1.4.3 
(jQuery and floatThead are different versions in my project, than in the fiddle, but the effect is the same)

**Comment by mkoryak** [comment]
the width attribute is deprecated. use a style attribute.

Can you provide a fiddle where the set widths are respected **without** floatThead running? I couldnt get it to work:

https://fiddle.jshell.net/erdjcmdj/3/show/light/

**Comment by Phil795** [comment]
Hi @mkoryak 

Thanks for the fast answer.
I changed my `<th width="X">` to `<th style="min-width:200px;max-width:200px;">` and now it works in my application.

You can close this questing. Works great.

Thanks for this magic lib!
