### ISSUE TITLE
jQuery is not defined when using with browserify

### ISSUE THREAD

**Issue by beeb** [mkoryak/floatThead#331]
I tried using the npm package inside my project that uses browserify and babelify and the script complains that jQuery is not defined, even though it IS imported and both defined as `const jQuery` in the file where floatThead is used, and in the `window` scope as `window.jQuery` and `window.$` (required for bootstrap)

I tried with `import 'floatthead'` and `require('floatthead')` but in both cases, the script complains that jQuery is not defined. Why not make a proper module?

**Comment by mkoryak** [comment]
Why not indeed. Submit a pr

**Comment by beeb** [comment]
I don't have time to edit your script mate, I'm just saying that if you are publishing it via `npm`, people are expecting it to work as a module.

**Comment by mkoryak** [comment]
Its free software. It comes with no guarantees of doing anything

On Oct 13, 2016 9:33 AM, "Valentin Bersier" <notifications@github.com>
wrote:

I don't have time to edit your script mate, I'm just saying that if you are
publishing it via npm, people are expecting it to work as a module.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mkoryak/floatThead/issues/331#issuecomment-253514148>,
or mute the thread

**Comment by beeb** [comment]
Ok but I'm still submitting a bug : the script won't work even though jQuery is defined in the window scope

**Comment by mkoryak** [comment]
Did you shim jQuery in browserify? If you did, it should work. It's not on
window. If it was on window it would work

**Comment by beeb** [comment]
Now that's helpful :) I didn't know about shim until now, gonna try

**Comment by beeb** [comment]
Confirming that it's working! For anyone wondering

In `package.json`

    "devDependencies": {
      "browserify": "^13.1.0",
      "browserify-shim": "^3.8.12",
      "grunt-browserify": "^5.0.0"
      /* ... */
    },
    "browser": {
      "jquery": "./node_modules/jquery/dist/jquery.min.js"
    },
    "browserify": {
      "transform": [
        "browserify-shim"
      ]
    },
    "browserify-shim": "./shims.js"

`shims.js`

    module.exports = {
      jquery: { exports: 'jQuery' }
    }

in `Gruntfile.js`

    browserify: {
      dist: {
        options: {
          browserifyOptions: {
            debug: true
          },
          transform: [
            'browserify-shim'
          ]
        },
        src: ['src/js/main.js'],
        dest: 'dist/js/app.js'
      }
    },

Not sure if it's needed in the gruntfile though, but it works like so.

**Comment by mkoryak** [comment]
this one is for you

https://github.com/mkoryak/floatThead/releases/tag/1.4.5

and I was having a shitty day

**Comment by mkoryak** [comment]
let me know if it works or not. I didnt test it ;)

**Comment by garrettr** [comment]
@mkoryak Unfortunately, 1.4.5 does not appear to resolve this issue. I still get `jquery.floatThead.js:1147 Uncaught ReferenceError: jQuery is not defined`.

Thanks for sharing the code regardless, it's very useful!

**Comment by beeb** [comment]
Same here, I tried various ways of loading jQuery before requiring floatThead but I get the `ReferenceError` too.

**Comment by mkoryak** [comment]
yeah but that sucks!

I know what the problem is. My underscore shim needs the commonjs stuff in it too. You can get around that problem by using the slim version, but then you will still need to shim underscore and change the `main` in package.json. 

I will fix it and update the release tag in place

**Comment by mkoryak** [comment]
im going to hold off on updating the tag. if one of you guys can test this (even by coping over your local lib in node modules with latest from dist) that would be good

**Comment by garrettr** [comment]
@mkoryak Re: https://github.com/mkoryak/floatThead/issues/331#issuecomment-256926719, I've tested the latest code on master and confirms that it fixes the issue - `const floatThead = require('floatthead');` works without requiring any workarounds for jQuery or Backbone.

**Comment by mkoryak** [comment]
I decided (because no time) that ill publish a new version when publishing a new version becomes required.

**Comment by 1antares1** [comment]
@beeb Thanks a lot, man!
Already works now!
