### ISSUE TITLE
Bootstrap regression in version 1.4.4?

### ISSUE THREAD

**Issue by dfcamara** [mkoryak/floatThead#335]
This is a copy of Bootstrap's "Fixed navbar" example with a table and floatThead version 1.4.2:
https://jsfiddle.net/dfcamara/z8cbyxf9/

In the same example with floatThead version 1.4.4, the header text is missing and the thead doesn't float:
https://jsfiddle.net/dfcamara/L1t0ws7e/

Tested with Firefox 49.0 running in Fedora Linux 24.

**Comment by mkoryak** [comment]
yep, looks like a bug. probably was introduced with the `translate` changes.

**Comment by mkoryak** [comment]
ill get this fixed this week. Running low on free time
