### ISSUE TITLE
Column widths get changed on continous maximize and restore of Browser Window

### ISSUE THREAD

**Issue by ksgsharma** [mkoryak/floatThead#336]
Hi,

First of all, thanks for this awesome utility.

We using the latest version of FloatHeader on IE 10. But this issue happens on Chrome also.
When keep maximize and restore browsers continuously after the FloatHeader is applied then widths of some of the columns in the grid gets reduced and some get increased. 

Could you please check this issue. This seems to happen only with Grids that have textboxes inside TD.
_(not to bother you but we are waiting on this issue for production migration)_

Here is the Jsfiddle for the Grid Design
[https://jsfiddle.net/zLu0jhe1/]

- IE/10 (happens in Chrome also)
- Windows 7
- jQuery v2.1.4
- using floatThead version latest

Thank you once again !!

**Comment by mkoryak** [comment]
I haven't had a chance to look, but I suggest you try the latest 1.3 version while you wait for me

**Comment by mkoryak** [comment]
your jsfiddle did not include any javascript so i couldnt run it.

i made a jsfiddle that i **could** run here:
https://jsfiddle.net/4zwhwfyy/8/

I cant reproduce your issue. Please update your fiddle to include javascript code and any relevant css.

**Comment by ksgsharma** [comment]
Thanks so much !! 

I was able to fix this issue by adding padding to those column headers (TH) that were shrinking in width during maximize and restore.

/* To fix the column width so that on maximize and restore widths do not change*/
    #thId_Case_1 {
        padding: 0 1em 0 1em !important;
        white-space: nowrap;
    }

    #thDt_Installment {
        padding: 0 2em 0 2em !important;
    }

**Comment by mkoryak** [comment]
great
