### ISSUE TITLE
(angularjs) Column headers snap to offset position when switching between bootstrap.ui tabs

### ISSUE THREAD

**Issue by maxhap** [mkoryak/floatThead#337]
Dear,

When I use your plugin inside bootstrap.ui tabs (hybrid mode) the column headers get offset by the scrolled position when switching between tabs.

To reproduce 

1. Add table into a tab
2. Scroll  till heards become fixed
3. Switch tab
4. Scroll in second tab
5. Switch back to first tab
6. Table headers will be offset by scrolled amount

Please see my fiddler  for a simple example with detailed instructions
[https://jsfiddle.net/maxhap/Luhx29cf/](url)

Browser Chrome Firefox IE (latest versions)

Any help solving this would be mostly appreciated and deserve a donation :D. This plugin is now used on many of my none tabed tables but would be fantastic if I could get this working.

Kind Regards
Max

**Comment by mkoryak** [comment]
This plugin supports bootstrap but not ui-bootstrap, but the fix is to trigger reflow on the table who's tab you are switching to. 

I also saw another bug where the header was not being positioned correctly on init (i will look at this separately). Luckily for you there is a quick workaround - you need to trigger a reflow on the table post init.  

Both of these fixes are here:

https://jsfiddle.net/Luhx29cf/1/

Thanks for a good issue report.

**Comment by maxhap** [comment]
I thought you would say ui.bootstrapper isn't supported, it's so close to fully working too :D.

Looking at your fiddle update I see your fix almost worked. I did noticed that the the headers still flicker from their offset position back to the correct position. I extended the tab selection detection to remove the fixed headers from all none selected tabed tables, and then add fixed headers to the current table. With this amendment it works near perfect. 

[https://jsfiddle.net/maxhap/Luhx29cf/3/](url)

I will put this into my real project (implemented a little cleaner) and see how it works on a much larger scale.
 
Thanks for the fast response, owe you a beer!

**Comment by mkoryak** [comment]
i noticed that uib-tabs also take an `unselect` (look at the docs, i might be wrong on the name).  You might be able to use that to destroy the plugin, or maybe try moving my reflow logic in there. The table has to be visible in order for reflow to work correctly, so it might not work - something you can play with

**Comment by mkoryak** [comment]
actually, you dont need to do any of that. try this:

https://jsfiddle.net/Luhx29cf/4/
