### ISSUE TITLE
Question - vertical scroll bar within body only?

### ISSUE THREAD

**Issue by itslittlejohn** [mkoryak/floatThead#339]
Hi. I appreciate all your work on this project. I have read the docs and like the way the inner scrolling works, but I'd ideally like to have it work like this: https://jsfiddle.net/hashem/CrSpu/554/

Basically, the vertical scroll bar is inside the body, not outside. This would allow me to put a button in the last `th` to 'toggle' the scrolling. It doesn't seem like it's currently possible, but do you know if it's possible to adapt what you've done (along with all the nice responsive stuff) to layout like this?

Thanks!

**Comment by mkoryak** [comment]
What have you tried that didnt work with this plugin?
Right now I dont have the time to solve this for you, but I am happy to look at code you tried that did not work.

**Comment by mkoryak** [comment]
I misunderstood your question. You want the scrollbar inside the tbody tag. That is not possible with this plugin
