### ISSUE TITLE
Sorting not working Intergrate with datatable

### ISSUE THREAD

**Issue by bokuyami21** [mkoryak/floatThead#340]
I m sorry for my bad english. But I have following issue.
My sorting not working when intergrate with datatable.
It's work well after initation, but when i resized window then it became to not good (just only in Edge Windows 10). the same state when i tried sample on homepage (http://mkoryak.github.io/floatThead/datatables/).

**Comment by mkoryak** [comment]
and it works fine in Chrome and firefox on windows 10?

This will take me a while to reproduce - I currently do not have windows 10 / edge. 


you can try the follow code which may fix the issue for you:

```js
$(function(){
   var $table = $(.... your table selector ...);
   $(window).on('resize', function(){ $table.triggerHandler('reflow'); });
});
```

**Comment by bokuyami21** [comment]
Thanks for reply soon.
It works fine on Chome and IE11 on Windows 10. But not works in Edge.
I put your code in my source but it cant resolve.
Actually, if use $table.trigger('reflow'); then the same error still occurs.
Thanks for  supporting.

**Comment by bokuyami21** [comment]
I think The click event on thead was lost when reflow, but i dont know how to fix it.
Thanks

**Comment by mkoryak** [comment]
i remember this. I think there was a reason for using prepend vs append - i need to look into this more. this change could break a lot of other browsers

**Comment by bokuyami21** [comment]
Yes, maybe break a lot of other browsers, i think too.
Thanks for replying and i m waiting for new version.

**Comment by mkoryak** [comment]
sorry, highly unlikely that i am going to work on this unless more people have this issue. I will accept a PR that was tested on all browsers if you have a fix like that on hand.
