### ISSUE TITLE
Invalid for fadeIn/fadeOut row and column

### ISSUE THREAD

**Issue by hopesai** [mkoryak/floatThead#341]
Hi,

I used floatThead and fadeIn/fadeOut row and column
1. If there is border of table, and one column is hide by default, the border scope is invalid
2.
    A. Click "SHOW TR" to show all row
    B. Scroll to the bottom of page
    C. Click "SHOW TD" to show all column
    D. THead does not show all column

Example: [jsfiddle](https://jsfiddle.net/wtfexeyj/8/)

- Chrome 54.0/ IE 11
- Windows 7
- jQuery 1.9.1 on fiddle / jQuery 1.12.4 on my PC

**Comment by mkoryak** [comment]
didnt notice you closed it. read the docs, and:
https://jsfiddle.net/wtfexeyj/9/
