### ISSUE TITLE
Bootstrap dropdown menu in header not visible 

### ISSUE THREAD

**Issue by Fraer** [mkoryak/floatThead#342]
The dropdown menu inside a table header is not visible, it looks like it's container is floating header and not the initial table, changing the z-index does nothing.

https://jsfiddle.net/8qr65o64/

- Chrome v 54.0.2840.98
- Macosx el capitan

**Comment by mkoryak** [comment]
this is required to make certain really bad things which happen sometimes from happening, you dont need it but need some css:

https://jsfiddle.net/8qr65o64/7/

**Comment by Fraer** [comment]
it does not work in your jsfiddle, the menu looks still hidden in the container, i don't get, why you closed the issue ?

![screenshot-jsfiddle net-2016-12-06-16-26-44](https://cloud.githubusercontent.com/assets/976420/20931254/d049b28c-bbd0-11e6-9d28-8fb3dc231029.png)

**Comment by mkoryak** [comment]
i closed it because i thought i had it fixed, but i must have pasted the wrong link. try this:

https://jsfiddle.net/8qr65o64/9/

**Comment by mkoryak** [comment]
does that solve it for you?

**Comment by Fraer** [comment]
Yes perfect! Thank you!
