### ISSUE TITLE
Unable to fix table header when using in page with mutilple dynamic table

### ISSUE THREAD

**Issue by som123** [mkoryak/floatThead#343]
I have page which has multiple table loaded on ajax, I won't able to fix the header of those tables (not working single table also ), Please let me know is there any other way to initialize it.

- browser name/version : Chrome Version 54.0.2840.99 m (64-bit)
- OS name : Windows 7
- jQuery version if not latest : jquery-1.8.1.min.js?v=14.8
- floatThead version if not latest : jquery.floatThead.min.js?v=14.8

https://jsfiddle.net/n6vqmdkn/

**Comment by mkoryak** [comment]
You are missing the thead and tbody tags from your table html. You need to
have those for the script to work

**Comment by mkoryak** [comment]
i assume this is closed now. let me know if you have any more issues
