### ISSUE TITLE
jquery.floatThead for Handsontable

### ISSUE THREAD

**Issue by Narayanan12345** [mkoryak/floatThead#344]
Hi Team,

Please let me know, Do you have any sample example for Handsontable ?

Handsontable render the 3 headers(htmaster,ht_clone_top,ht_clone_left) in run time. I am not sure how to implement jquery.floatThead for Handsontable similar to DataTable Plugin.

jquery.floatThead Overflow scrolling is not fit for Handsontable? Can you please check

Thanks,
P.Narayanan

**Comment by mkoryak** [comment]
Sorry, but I have never heard of or used handsontable. I don't have time to check. If you make a jsfiddle and include things from the issue template, I might be able to tell if it will work or not

**Comment by Narayanan12345** [comment]
Hi,
Thanks for your reply
I have created the jsFiddle for above issue.   http://jsfiddle.net/s6t768pq/449/ 
I am using window scrolling (position: 'absolute') in floatThead but when i use vertical scroll bar Up/Down, am facing flickering issues in table header.
Can you please check in IE browser ?
Thanks,
P.Narayanan

**Comment by mkoryak** [comment]
an important requirement of a jsfiddle is that it produce something i can look at. A table that i can see, and reproduce your issue. This is not happening here, this is just some random code. 

If you are interested in consulting, my rate is $100/hr minimum 2 hours

**Comment by mkoryak** [comment]
I looked some more, and the table was there, just hidden for some reason with css. It looks like handsontable already provides something for floating the header, as its header is broken apart from the table in the dom.

In order for me to help you I would need a lot more investment from you here. It feels more like 'I dont know what is going on, can you fix it?' I dont have time for that.
