### ISSUE TITLE
Errors in position if window is resized

### ISSUE THREAD

**Issue by nonameworks** [mkoryak/floatThead#345]
- After $table.floatThead(); is called if the table is resized the head does not line up with the content.
- Open this fiddle 
https://jsfiddle.net/syLn9xve/

Scroll down the result window, restore the browser window and resize. Maximize browser window.

Chrome 55, Windows 7

**Comment by mkoryak** [comment]
yep something weird is going on

**Comment by AvogadroSG1** [comment]
Working with ASP.NET 4.2 updated to newest JQuery from NuGet 3.1.1

Updating to the newest JQuery seemed to have caused this issue.

Tried to do:
                function reflow() {
                    $("#<%=lv.ClientID%>").floatThead( 'reflow');
                };
                var resizeTimer;
                $(window).resize(function () {
                    clearTimeout(resizeTimer);
                    resizeTimer = setTimeout(reflow, 100);
                });

All functions call correctly, but no re positioning occurs.  Headers stay where they were originally.

**Comment by mkoryak** [comment]
I see no errors in the above code, but you will have to create a jsfiddle if you want me to action it.

**Comment by mkoryak** [comment]
@AvogadroSG1 is this related to this issue? if not, create a new issue and add a jsfiddle

**Comment by mkoryak** [comment]
@nonameworks sorry i took forever to respond, but there is no new bugs here. you needed to specify `scrollContainer` because you use a wrapper div. 

headers sticking around after scrolling under the table is indeed a bug, tracked here: #303 
there is a workaround, which is to use `position: 'fixed`

fixed fiddle:

https://jsfiddle.net/syLn9xve/4/

**Comment by AvogadroSG1** [comment]
I think mine might be a different issue.  Tough to make a JSFiddle out of it.  I'll see what I can do!  Thanks!
