### ISSUE TITLE
Serious Issues when using a form outside current table div

### ISSUE THREAD

**Issue by kshipp** [mkoryak/floatThead#346]
Cannot create a jsfiddle because no easy way to use php postback.
It would be nice if you could fix this serious issue, but if you can't, at least keep this ticket closed and available for searching.
This needs to be posted here so others can easily find this solution when this happens:
Warning: If you move your FORM element outside of the div that contains the table that you're floating, the postback results will NOT include the elements inside the table!
Always keep the FORM element inside the same div as the table you're floating.
Always keep the FORM element inside the same div as the table you're floating.

**Comment by mkoryak** [comment]
not sure this is useful, but ok
