### ISSUE TITLE
Header's not scrolling with Bootstrap table-container

### ISSUE THREAD

**Issue by mozzer39** [mkoryak/floatThead#347]
Hi,
I have a problem with floatThead running on Bootstrap table. Look at the jsfiddle:
https://jsfiddle.net/euwz8x58/

When the window is width enough (more than 768px) but table content is wider than available space, horizontal scroll scrolls the table, but the header remains misaligned. On smaller width when bootstrap RWD media style is working, everythink works fine. How can I fix that issue?

**Comment by mkoryak** [comment]
your header contains more columns than there are in the table. the number of columns should match.

https://jsfiddle.net/euwz8x58/1/
