### ISSUE TITLE
Header moves to the right after F5

### ISSUE THREAD

**Issue by DominikHerold** [mkoryak/floatThead#352]
I have a table with a lot of columns. If I scroll horizontal to the right and then reload the page (F5), the header moves to the right, but not the rest of the columns. So the alignment doesn't work. I'm not sure, if it is a bug or if I'm just missing a parameter. I have to apologise, because my example doesn't work correct on jsfiddle, because you can not reload the frame. But you can download the html with script and should reproduce locally. Btw on your homepage (http://mkoryak.github.io/floatThead/#issues) you link to jsfiddle.**com**, but you have to link to jsfiddle.**net**
You can find the example here: https://jsfiddle.net/8ggygd81/2/
specs:

- Windows 7
- FF 51.0.1
- JQuery 1.10.2
- floatThead 2.0.0

Thank you for your work.

Dominik

**Comment by mkoryak** [comment]
this is fixed on master
