### ISSUE TITLE
Empty space between header and body

### ISSUE THREAD

**Issue by mackva** [mkoryak/floatThead#354]
I discovered the problem, when we quickly scroll the page. We can see the blank space between the header and body. It is reproduced in IE11. 
I think, because we move the header in the body or floating content. (It is slow for IE)

- IE11
- W7
- This problem is reproducible on the demo site (http://mkoryak.github.io/floatThead)

http://i.imgur.com/7kkhou3.gifv
http://imgur.com/kDuTYIN

**Comment by mkoryak** [comment]
nothing i can do it about it. The javascript is unable to keep up with scroll speed

**Comment by mackva** [comment]
Mkorya, thank you for your hard work, and fast response.
I'm a shame that you closed as won't fix.

BTW You can see that your headline is inert (slow), but fixed column a little bit faster. It also works with "position: fixed"

http://i.imgur.com/BPvGwSb.gifv
