### ISSUE TITLE
Table head jumps to the left when scrolling starts

### ISSUE THREAD

**Issue by xivVerge** [mkoryak/floatThead#356]
I have a table inside a container and I want that table to be centered and condensed (not using 100% width by default). So I added the class .table-nonfluid. As soon as this class is added the table header jumps to the left when scrolling starts. Can this be avoided using an existing option or is it a bug?

See
https://jsfiddle.net/humweguy/

**Comment by mkoryak** [comment]
it is a side effect of absolute positioning you are using. i have to wrap the table in a container in that mode, and so `margin: 0 auto` stops working. you can either fix it with css by styling the markup created by the plugin or use fixed positioning:

https://jsfiddle.net/humweguy/1/

**Comment by xivVerge** [comment]
As I have some dynamic content above my table I will stick to absolute positioning. by styling the markup you mean I have to add some css to the container your plugin creates for the absolute positioning?

**Comment by mkoryak** [comment]
Yes, inspect markup and you will see what needs to be done

**Comment by mkoryak** [comment]
The Dom that is created has classes you can

**Comment by mkoryak** [comment]
Blarg phone
