### ISSUE TITLE
Nested scroll containers

### ISSUE THREAD

**Issue by sabtt** [mkoryak/floatThead#358]
I'm trying to get this control working with something I'm pretty sure is not supported - multiple containing scroll frames.  As in the fiddle, this is one horizontal and one vertical.

It's very close to working as-is - the scroll event seems fine when returning multiple items from scrollContainer, it attaches to both and scrolls vertically as expected.  The actual header element, however, is cut off horizontally at the width of the outer container and does not clip to the direct parent, in this case the inner scroll area - this is most apparent when scrolling horizontally using the inner scroll area.  In fact, it does not even seem to clip to the outer on the left, though this is a bit hard to see in the fiddle.

Can you suggest how to get this working?  Or is it not something the control can (or will) support?

https://jsfiddle.net/dr0c8ao4/

**Comment by mkoryak** [comment]
This is not supported.. but I can get it working :)

This is actually how the responsiveContainer option works. The x and y scrolling are driven by different containers. 

try this:

https://jsfiddle.net/dr0c8ao4/1/

**Comment by mkoryak** [comment]
I lied, its too good to be true, it wont work so well when there is a scrollbar on the window. But, you might be able to hack it into submission. I started doing it and made some progress, but I should stop and do real work now:

https://jsfiddle.net/dr0c8ao4/2/

**Comment by sabtt** [comment]
Thanks for the advice, I've managed to get the top aligning correctly, though only by modifying floatthead to account for nested containers when calculating tableOffset inside calculateFloatContainerPosFn.  This removed the need to manually trigger the resize event.

Unfortunately, the headers still float past the bottom of the table's containing element - this is unaffected by my modification, you can see this in your second fiddle by adding a load of br elements after it.

Further, when integrated with my actual app the columns do not correctly align with the real table header when scrolling horizontally - there is a large padding getting added to either side of the floating header.  I've been unable to work out exactly what's causing this so can't provide a minimal example, though it's clearly something to do with the element styles since the padding is exactly the same size as the table's x-offset relative to its direct parent.  It's fine at the initial horizontal scroll offset, but the floating header does not extend left to match the new bounds of the real header when scrolling.

If you have any suggestions on where to look to tackle these further two issues, I'd appreciate it, but it looks like I won't be able to use this control for my app as refactoring the existing layout to get it to cooperate would be a huge amount of effort, and I only have limited time to work on it.

**Comment by mkoryak** [comment]
I would suggest looking at responsive scrolling. When it's active it uses window for y and container for x. 

That's the best I can do. Good luck

**Comment by mkoryak** [comment]
Why do you have such a strange layout?

**Comment by sabtt** [comment]
It's an existing form solution, as part of a larger application, that is broken down into sections, some of which may contain tabular data.  The sections individually scroll horizontally if there is too much content to fit on-screen, but the form as a whole scrolls vertically.  The location of the form container is also dynamic wrt the page.

Thanks for the help anyway!
