### ISSUE TITLE
Background THead is removed on window resize after tbody replacement

### ISSUE THREAD

**Issue by ithielnor** [mkoryak/floatThead#359]
In my usage, I use something like this to update the data in my table:

    $tableElement.find("tbody").replaceWith(tbodyLoadedFromElsewhere);

After this is called, if the window is resized, or some other reflow event occurs, the size-row `thead` is completely removed from the table causing the first row to disappear behind the floated header.

In this fiddle, click the trigger link and then adjust the window size to see the effect.

https://jsfiddle.net/4u3L40r3/1/

**Comment by ithielnor** [comment]
My workaround for now is to do: 

    $tableElement.find("tbody tr").remove();
    $tableElement.find("tbody").append(tbodyLoadedFromElsewhere.find("tr"));

**Comment by mkoryak** [comment]
yep, the plugin hangs on to a ref of the tbody and when you replace it in the dom, it breaks. your workaround is the only way it will work. 

I am not going to change it to re-find the tbody element every time it is needed.
