### ISSUE TITLE
Dropdown on header is not working

### ISSUE THREAD

**Issue by gabn88** [mkoryak/floatThead#360]
I have  a dropdown on my table header to do some filtering, but I have to comment a few characters in the source code to get it working.

https://jsfiddle.net/psLbsLnx/

The characters to comment are: <div style="  **_overflow: hidden _**"

**Comment by gabn88** [comment]
For the rest, thanks for this easy to use library! 👍

**Comment by mkoryak** [comment]
you need this css:

https://jsfiddle.net/psLbsLnx/1/

**Comment by gabn88** [comment]
Feel so stupid right now. Thanks for the quick response!

**Comment by mkoryak** [comment]
yeah, that needs to stay there in the source as it addresses issues that other people have, but not you :)
