### ISSUE TITLE
Fixed headers are in front of jquery mobile header and menu when scrolled

### ISSUE THREAD

**Issue by fitforcode** [mkoryak/floatThead#362]
Hello there,

I made a page with jquery (V2.1.4) and jQuery Mobile (V1.4.5) and then added the floatThead plugin.
After that the table headers were fixed and everything went fine.
But then I noticed that, when I scrol down the page and the whole table begins to scroll out of the view, the header lies in front of the jquery mobile header. This happens with all tables of the page.
Another impact is, that when I open the jquery mobile Menupanel the headers are in front of some menu entries, so that they are not clickable. (I couldnt get this to work in the jsfiddle :( )
and it seems like that this thing just occurs in jsfiddle when scrolling by clicking whith the mouse on the scrollbar - not when scrolling with the wheel...).

Are there any known issues on that ? I searched trough Issues and pull requests but found nothing like that. Since I'm a beginner with these techniques, there is maybe a problem in general with my code.

See this jsfiddle for live demonstration: [jsfiddle](https://jsfiddle.net/w8hq7kg5/8/) 
(reduce the height of the output window till the scrollbar of the page appears and then scroll down - the table-header will get in front of the header).

I tested this in Chrome48 and IE11 on a Win7 64bit with floatthead 1.x.x and 2.0.3.

Thank you in advance, for reading this and hopefully answer it.

**Comment by mkoryak** [comment]
`z-index` is your friend:

https://jsfiddle.net/w8hq7kg5/9/
