### ISSUE TITLE
ScrollContainer assigned incorrect width to floatThead-container

### ISSUE THREAD

**Issue by li-xinyang** [mkoryak/floatThead#363]
Follow the documentation to create an overflow scrolling table and set a fixed width to the table wrapper.

- Google Chrome Version 57.0.2987.110 (64-bit)
- Ubuntu 16.x
- jQuery 3.2.1
- floatThead latest via Bower

https://jsfiddle.net/8wo3bprh/1/

Table header is get cropped due to the inaccurate width and `overflow:hidden`.

JSFiddle Screenshot,

![screenshot from 2017-03-23 16-10-06](https://cloud.githubusercontent.com/assets/3349406/24237900/56b47d9a-0f76-11e7-8dc1-9ee829e11cd6.png)

Production Screenshot,

![screenshot from 2017-03-23 15-53-11](https://cloud.githubusercontent.com/assets/3349406/24237821/df635522-0f75-11e7-975f-7f6d500559b8.png)

**Comment by mkoryak** [comment]
Your style on div is too broad. 

This plugin generates additional markup. You need to be more specific.

https://jsfiddle.net/8wo3bprh/3/

**Comment by li-xinyang** [comment]
It kind wired that I cannot reproduce the issue on a Mac with the same version of Google Chrome.

By the way, the previous sample is working fine on Ubuntu Firefox.

**Comment by mkoryak** [comment]
sorry, I will be of no help here. I don't have an ubuntu box I can test on.

**Comment by li-xinyang** [comment]
Thanks, I will update you if I fond the issue on Ubuntu (Window seems have the similar issue two).

**Comment by Rikhter** [comment]
:+1:  also happening in IE11 under windows 7.

**Comment by mkoryak** [comment]
can i have a jsfiddle with ie11 issue?

i offered a solution to the original issue, so yours is new maybe?

**Comment by Rikhter** [comment]
I'll see if I can get a fiddle going today.

**Comment by LeroyGerrits** [comment]
I have exactly the same issue. Anyone resolved this yet?

**Comment by mkoryak** [comment]
Can you provide a fiddle. I am waiting on one. Try the latest 1.x.x version, it might be not there

**Comment by mkoryak** [comment]
Also not having a windows box really makes this one difficult for me to fix at the moment. I'll get a VM after a new fiddle

**Comment by LeroyGerrits** [comment]
The fiddle posted in the OP is applicable for me too. I have a very basic table, but the floated <thead> part is missing about 18 pixels in width, causing the same 'gap' to show up as posted in the OP. Using Windows and Chrome (59.0.3071.115); and floatThead 2.0.3.

**Comment by mkoryak** [comment]
ok, does the fix i posted for his fiddle help you? 

https://jsfiddle.net/8wo3bprh/3/

thats the problem I have with his fiddle, he had an error in it probably unrelated to this bug, but it makes it a bad example for me to work from

**Comment by LeroyGerrits** [comment]
Both fiddles have the issue for me. My setup is exactly the same (table with a wrapper with a fixed width and height).

**Comment by mkoryak** [comment]
I think i am getting to the bottom of this issue. does the following fiddle correct it for you on your IE ?

https://jsfiddle.net/8wo3bprh/14/

**Comment by mkoryak** [comment]
it appears that the issue stems from a change in some version of chrome where they changed how scrollbars  affect the dimensions of the container where they appear.

**Comment by LeroyGerrits** [comment]
Workaround works on this end, verified in latest Chrome and Edge / IE versions. 
Awesome. ;) Keep up the good work!

**Comment by MaLeVoLenT1** [comment]
I had this same issue except I used another plugin for scroll bars found here:
http://manos.malihu.gr/jquery-custom-content-scroller/

**My fix**
To fix this issue, I assigned another class that extended the width after the initialization.
https://gist.github.com/MaLeVoLenT1/a4c8d2b6336c183b00563c2494a64532

**Comment by mkoryak** [comment]
The reason I am not fixing this right now is that the issue is that browsers started to "use" zero width scrollbars at some point, while reporting ~15px width using the detection method that I use. 
This is weird and I would like to first figure out when this behavior got introduced, and which browsers are affected.

**Comment by mkoryak** [comment]
I looked into this a bit today. It turns out the culprit is jquery. The `width()` method does not include the scrollbar width in 3.2.0 onward. The fix will have to be a jquery version check. yey
