### ISSUE TITLE
destroy method creates extra rows

### ISSUE THREAD

**Issue by dallaselopez** [mkoryak/floatThead#364]
Please see fiddle. Having this issue with my tables on an internal application. I've recreated it in the fiddle. Because of responsive nature, I'm calling destroy and reinit during resize. In my app, there is a check for screen size to determine where the position of the thead is going to be. If you resize the produced result in fiddle, you'll notice that it applies additional rows. If there is a method that I'm missing, please advise... 

On another note, any plans to integrate position: sticky?

**Comment by dallaselopez** [comment]
Closing issue... My mistake... I put pos instead of position. This is still happening in my applicaiton, but I'm unable to reproduce in jsfiddle.

**Comment by dallaselopez** [comment]
[https://jsfiddle.net/9qznf1b5/1/](https://jsfiddle.net/9qznf1b5/1/)

reopened. I got it to reproduce

**Comment by mkoryak** [comment]
> any plans to integrate position: sticky?

yes, but probably not in this lib. I am working (slowly) on version 2 in es6, that is where new things will go.

**Comment by mkoryak** [comment]
there is perhaps a bug here, but you are doing something really weird :)

first, reinit does not take options, though maybe it should. 

but you dont need to bind that resize handler, because the `top` can be a function for this exact reason:

https://jsfiddle.net/9qznf1b5/3/

**Comment by dallaselopez** [comment]
![image](https://cloud.githubusercontent.com/assets/2340660/24299048/e0ee6c50-1075-11e7-944b-d18f267e51f1.png)

This is after resize.

**Comment by dallaselopez** [comment]
var floatHeader = function (table) {
        var topPos = window.innerWidth < 1125 ? 0 : 63;
        $(table).floatThead({
            top: topPos,
            position: 'absolute'
        });
    }

    // handles the freeze header functionality
    var freezeHeader = function (table) {        
        floatHeader(table);

        $(window).resize(function () {
            var reinit = $(table).floatThead('destroy');
            //setTimeout(reinit(), 2000);    

            setTimeout(floatHeader(table), 2000);
        });

    }

Alternatively, I've attempted this.

**Comment by mkoryak** [comment]
ok, but scroll up and look at my last comment.

it looks like there is a bug with destroying it in absolute position mode when the header is floated, though so far I cannot reproduce on the docsite.

**Comment by dallaselopez** [comment]
Actually, that did fix it.... 

[https://jsfiddle.net/9qznf1b5/4/](https://jsfiddle.net/9qznf1b5/4/)

**Comment by dallaselopez** [comment]
And, thanks for taking a look.
