### ISSUE TITLE
DataTable and scrollX

### ISSUE THREAD

**Issue by Hanterdro** [mkoryak/floatThead#365]
Hey,

floatThead 2.0.3 seems not working with DataTable  1.10.13  when `scrollX` is set to `true`.

**Comment by mkoryak** [comment]
ok,
provide a jsfiddle and I can take a look, though honestly ill probably just drop datatables support at this point.

**Comment by Hanterdro** [comment]
Here is the jsfiddle :-)

https://jsfiddle.net/e6t2c39m/

**Comment by mkoryak** [comment]
yep, sadly the new version of datatables is nothing like the old one i supported ~4 years ago. Its putting the header into a separate div. This plugin will not work there. 

I will remove the claims of supporting it and rip out all datatables related code from this lib
