### ISSUE TITLE
How about a way to make it scroll on "integer" rows

### ISSUE THREAD

**Issue by shaulid** [mkoryak/floatThead#366]
This is not a bug, just a request/question -
is there a simple way to make it not cut the row just below the header?
I want that below the header the row will be full and not half row or cut to some extent because it doesn't look good. So what it means is that scrolling should happen only for full rows. Any simple ideas?

Anyhow,
Thanks for the plugin.

**Comment by mkoryak** [comment]
There is no simple way to do that without rewriting the plugin from scratch. I did it this way because it makes it much easier to do the scrolling calculations 

Anywho,
You're welcome

**Comment by shaulid** [comment]
:)
OK, thanks.
