### ISSUE TITLE
Col group col not getting width in IE 11

### ISSUE THREAD

**Issue by Arvn41** [mkoryak/floatThead#367]
Hello,

When I use flotThead with my bootstrap table it working well in IE 11, but when I pass the values dynamically, table headers fixed, but table UI disturb, its not showing me all headers, also when I inspect its not apply the width to tbody col-group cols, and tables position is auto(not table layout fixed).

My table containing col-span in table head, I have tried to produce same in jsfiddle but same situation not happens

Is I miss some parameters? below is my code, and its perfectly work with IE Edge, FF, Chrome, IPAD and MAC only fails in IE 10 and 11

I have use following code
```
 var $table = $('.table.table-scroll-div');
           $table.floatThead({
            position: 'absolute',
            scrollContainer: true
           
        });  
       $table.floatThead('reflow');
```
Also tried with
```
 var $table = $('.table.table-scroll-div');
           $table.floatThead({
            position: 'absolute',
            scrollContainer: true,
            getSizingRow: function($table){
                return $table.find('thead tr:not(.grouping):visible:first>*');
            },
            useAbsolutePositioning: false
        });  
       $table.floatThead('reflow');
```
![floattheadissue](https://butt.githubusercontent.com/assets/27851973/25272960/76c00274-26a7-11e7-9aa4-b62e44592888.png)

- jsfiddle that reproduces your issue in its simplest form possible [required]

- IE 11
- `Windows

`
- 3.1.1
- 2.0.3
no jsfiddle == your issue will be closed

**Comment by mkoryak** [comment]
can you please reproduce your issue on jsfiddle.net and post the link to the fiddle here.

you can look at past closed issues with label 'solved' to find a starting point

**Comment by mkoryak** [comment]
Ok, you have a col-span in table header. so you are probably read this page:

http://mkoryak.github.io/floatThead/examples/row-groups/

but you cant simply copy-paste the code from there into your code. you need to understand what it is doing. do you understand what needs to be returned from that `getSizingRow` method?

**Comment by mkoryak** [comment]
no response, closing

**Comment by Arvn41** [comment]
Hii, sorry for the late reply, I have tried to reproduce the same in JSfiddle, but i was not able to do it and now that issue  is resolved, which was due to wrong binding of data.
