### ISSUE TITLE
Can this be used to lock the left most column when scrolling too?

### ISSUE THREAD

**Issue by deanpeterson** [mkoryak/floatThead#368]
Is it possible to tweak this somehow to allow locking the left most column in a table and making it float on horizontal scroll?

**Comment by mkoryak** [comment]
See readme

**Comment by deanpeterson** [comment]
I've looked everywhere. I don't see anything on being able to freeze the
left most column and have it stay in place on horizontal scroll.

**Comment by deanpeterson** [comment]
Oh, I see it under things this does not do.

**Comment by mkoryak** [comment]
Sorry,
I should have just said that, but I was just waking up.

**Comment by joetinger** [comment]
any plans to add this feature?

**Comment by mkoryak** [comment]
No

**Comment by deanpeterson** [comment]
Is it something that is just too error prone to consider doing? I've attempted to just have two tables side by side and calculate heights on the fly, but the alignment is always off on some browsers after many rows. And the typical solution of forcing the left most column to have absolute positioning takes it out of table flow and the same problem with alignment occurs.

 Is there a way to take up a collection to have you implement this specific feature? I'd contribute.

**Comment by mkoryak** [comment]
Libs that attempt to do too many things usually end up doing them badly.

I have enough functionality to support here as it is.

This kind of a thing should be done in another lib not related to this one.

Also I don't have much time lately. You are better off finding someone else
to build this for you

**Comment by deanpeterson** [comment]
Completely understand. Thanks for the reply.
