### ISSUE TITLE
"Uncaught TypeError: util.isFunction is not a function"

### ISSUE THREAD

**Issue by Dylan-Chapman** [mkoryak/floatThead#369]
I have a custom lodash build that contains only a select few things I need on my site (debounce and throttle). This means that the line

```JavaScript
var util = window._ || (function underscoreShim(){
```

assumes the existence of functions which aren't necessarily there, leading to the error in the title (as an example).

A workaround is to switch script order, I suppose. In my environment, I can't do this, though.

Is this something the library should address? Or the user?

**Comment by mkoryak** [comment]
This is a good question. At this point, I should just remove the fallback on `window._` since I no longer provide a smaller version of the lib which does not contain the underscore methods. 

I will file this as a bug and will have a fix soonly

**Comment by mkoryak** [comment]
soonly seems to mean not so soonly, life became busy. can you make a PR for this (and run `npm build` to generate dist) ?

**Comment by mkoryak** [comment]
the fix btw is:

`var util =  (function underscoreShim(){ `

**Comment by mkoryak** [comment]
fixed in #373
