### ISSUE TITLE
README.md: Confusing section "Who is using floatThead"

### ISSUE THREAD

**Issue by protron** [mkoryak/floatThead#370]
I think it's confusing that the README.md section "Who is using floatThead" contains "compat-table" and "staticsitegenerators.net" (right in the middle of other links which actually shows this plugin usage).

Besides, the link to django-sql-explorer commit seems to be broken now. Maybe you can use this link instead (they list this plugin in their readme.md):
https://github.com/groveco/django-sql-explorer#dependencies

**Comment by mkoryak** [comment]
some of the links link to code while other links link to sites which use the plugin. how do you think that section should be organized?

**Comment by protron** [comment]
I just realized that "compat-table" is actually using your plugin. I guess I got confused by the different format (not redirecting to the github site, and not having an item below as in "netdisco" and the rest). Sorry.
But if I would have to choose I would change that one to:
### [compat-table](https://github.com/kangax/compat-table/) 
- https://github.com/kangax/compat-table/blob/gh-pages/jquery.floatThead.min.js
- [online site](http://kangax.github.io/compat-table/es6/) (see floatThead in action here)

But I still think is better to remove 'staticsitegenerators.net' as they are not using your plugin anymore. It seems like they removed your plugin in this huge commit: https://github.com/bevry/staticsitegenerators-website/commit/2616d24536ea0bc9017dd03b44d9a2e72f126edb

**Comment by mkoryak** [comment]
Ah I didn't realize they removed it. I can see how that is confusing. I like your proposed format, want to submit a PR ;) ?

**Comment by protron** [comment]
Sure! There it is.

**Comment by mkoryak** [comment]
Thanks a bunch!
