### ISSUE TITLE
Can't get header cell values

### ISSUE THREAD

**Issue by lcsqlpete** [mkoryak/floatThead#372]
I am using floatThead with window scrolling successfully.  However, my application needs to download the table contents to a csv file including the header cell values .  My jQuery code to get the header cell values is:

`$('#forecatttable > thead > tr > th').each(function () {
            alert($(this).text());
  })`

The alert is just for debugging purposes. The text of every header cell comes back as empty.  Similar code to get the table body cells works fine.  If I remove the fixed-head-wrapper class from the div containing the table, the header cell values are returned correctly.

Is this a limitation within floatThead or am I doing something incorrectly?

Thanks,
Pete

**Comment by mkoryak** [comment]
in the docs, see `getRowGroups`

```js
$('#forecatttable ').floatThead("getRowGroups").find('thead > tr > th').each(function () { alert($(this).text()); })
```

**Comment by lcsqlpete** [comment]
Thanks.  The second of your examples worked.
