### ISSUE TITLE
Support for horizontal scrolling with vertical page scrolling

### ISSUE THREAD

**Issue by Vyling** [mkoryak/floatThead#376]
- Windows 10, Firefox 54
jQuery and library are latest version

Okay my title might be confusing, but I got the following issue:
I have a table which can be scrolled  horizontally with a fixed width container, but has a fixed height without vertical scrolling. When I scroll down the page, I want the header to scroll with the page. However, setting either scrollContainer or responsiveContainer will only make it scroll within the container - which is not vertically scrollable.
Setting none of both will result in the header to be outside of the table container.
I hope you can follow me. Here are the js fiddles with the issue: 
https://jsfiddle.net/humweguy/4/
https://jsfiddle.net/humweguy/5/
https://jsfiddle.net/humweguy/6/

So, I want the thead to be within the container, but also scroll with the page.

**Comment by mkoryak** [comment]
sorry, this is not supported.

**Comment by mkoryak** [comment]
actually, what about this:

https://jsfiddle.net/humweguy/7/

**Comment by mkoryak** [comment]
maybe I do support that, a little

**Comment by Vyling** [comment]
Strangely doesn't work in the application, trying to reproduce on jsfiddle or fix locally. Please hang on.

**Comment by mkoryak** [comment]
you noticed the style change I made, right?

**Comment by Vyling** [comment]
Oh! Wouldn't have thought that'd make the difference. Now it works, thank you very much. It really helped a ton to finally get a working sticky header for PrimeFaces' DataTable.

**Comment by vinnygambiny** [comment]
How work with a scroll vertical on a different div of scroll horizontal

https://jsfiddle.net/y2qzekun/

**Comment by mkoryak** [comment]
That is not supported. Does the responsiveContainer option perhaps work for
you?

**Comment by mkoryak** [comment]
Also, please create a new issue

**Comment by vinnygambiny** [comment]
I have try with responsiveContainer, the horizontal scroll work but the vertical not. The thead don't move with the div vertical

**Comment by mkoryak** [comment]
Sorry, I can't help you with this
