### ISSUE TITLE
Hide column method doesn't hide floatThead header

### ISSUE THREAD

**Issue by luca159** [mkoryak/floatThead#377]
Hi, i got this problem: when i run a custom method, that basically sets "display: none;" to a specific column and his relative "th", the header created by the floatThead plugin doesn't hide, even if i call:

"$('#mytable').floatThead("reflow");".

Maybe i'm missing something. 
Thank you,
Luca

(here is the working jsfiddle, just press the show/hide checkbutton to see the problem)
https://jsfiddle.net/humweguy/12/

**Comment by mkoryak** [comment]
I have a section in the docs all about this. Have you read it? If the top
of my head the method you want is getRowGroups I think

**Comment by luca159** [comment]
Hi, thanks for the reply .. actually i solved the problem this way :
when i call the show_hide method, first i destroy floatthead, then i hide the columns and at the end i re-initialize it.

Is this a good behavior in your mind?

https://jsfiddle.net/humweguy/13/

**Comment by mkoryak** [comment]
No.

**Comment by mkoryak** [comment]
I'll show you a better way to do it if you tell me how to improve to docs
afterwards

**Comment by luca159** [comment]
Of course i'll help you if i can. Actually don't know how , but i'll try my best.

**Comment by mkoryak** [comment]
https://jsfiddle.net/humweguy/14/

but tell me, could you find the docs for this on my docsite? 

did you find this page:

http://mkoryak.github.io/floatThead/examples/hidden-columns/

and if so, what would make that page more readable?

**Comment by luca159** [comment]
i think that if the examples would have been interactive like the ones on jsfiddle it would be easier to understand. Because in my case i learn a lot from trial and error .. like i've got a working piece of code and i start modify something here and something there so i can better understand how the whole thing works.
