### ISSUE TITLE
In Firefox,$('table').floatThead('reflow'); doesn't seem to work

### ISSUE THREAD

**Issue by LongYue9608** [mkoryak/floatThead#379]
Hello, friend，Questions as stated in the heading，Looking forward to your reply, thank you very much。

**Comment by LongYue9608** [comment]
There is no data in the form, in Google, the header shows the width is good, but in Firefox below, the header is crowded to the left。
$('table').floatThead({
	position: 'absolute',
	 scrollContainer: true
	});
	$('table').floatThead('reflow');That's what I wrote。

**Comment by mkoryak** [comment]
I can do nothing with this. I need a jsfiddle which reproduces your issue.
