### ISSUE TITLE
floatThead('reflow'); doesn't seem to work

### ISSUE THREAD

**Issue by km3945** [mkoryak/floatThead#380]
Use the reflow use case ( doesn't seem to work )
https://jsfiddle.net/faytxndn/

I expect the effect: 
https://jsfiddle.net/6buen7a4/

**Comment by mkoryak** [comment]
I'm on my phone, I'll clarify later today, but:

The top option can also take a function. If you use a function instead of
Number, you can use that function to return the height of the menu. You
will still need to call reflow after that height changes, but you would not
need to destroy the plugin

**Comment by mkoryak** [comment]
here you go
https://jsfiddle.net/faytxndn/1/

reopen if you have more issues
