### ISSUE TITLE
Bootstrap Tab Panes showing both tables in the one

### ISSUE THREAD

**Issue by simonprice33** [mkoryak/floatThead#381]
![capture](https://user-images.githubusercontent.com/6917459/29423350-4aab8540-8373-11e7-8228-b01dd97642ee.PNG)
Hi 

Following the example from jsFiddle http://jsfiddle.net/muruadvm/1/  I am having an issue where I am seeing both tables from both tabs in the one tab pane rather than each respective table in its respective tab. 

Everything else works fine, the table header stays in the container, it scrolls perfectly but its just showing both tables.

My JQuery is this 

`$(document).ready(function() {
            $('table').floatThead({
                position: 'absolute',
                scrollContainer: true
            });
        });`

I did try and paste the razor but it doesnt show well in this window 

Any and all help on this would be very much appreciated.

**Comment by mkoryak** [comment]
sorry, i cannot help without a jfiddle. does it work without my plugin?

**Comment by simonprice33** [comment]
I will get a fiddle up to you shortly

**Comment by simonprice33** [comment]
Here is a link to the fiddle 

http://jsfiddle.net/SimonPrice/ztm06fjm/2/

I have found if i use this JQuery that I have this issue

`$(document).ready(function() {
        $('table').floatThead({
            position: 'absolute',
            scrollContainer: true
        });
    });`

However, if i use this JQuery below it renders ok, but when when i scroll past the table and then back up the header jumps out of the containing div and then goes to the top of the page and is just functionally wrong 

    `//$(document).ready(function () {
    //    $('.sticky-header').floatThead();
    //});

    //$('a[data-toggle="tab"]').on('shown.bs.tab', function () {
    //    $('.sticky-header:visible').floatThead('reflow');
    //});`

**Comment by mkoryak** [comment]
I see, you cant use .tab-pane as the scroll container because in absolute positioning mode the scroll container gets wrapped in a div, and that breaks your bootstrap layout. You can put another container inside the tab-pane and put the overflow on that, or you can use fixed positioning mode which does not mess with your DOM as much:

http://jsfiddle.net/ztm06fjm/4/

**Comment by simonprice33** [comment]
Thanks for your response, however your fiddle shows something that I have already experienced too where there header is fixed, but the second tab never becomes active. 

Any recommendations on how to get around this?

**Comment by mkoryak** [comment]
You didn't include bootstrap JavaScript, so that is why it does not work in
your fiddle

**Comment by simonprice33** [comment]
Ok, I will try that in my version now and let you know how i get on

**Comment by simonprice33** [comment]
Ive included that in the inclides now and see it working in jsfiddle, however I have that you have implemented in my system, the tables view in their own tabs, I can select the tabs and scroll the data, however the headers still scroll rather than fix their position. 

I have your js file after jquery1.11.x.js and after bootstrap.js,  and the header row continues to scroll. 

I have also tried it being the last thing in the file too as when having 

`$(document).ready(function () {
    $('.sticky-header').floatThead({
        scrollContainer: ($t) => $t.parent(),
        position: 'fixed'
    });
});`

in with my other scripts too that takes away a lot of other jquery behaviors that I have in place

**Comment by mkoryak** [comment]
ok, that is just ES6, which you can translate into ES3 like this:

`scrollContainer: function($t) { return $t.parent() }`

**Comment by simonprice33** [comment]
Absolute star!!!!!!
