### ISSUE TITLE
Can't make floatThead to work with Datatables

### ISSUE THREAD

**Issue by HeyJude1** [mkoryak/floatThead#382]
I'm trying to use floatThead on a table initialized with Datatables, but though trying differnet methods, I can't make it work. Would be glad for any help.
Here's my fiddle - it currently contains my trial with the use of `scrollContainer`, but I'm not sure it's what I need...I'm using IE11 (but it doesn't seem to be a browser issue):
[fiddle](http://jsfiddle.net/7fqwra3g/7/)

**Comment by mkoryak** [comment]
Your table selector was missing `#`, also the default positioning of the plugin was messing with your styles so I changed it to use `fixed`

see: http://jsfiddle.net/7fqwra3g/8/

**Comment by HeyJude1** [comment]
Thanks, @mkoryak
