### ISSUE TITLE
Header conflicts with first row

### ISSUE THREAD

**Issue by sunnyrjuneja** [mkoryak/floatThead#383]
Hi mkoryak,

First of all, thank you so much for your hard work. Your library is great and it's already made my life much easier.

I'm having some problems where the header is sitting on top of the first row. I believe it's because I'm using colgroups but I'm not entirely sure. I'm also noticing some issues where the alignment is now broken. If you can help me with the header intersecting with the first row, I think I can probably figure out the alignment too.

https://jsfiddle.net/4srjg9nd/

**Comment by mkoryak** [comment]
Sadly this plugin does not support colgroups with `span` attributes. If you are using those colgroups for styling your table you are SOL.

The only thing it supports is this type of layout:
https://jsfiddle.net/4srjg9nd/2/

**Comment by sunnyrjuneja** [comment]
@mkoryak Thanks for your quick response and the jsfiddle. I'm going to change my styling to match that. Really appreciate your help.
