### ISSUE TITLE
Usage option to control when to destroy

### ISSUE THREAD

**Issue by adixondev** [mkoryak/floatThead#384]
all new issues should include the following:
- description of the issue and steps to reproduce
On your web site, in the window scrolling example, you hide the header only after the user scrolls past the very bottom of the table.  Do you know of any arguments that can control this?  Perhaps if we wanted to "glue" the header just above the second to last row of a table?

- jsfiddle that reproduces your issue in its simplest form possible [required]
https://jsfiddle.net/dixalex/s6dyobo7/

- browser name/version
- OS name
- jQuery version if not latest: 1.9
- floatThead version if not latest

no jsfiddle == your issue will be closed

Ideally, this would be an configurable option where we could set defaults of where we want the header to anchor while scrolling.

If I have posted this issue in the incorrect manner, please forgive me.

**Comment by mkoryak** [comment]
what you want is the `bottom` option. I have no idea why it made it so you have to return a negative number, probably because I didn't really think about it and made it work just like `top` works. anyway:

https://jsfiddle.net/s6dyobo7/2/

**Comment by adixondev** [comment]
I appreciate your time and your example.  I apologize that I did not see this in the documentation.

**Comment by mkoryak** [comment]
Any time.
