### ISSUE TITLE
bottom offset not respected when positioning is absolute instead of fixed

### ISSUE THREAD

**Issue by herringtown** [mkoryak/floatThead#385]
When you use position: 'absolute' with bottom: <offset> the bottom offset is not respected like it is when the position is 'fixed'.  Instead, it seems to "jump" right to the bottom when it hits it's bottom offset instead of halting the translateY increment steps. 

steps to reproduce:
* setup a properly formed table, load required libs
* demonstrate correct behavior with $table.floatThead({position: 'fixed', bottom: -45});
* reset floatHead > $table.floatThead('destroy');
* swap out positioning strategy with: $table.floatThead({position: 'absolute', bottom: -45});
* ^ or just skip steps 2&3 and go right to 4 ;)

jsFiddle: https://jsfiddle.net/herringtown/ya59zo2h/2/ 

browser: Chrome 60.0.3112.113 (Official Build) (64-bit)
OS: OSX Sierra

![floatthead-pos-abs-bug](https://user-images.githubusercontent.com/2006761/30176929-1e3bc32a-93d2-11e7-85bb-a9cc5786b43f.gif)

**Comment by mkoryak** [comment]
ok, thanks for the report. ill take a look

**Comment by mkoryak** [comment]
I wonder how long its been doing this.

**Comment by herringtown** [comment]
@mkoryak I tried with both current release and the 1.4.5 release (the one included with the angular-floatThead plugin).  So I would guess it's been doing this for quite a while ? :)

**Comment by mkoryak** [comment]
yeah I added `bottom` as an afterthought, probably just copied `top`, this is why you have to return negative numbers from it. If I actually thought about it I would have made it be a positive number. I am not sure fixing it is worth a major version bump though. It appears that only you and one other guy have used this feature since I wrote this plugin ;)

**Comment by mkoryak** [comment]
I am going to pretend that using that other positioning mode is a workaround, but I will fix this one soon

**Comment by herringtown** [comment]
@mkoryak cool -- in my case, I had to switch to absolute positioning b/c it have been too hacky to figure out all the scenarios for reflows (dom above where i have the floatthead table gets modified a lot) when in fixed.    If you've got any suggestions on where to look in the code for an obvious place to patch, I'd be happy to give it a go (if it's just a few lines of fix) and submit a PR..

**Comment by mkoryak** [comment]
Yes, the issue is happening here:

https://github.com/mkoryak/floatThead/blob/master/src/jquery.floatThead.js#L786

`floatEnd` is the var containing your bottom offset. 

probably just need to add or subtract that there :)
