### ISSUE TITLE
bug when toggle browser fullscreen reinit floatThead

### ISSUE THREAD

**Issue by lishichao1002** [mkoryak/floatThead#386]
all new issues should include the following:
- description of the issue and steps to reproduce

1.In browser normal mode. I init floatThead. it's ok.
```javascript
$('.header').show();
var $table = $('table');
$table.floatThead({
    top: 40
});
```
2.In browser  fullscreen mode.I reinit floatThead. it's not ok.
```javascript
$('.header').hide();
var $table = $('table');
$table.floatThead('destroy');
$table.floatThead({
    top: 0
});
```

the toggle code fullscreen as follows:
```javascript
screenfull.on('change', () => {
    if (screenfull.isFullscreen) {
        $('.header').hide();
        $table.floatThead('destroy');
        $table.floatThead({
            top: 0
        });
    } else {
        $('.header').show();
        $table.floatThead('destroy');
        $table.floatThead({
            top: 40
        });
    }
});
```
![image](https://user-images.githubusercontent.com/13584162/30199915-62a17f84-94a7-11e7-969d-79988773c7f3.png)
![image](https://user-images.githubusercontent.com/13584162/30200102-1ab533b8-94a8-11e7-80ae-632e5a1483c1.png)

- jsfiddle that reproduces your issue in its simplest form possible [required]

I put the code in plnkr
[bug table without bootstrap css](https://plnkr.co/edit/JAFNjHq7UaIfzFFdeq44?p=preview)
[bug table with bootstrap css](https://plnkr.co/edit/zz3PQe9ufy1Y5Fdzdg3E?p=preview)

- browser name/version

chrome version 60.0.3112.113（正式版本） （64 位）

- OS name

window 10

- jQuery version if not latest

https://code.jquery.com/jquery-1.10.2.js

- floatThead version if not latest

https://cdnjs.cloudflare.com/ajax/libs/floatthead/2.0.3/jquery.floatThead.min.js

no jsfiddle == your issue will be closed

**Comment by lishichao1002** [comment]
I find the same quetion at #364 .

I should use` top: function(){ creenfull.isFullscreen ?  0 : 40 } ` instead of reinit.

**Comment by mkoryak** [comment]
Thanks
