### ISSUE TITLE
how to add animate to head

### ISSUE THREAD

**Issue by lishichao1002** [mkoryak/floatThead#387]
all new issues should include the following:
- description of the issue and steps to reproduce

![1_](https://user-images.githubusercontent.com/13584162/30320921-c53be48a-97e6-11e7-9867-4c7acc484729.gif)

- jsfiddle that reproduces your issue in its simplest form possible [required]

I put the code on the [plunker](https://plnkr.co/edit/zz3PQe9ufy1Y5Fdzdg3E?p=preview)      [jsfiddle](https://jsfiddle.net/lishichao1002/0w4emyk8/4/)

- browser name/version

chrome 61.0.3163.79

- OS name

window10

- jQuery version if not latest

https://code.jquery.com/jquery-1.10.2.js

- floatThead version if not latest

https://cdnjs.cloudflare.com/ajax/libs/floatthead/2.0.3/jquery.floatThead.min.js

no jsfiddle == your issue will be closed

**Comment by mkoryak** [comment]
Animate what? 

I need a bit more of a description. That gif has nothing to do with animation

**Comment by lishichao1002** [comment]
I put the code on the [plunker](https://plnkr.co/edit/zz3PQe9ufy1Y5Fdzdg3E?p=preview)      [jsfiddle](https://jsfiddle.net/lishichao1002/0w4emyk8/4/)

you can run the code the see the result.
1.click the fullscreen button, the chrome will fullscreen. then the top header will have 3px.
2.move the mouse to the top, the head will toggle 3px to 50px

![image](https://user-images.githubusercontent.com/13584162/30321899-41402b4c-97ea-11e7-8868-ab6e0496c3e8.png)
![image](https://user-images.githubusercontent.com/13584162/30321924-53f3b682-97ea-11e7-8ba8-be191d7a5712.png)

**Comment by lishichao1002** [comment]
I find the same quetion at #387.
The `position: 'absolute'` resolve my question.

Thanks a lot.
