### ISSUE TITLE
Unable to apply floatThead on dynamically created table

### ISSUE THREAD

**Issue by A-Dummy** [mkoryak/floatThead#390]
- FF 56.0.1 
- Windows 10

I am new with floatHead.
I got it working for static tables but need it for a dynamically created table.
In the jsfiddle example I am importing an excel file and turn it into an HTML table.

- [JSfiddle](https://jsfiddle.net/anonymousdummy/zerg1w5o/)

Any ideas?

**Comment by mkoryak** [comment]
First, 
if you want me to actually be able to view your fiddle, upload an example xls file somewhere I can use with this.

Second,
You load the data into the table and then you ` $('#tbl').floatThead();` which is wrong. That is a no-op if the table already floatThead installed. What you need to do is fire a reflow event on the table. The docs have examples.

**Comment by A-Dummy** [comment]
any xls file will do, but here's an example file [xls](https://drive.google.com/file/d/0B8DSqNDR56QecGRTeGNuRmlzSXc/view?usp=sharing)

Excuse my ignorance, but don't understand how to 'fire a reflow event'

**Comment by mkoryak** [comment]
Did you read the docs?

**Comment by A-Dummy** [comment]
The docs suggest using `$('table').floatThead({autoReflow:true});`
This however results in my [JSfiddle ](https://jsfiddle.net/anonymousdummy/ek9q3hfu/)example in an error `TypeError: $(...).floatThead is not a function`

**Comment by mkoryak** [comment]
Ok, you must really be new to javascript. Here is what you were doing wrong:

- The table gets created after they upload a file, so you cant init my plugin on page load, or at the top of the script. there is no table yet. 
- You had another init inside of the `loadFile` function, but it was **after** the call to `alasql` which is **async**. So my plugin tried to init before the table was built via that async function. 
- The thing I was talking about in the docs was `.trigger('reflow')` method, but that would only be needed if you had a table that stuck around on the page and you only refreshed the tbody part of it. You blow away and recreate the table every time you call `loadFile`, so you need to reinit my plugin every time too. 

I removed all init calls at the top, they will never work. You don't have a table there.
I moved the other init call to the bottom of the async function. 

You should read up on how async works in javascript.

Good luck!

https://jsfiddle.net/ek9q3hfu/1/

**Comment by mkoryak** [comment]
Oh, you were not initializing the plugin correctly to use with inner scrolling, I fixed that:
https://jsfiddle.net/ek9q3hfu/2/

also you should use `+=`

**Comment by A-Dummy** [comment]
Thanks mkoryak, it works now and thanks for the detailed explanation!
