### ISSUE TITLE
firefox printing headers in odd places

### ISSUE THREAD

**Issue by jnmills** [mkoryak/floatThead#391]
when using Firefox 57 (and some of the fiirefox versions in the previous few months) printing a floated table (floatThead 2.0.3) prints the headers misaligned, and a free set of headers elsewhere.

It works fine with Chrome.

It seems there is a Firefox bug where the mediaMatch event "print" isn't fired, so floatThead  doesn't do its work.  https://bugzilla.mozilla.org/show_bug.cgi?id=774398

I worked round this for my purposes by changing
```
      var matchMediaPrint;
      if(window.matchMedia && window.matchMedia('print').addListener){
```
to
```
      var matchMediaPrint;
      if(navigator.userAgent.indexOf("Firefox") < 0 && window.matchMedia && window.matchMedia('print').addListener){
```
to force the code down the "window.on('beforeprint', beforePrint) path, which does work, but it isn't an elegant fix.  

My lack of understanding of mediaMatch's workings may be contributing to this too.

**Comment by mkoryak** [comment]
Hey, sorry for the delay answering you.

I think that probably what you have is the best we can hope for, unless there is a way to write a feature detection test to see if the match media('print') is broken. I will look into that. The idea I have is to make an iframe and somehow set its media to print and see if a listener fires in there.

**Comment by mkoryak** [comment]
I still need to generate dist/ for this. You can test by using what is in src/

**Comment by mkoryak** [comment]
By the way, I tried doing feature detection for this, but I could not get something that did not open a print dialog - kind of a deal breaker :)
