### ISSUE TITLE
Header sticks to top by default ?

### ISSUE THREAD

**Issue by lakinmohapatra** [mkoryak/floatThead#392]
Hi 
first of all , thanks for this great project. 

I want my table not to stick top. 
Only tbody to be scrollable . 

But when i am applying your plugin , its making it sticky to top. 

Please help 

Also jumping issues found with ios safi chrome .

**Comment by lakinmohapatra** [comment]
In ios , when i select any input box , it jumps down and restores header to original position

**Comment by mkoryak** [comment]
I need jsfiddles reproducing the problems you have. I am not sure I
understand what your problems are.

The more effort you put in explaining, the more I'll put in helping you

**Comment by mkoryak** [comment]
no response.

**Comment by lakinmohapatra** [comment]
I am extremely sorry .
It worked.
It was a mistake from my side.

Please close this.
