### ISSUE TITLE
Question: Are the DOM changes asynchronous

### ISSUE THREAD

**Issue by rr326** [mkoryak/floatThead#394]
Question: When I call `el.floatThead()`, the call returns synchronously. But do the DOM modifications happen asynchronously?

I'm guessing yes, since that would explain a lot. (I couldn't tell by looking at the code.) 

Note: I have some very strange behavior I'm trying to debug, and it's complicated because it is integrated with a Vue controller in an Electron application.  So reproducing is hard. But if I knew it were asynch, it would help a lot. 

Thanks.

**Comment by mkoryak** [comment]
They should be synchronous. BUT, depending on a couple of things, they may appear to be async. 

For example, does the resize event get fired? I know that some frameworks fire that event for whatever reason even when window is not being resized.  I also re-fire reflow on window `load` event. 

Also you have a lot of layers here. I recommend doing the following - comment out all lines of code that have `eventName(` it should not break the plugin on initial load (it will break it later, but you dont care)

https://github.com/mkoryak/floatThead/blob/master/src/jquery.floatThead.js#L990

If you find that your stuff works after commenting out all events, which are by definition async, you know that you have some problem later on synchronizing state when the async stuff happens.

**Comment by mkoryak** [comment]
Let me know how else I can be of help.
