### ISSUE TITLE
CSS can do a sticky header !

### ISSUE THREAD

**Issue by djibe** [mkoryak/floatThead#395]
thead th {
	position: sticky;
	top: -1px;
}
et voilà !

**Comment by mkoryak** [comment]
Yes, but it doesn't work in older browsers, and last I checked it was kinda buggy. I mention this in the project description on GitHub.

**Comment by mkoryak** [comment]
https://caniuse.com/#feat=css-sticky

So it's fine to use if you don't support ie, and only support latest chrome. Basically if you are a Dev that works on heaven's website
