### ISSUE TITLE
floatThead component for angular 5

### ISSUE THREAD

**Issue by sachinshahi** [mkoryak/floatThead#396]
Is there any plan to port floatThead to angular 5. I have found which is for old version https://github.com/brandon-barker/angular-floatThead.

I am trying to create directive similar to floatThead in angular 5.

 Please let me know if there is any suggestions.

**Comment by mkoryak** [comment]
Woah angular is up to version 5 now?!

I cannot help you, I have never used angular 2 or 3 or 4 or 5. If you write a component and use it in prod, I'll link to it from the docs
