### ISSUE TITLE
colgroup is put before caption

### ISSUE THREAD

**Issue by psalaets** [mkoryak/floatThead#397]
I am not aware of this breaking anything, but everything I've read says if a `table` has a `caption`, the `caption` should be the first child of the `table`.

By "everything", I mean

- [whatwg](https://html.spec.whatwg.org/multipage/tables.html#the-table-element)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption)
- [webaim](https://webaim.org/techniques/tables/data#caption)

# Steps

1. Use floatThead on a [table that has a caption](https://mkoryak.github.io/floatThead/examples/caption-tag/)
2. Inspect the dom structure of the table

# jsfiddle

https://jsfiddle.net/psalaets/s74nc0po/5/

# Versions

- browser: Firefox 57.0.4
- OS: macOS 10.13.2
- jQuery 3.3.0
- floatThead 2.0.3

**Comment by mkoryak** [comment]
If everything works on every browser, then I'm not going to go fix it and maybe break something new :)
