### ISSUE TITLE
No dependency of jquery in package.json

### ISSUE THREAD

**Issue by windware** [mkoryak/floatThead#400]
I see that there is no other way to use floatThead besides calling from jquery object but it does not state about jquery in package.json's dependency.

**Comment by mkoryak** [comment]
This is true. 

Was this really a problem for you or are you just being pedantic?

**Comment by mkoryak** [comment]
Most projects that use this or any other _jQuery plugins_ usually are already setup to use a version of jQuery of their own choice. 

So it has never been a problem for anyone in the last 5 years. 

Please submit a PR if you want to spend time on this
