### ISSUE TITLE
After floatThead() the table sorting does not work anymore

### ISSUE THREAD

**Issue by q2apro** [mkoryak/floatThead#401]
I am using a simple table sorter script: https://stackoverflow.com/a/19947532/1066234

However, when applying `floatThead()` to the table, the script does not work anymore.

Is there any chance to get both working together?

- browser: Chrome v63
- OS name: Win 10
- jQuery latest
- floatThead latest

Fiddle: https://jsfiddle.net/xw4046pr/1/

**Comment by mkoryak** [comment]
`getRowGroups` method is your friend:

https://jsfiddle.net/xw4046pr/2/

**Comment by q2apro** [comment]
Nice! But does not sort the first `tr`, see "France" in the table.

**Comment by mkoryak** [comment]
And do you think that floatthead is causing that to happen?

**Comment by q2apro** [comment]
Yes, because without floatThead the sorting of all `tr`s work: https://jsfiddle.net/xw4046pr/3/

**Comment by mkoryak** [comment]
Here, I wrote the code for you:

https://jsfiddle.net/xw4046pr/4/

**Comment by q2apro** [comment]
Fantastic :) Thanks a lot for your help. I couldnt see the solution.
