### ISSUE TITLE
bootstrapTable. when I use showColumns="true" .

### ISSUE THREAD

**Issue by wsy6566** [mkoryak/floatThead#410]
Hello! It's does't work when I set showColumns is true in bootstrapTable.
<img width="1941" alt="2018-03-23 2 23 17" src="https://user-images.githubusercontent.com/10623744/37814627-de6636e4-2ea5-11e8-9443-8704614ff86f.png">

**Comment by mkoryak** [comment]
Thats a pretty picture. 

If you want me to actually help you, code is what I need. I dont know what bootstrapTable is, and I am not going to spend time reproducing your issue, that is your job.

**Comment by mkoryak** [comment]
reopen it when you have a jsfiddle
