### ISSUE TITLE
right to left

### ISSUE THREAD

**Issue by HKhedr** [mkoryak/floatThead#411]
Hello, Right to left table not working

Thank you.

**Comment by mkoryak** [comment]
yes.

You're welcome

**Comment by HKhedr** [comment]
Vertical scroll right to left not working..
any help ??
Thank you.

**Comment by mkoryak** [comment]
Please provide a jsfiddle reproducing the issue.

**Comment by mkoryak** [comment]
I have as much time to work on this as you do, probably less, but there is now support for rtl in here:
https://github.com/mkoryak/floatThead/blob/master/src/jquery.floatThead.js

but only for overflow scrolling and not window scrolling.

**Comment by mkoryak** [comment]
Closing,
Let me know if you need better support for this, and if you are willing to put in a bit more time into asking me to provide it.

**Comment by HKhedr** [comment]
thank you for fast respond and your attention but horizontal scroll still not working..
[jsfiddle](https://jsfiddle.net/hkhedr/0cpzL58j/4/)

Thank you

**Comment by mkoryak** [comment]
I expect the dir attribute on the HTML tag. It only works with internal
scrolling.

Sorry but I can't provide real support for this, there is to much stuff
that needs to change and I do not have time

**Comment by HKhedr** [comment]
added bootstrap-rtl that add dir attribute 

Thank you

**Comment by pgammans** [comment]
I have a fix the horizontal scrolling described by  @HKhedr.
It looks like there is a fix of issues #19 which causes the issue you as seeing.

BTW: the jsfiddle example above is not running in RTL mode, but LTR

An updated version https://fiddle.jshell.net/2tgzoLd3/13 this is using the code from pull request #432

A version of the original jsfiddle with dir=RTL set is https://fiddle.jshell.net/2tgzoLd3/14/
