### ISSUE TITLE
Responsive Table Interoperability

### ISSUE THREAD

**Issue by garethwarry** [mkoryak/floatThead#414]
**Summary:** When creating a responsive table using `display: block` for smaller screens and hiding the thead element, floatThead no longer sets the min-width of the table after resizing to a smaller screen. This causes a horizontal scrollbar to appear. Not sure if this is something I'm doing wrong, or a setting I'm not seeing?

**Link:** https://codepen.io/anon/pen/WzVaWd
I used UIKit to create the responsive table in this example.

Thanks!

**Comment by mkoryak** [comment]
There is no support for this behavior, since at the small resolution your table does not have a thead - and that is one of the requirements of this plugin. 

But you can easily get around that:

https://codepen.io/anon/pen/geVqpO

**Comment by garethwarry** [comment]
Thanks! Sorry if my question was a bit out of scope, but thank you for giving me a workaround. 👍
