### ISSUE TITLE
Images to float above tHead

### ISSUE THREAD

**Issue by SiGroves** [mkoryak/floatThead#415]
Hi Misha
Hope you can help with this.
I have some "thumbnail" images in my table. 
When you hover over the image it expands to show more detail. 
But the image still shows behind the tHead.
How can I pull the image in front of tHead? 
zIndex seems to have no effect.

Example in jsFiddle:
https://jsfiddle.net/3a35b94w/17/

**Comment by mkoryak** [comment]
You are dealing with "css stacking context". Google it if you don't know
about it.
There is not much you can do about it unless you move your images out of
that container on hover

**Comment by SiGroves** [comment]
Turned out to be simple solution.
No need to worry about zIndex on tHead.
Just added position:relative to my .transition style:

.img-zoom {
    -webkit-transition: all .2s ease-in-out;
    -moz-transition: all .2s ease-in-out;
    -o-transition: all .2s ease-in-out;
    -ms-transition: all .2s ease-in-out;
    width: 40px;
    max-width:100%;
}
 
.transition {
    -webkit-transform: scale(5); 
    -moz-transform: scale(5);
    -o-transform: scale(5);
    transform: scale(5);
   border: 0.5px  solid silver;
    
    position:relative;
}
