### ISSUE TITLE
Header Flicker on scroll in IPAD (Window Scrolling)

### ISSUE THREAD

**Issue by Arvn41** [mkoryak/floatThead#417]
Hello mkoryak,

I have one fixed head using following code,

$table.floatThead({
        top: custTop,
        responsiveContainer: function ($table) {
            return $table.closest('.table-responsive');
        }                
    });

it works perfectly well in the browser, am just getting issue while scroll on Ipad, I have use multiple table on same page and scroll to top and fixed head, but when user scroll fast on Ipad all header get flicker till the scrolling stop.

anyone is having solution for the above situation please let me know.

When I check http://mkoryak.github.io/floatThead/ window scrolling has same issue as I described above.

**Comment by mkoryak** [comment]
I have a duplicate open issue about this.
