### ISSUE TITLE
Issue with Bootstrap collapsible Accordion

### ISSUE THREAD

**Issue by bazzacad** [mkoryak/floatThead#419]
I have a Bootstrap collapsible Accordion above my table.
My floatThead position is set to fixed.
When I click on the Accordion to expand/open it, the table header says in the same fixed position, but when I scroll, it then jumps down to it's correct location.
Is it possible to make the table header jump to it's correct location when the Accordion is opened? I thought I could get the "reflow" option to work, but it doesn't.
Here's my jsfiddle showing the issue: https://jsfiddle.net/fw3bx68f/

**Comment by mkoryak** [comment]
did you see #296?

**Comment by mkoryak** [comment]
It needed a bit more love, but basically the solution is the same:

https://jsfiddle.net/fw3bx68f/9/
(it needed an extra style)

**Comment by mkoryak** [comment]
closing as solved. Repoen if something does not make sense
