### ISSUE TITLE
Wrong size header when first loading

### ISSUE THREAD

**Issue by mark1702** [mkoryak/floatThead#420]
Hi! I met a new issue that really need your help.
Now i'm using IE: 11.0.44, Jquery 1.12.1 and jquery.floatThead.js 2.1.2.
When the first time i load my table, just only a part of header (width:100px) was displayed above first row of table. But after i resize my table, it's ok. Sorry can not post my code to jsfiddle now.
Below are some picture about my issue. Could you help me, please? Thank you so much!
_* First loading time:_
![image](https://user-images.githubusercontent.com/38837455/39533925-8267cb44-4e5a-11e8-8432-3b9a5668b04f.png)
-- loading code:
![image](https://user-images.githubusercontent.com/38837455/39534045-d8156240-4e5a-11e8-87c3-da29df8b4878.png)

_* After resize my page:_
![image](https://user-images.githubusercontent.com/38837455/39533963-9987a4c0-4e5a-11e8-8110-e333448e2d27.png)
- And loading code:
![image](https://user-images.githubusercontent.com/38837455/39534075-eb7db7c4-4e5a-11e8-9e44-b12b5eac4d66.png)

**Comment by mkoryak** [comment]
Sorry, nothing jumps out at me from looking at this, and I cant help you without seeing the code. 

does it work correctly in chrome or firefox?

you can always try a hack. after you init the table do something like this:

```js
setTimeout(() => $('#table1').trigger('reflow'), 50);
```

**Comment by mark1702** [comment]
Thank you for your quick response. You're right, follow your guide, i found i a forgot function that can change ccs automatically.
Thank you for your help one more time and have a nice day!
