### ISSUE TITLE
Original header being spoiled

### ISSUE THREAD

**Issue by l736k** [mkoryak/floatThead#425]
Hi, I'm using your script with Bootstrap 3 as follows:

```js
mainTable.floatThead({
	responsiveContainer: function(table){
		return table.closest('.table-responsive');
	},
	zIndex: 2,
	autoReflow: true
});
mainTable.floatThead('reflow');
```

Problem is that once called the first part of the script, the new header is correctly created while the original one is spoiled (it became circa 20px heigher).
The only way to make the original header return to the correct height (and so disappear under the dynamic header) is to use the reflow method.

Am I missing something or doing something wrong?

**Comment by mkoryak** [comment]
Jsfiddle is required if you want code help.

I don't know what you after doing wrong or the plugin is doing wrong
without seeing code

**Comment by mkoryak** [comment]
please reopen if you ever come back and have a jsfiddle
