### ISSUE TITLE
ScrollTop change not work after a destroy

### ISSUE THREAD

**Issue by vinnygambiny** [mkoryak/floatThead#426]
I need to replace the content of the parent div of the table and keep the scroll position.

So I get the scroll position
`var scrollTop = $('.wrapper').scrollTop();`
Then I destroy
`$('table').floatThead('destroy');`
Replace the content and set the scrollTop
`$('.wrapper').empty().append(...);
$('.wrapper').scrollTop(scrollTop);`
And finally replace the thead
`$('table').floatThead({scrollContainer: function($table){return $table.closest('.wrapper');}});`

But the scrollTop don't work. If I remove the "destroy", the scrollTop work, but have two thead in the html...

https://jsfiddle.net/ymqx201s/19/

**Comment by tom-seegreen** [comment]
Verify Your Email


	Verify Your Email
	
		Hey vinnygambiny, 
		Please verify your email address in order to login to:
		http://portal.seegreen.uk/support/.  If that was a mistake or you
		sign up for the account, you can safely delete this email.
	
	
		To verify your address, please click or enter the following
		URL in your web browser- http://portal.seegreen.uk/support/v1/verify/72345:1f47d03d-8062-42e5-a0b6-237e92015bc4:1096100

**Comment by mkoryak** [comment]
why not put the scrollTop setting after you create the plugin like this:
https://jsfiddle.net/ymqx201s/22/
??

**Comment by vinnygambiny** [comment]
The init call is make by a other call... maybe a can change it.

They a way to know if the table is already be init ?

**Comment by mkoryak** [comment]
Yes, there are many ways to know if init has happened. You can look for a `colgroup` element in the table, you can mark the table that has been initialized by setting a data property on it etc...

**Comment by mkoryak** [comment]
There is a better way to do what you are doing I think. You want to update the table with some stuff, but what you really want to do is not replace the table because that breaks the plugin. Maybe you wanted to do this:

https://jsfiddle.net/ymqx201s/35/

notice that this solution does not care about scrollTop at all.
