### ISSUE TITLE
Border top removed in Firefox

### ISSUE THREAD

**Issue by siccovansas** [mkoryak/floatThead#428]
The top border of the header of the table is removed when I use floatHead on a Bootstrap table with the `table-bordered` class. This happens in Firefox but not in Chrome. You can see the problem in this [floatHead example](http://mkoryak.github.io/floatThead/examples/bootstrap3/), but I also reproduced it using this [jsfiddle](https://jsfiddle.net/16a5uqcx/).

The `table` element has a `border-top-width` of `1px` and `border-bottom-width` of `0px` when you remove `$(".table").floatThead();` from the jsfiddle, but when you add floatHead it flips those values.

I think it is related to the suggestion to add
```
table.floatThead-table {
    border-top: none;
    border-bottom: none;
    background-color: #FFF;
}
```

I removed the `border-top` and `border-bottom` lines and the table looks fine again. I'm not sure if it messes anything else up though.

**Comment by mkoryak** [comment]
Yes, the suggestion is to set the border top and bottom to none.  I dont remember why I did that. You can do whatever you need to do to make it look right. The plugin does not require any css to work properly.
