### ISSUE TITLE
Table head moves with horizontal scroll on chrome with direction : rtl style

### ISSUE THREAD

**Issue by Vadp** [mkoryak/floatThead#430]
as mentioned in the title, the table head moves when scrolling horizontally (only on chrome)
when the table container has the style "direction : rtl"

https://jsfiddle.net/6x1z4gpq/

**Comment by mkoryak** [comment]
The rtl support is really bad, it only looks at HTML element dir attribute.

**Comment by mkoryak** [comment]
Can you put a dir attribute on the HTML element and see if that solves it?

**Comment by mkoryak** [comment]
No response
