### ISSUE TITLE
When using position: "absolute" W3C validator sees invalid html in table.

### ISSUE THREAD

**Issue by ChristianHausner** [mkoryak/floatThead#431]
Hello,

I'm using floatThead with absolute positioning (`$('table').floatThead({position: 'absolute'});`) and when I tried to validate the generated DOM with W3C online validator it raises errors like:

> Table column 1 established by element “col” has no cells beginning in it.

The generated `<table class="floatThead-table">` inside the `<div class="floatThead-container">` does not contain a `<thead>` as long as the table head is not floated and this seems to be an invalid table in terms of HTML5.

See: https://jsfiddle.net/y1prnw30/5/ for a small example.

But when using position: "fixed", the `<table class="floatThead-table">` contains the `<thead>` and valid HTML is generated.

I'm using Firefox 60.6.1 on Windows 10 and floatThead 2.1.3 with jQuery 3.4.0.

Is it possible to generate valid HTML with absolute positioning? 
Thanks a lot...

**Comment by mkoryak** [comment]
Nope, It is not possible. I am not actively developing new features here and this would require some effort. Sorry about that.

**Comment by mkoryak** [comment]
Eh, ill reopen this. Maybe ill fix it someday when I have nothing better to do.

**Comment by mkoryak** [comment]
anyway, why do you care about what w3c validator thinks?

**Comment by ChristianHausner** [comment]
Good question... I think its easier for browsers to render the page if it is valid html. But I don't mentioned any rendering issue with common browsers. ...now when I think about, it sounds somehow like a pure  academic problem.

**Comment by mkoryak** [comment]
Ok. Then I'm going to close this. This plugin has been used in prod in hundreds of places and it works well enough for people since I don't get many open issues :)
