### ISSUE TITLE
Header size too big when zoom out

### ISSUE THREAD

**Issue by huzjakd** [mkoryak/floatThead#433]
I encountered an issue with the header when I used this plugin with jQuery DataTables.
When You would zoom out to say like 30%, the header width would be too big and partially cover the vertical scrollbar.
Not a big issue but still an issue.
I saw that that the reflow does get triggered on every zoom but header size gets calculated wrong. Specifically, the scrollbar width is calculated wrong.
I went into the code and saw that you get the scrollbar width on plugin init in this function scrollbarWidth(), but you don't call that function on every reflow.
So my solution was to duplicate the function and call it on every reflow too, at the beginning of this function: calculateScrollBarSize(), with: scrollbarWidth = scrollbarWidth();
This fixed my issue.
Don't feel like making a fiddle, but it shouldn't be that hard to reproduce for you or somebody else.
Anyway just thought I'd leave this here in case you want to update your plugin or somebody encounters the same issue.

**Comment by mkoryak** [comment]
You don't feel like making a fiddle and I don't feel like reproducing it
