### ISSUE TITLE
Floating a thead inside of a bootstrap dialog

### ISSUE THREAD

**Issue by skeets23** [mkoryak/floatThead#438]
If the table is within a bootstrap modal, it doesn't render properly (even after manually triggering the "reflow")

jsfiddle:
https://jsfiddle.net/skeets23/qjcghou9/11/

... the answer here may be "Why are you trying to put a huge table inside of a bootstrap modal? Don't do that.".... but I thought I'd open an issue to see if maybe I was just doing something wrong (besides the obvious design flaws of having complex tables inside dialogs 😅 (It's an internal web app, not accessible to the public.))

**Comment by mkoryak** [comment]
You have a few things wrong here:

1. You have a lot more tbody tags then I would expect. Maybe a bad paste? Why is there a tbody around every row? This itself is legal, but probably not intended?
2. table-b does not exist, so why is there code to run the plugin on it? 
3. You specify a scroll container, but there is no scroll container. The window is what scrolls. 

And the fix is to use fixed positioning, and also supply a zindex that pops the floated header above the modal:

https://jsfiddle.net/kojaw0sc/1/

**Comment by skeets23** [comment]
1 - I was just trying to emulate the table in my project, that has a lot of tbody tags (that group every 2 rows together)

2 - There was a `#table-b`, it was outside of the dialog, just to make sure that I was including all the needed javascript correctly. It looks like you removed it in your fiddle.

It does look like using "fixed" positioning solves the problem, although the header is not present until after scrolling? 

I can trigger the "scroll" event upon the dialog opening, but it does make the table jump down a bit.

Also, I discovered that if you scroll down inside the modal while it's still "fading in", this happens:

![09_07-32-943x445-e48ab822e3](https://user-images.githubusercontent.com/13846271/60846899-e3223f80-a21b-11e9-9402-efd9ed0f1b2e.png)
 (it's floating a few pixels down from the top, the more you scroll while the dialog is animating, the bigger the gap. This screenshot was taken from the fiddle you provided.)

This can be solved with:
```
$(".modal").on("shown.bs.modal", function() {
	var reinit = $("#table-a").floatThead("destroy");
	reinit();
});
```

although there's still the jump when the header snaps into place after the modal's opening animation.

I did find a work around by making the modal invisible and removing the animation temporarily so it can be opened, initialize the floatThead, and then close it so it's ready the next time it's opened (pretty messy, but it does seem to work):

[fiddle](https://jsfiddle.net/skeets23/fde2460L/9/)
```
$(".modal").on("shown.bs.modal", function() {
	$(".modal").trigger("scroll");
} );

$(".modal").css({visibility:"hidden"});
$(".modal").removeClass("fade").modal("show");


$("#table-a").floatThead({
position:"fixed",
zIndex:433333,
scrollContainer:function(){
return $("#exampleModal");
} 
});

$(".modal").css({visibility:"visible"});
$(".modal").modal("hide").addClass("fade");
```

**Comment by skeets23** [comment]
It looks like floating a thead in a dialog with horizontal scrolling also causes issues [fiddle](https://jsfiddle.net/skeets23/1z46gt7j/3/)

![09_08-19-709x414-c1564028e4 1](https://user-images.githubusercontent.com/13846271/60848621-47480200-a222-11e9-8772-27b8d5c41c39.png)

Upon scrolling, the header goes out of the modal bounds, and also horizontally scrolling doesn't work correctly with the header (I believe this is because "absolute" positioning is needed when it's in a container that scrolls horizontally).

It all works beautifully outside a dialog, with absolute positioning [fiddle](https://jsfiddle.net/skeets23/1z46gt7j/6/)

**Comment by mkoryak** [comment]
So, I think you are running up into one issue that is a `wont fix`, that is, you want to control vertical and horizontal scrolling via two different containers. This is not supported because it would require a near full rewrite of the plugin :P

**Comment by mkoryak** [comment]
You could do the sane thing and put a max height on your dialog and made a div in there with overflow: auto that contains the table. If you do that, you will have scroll bars inside the dialog, and everything will work because your design will no longer be insane :)
