### ISSUE TITLE
Table Header Overlaps First Row

### ISSUE THREAD

**Issue by burgoyne** [mkoryak/floatThead#442]
I have created a table where you can hover on a cell, and that row and column will highlight. I am also trying to implement floatThead, but my header always overlaps the first row. 

I have created a fiddle of a basic table, that still shows this error. I assume it is caused by my JavaScript? 
https://jsfiddle.net/7awbfq9h/4/

Does anyone have a suggestion to get this working? Thanks in advance!

**Comment by mkoryak** [comment]
do you need those empty colgroups?

The plugin uses a colgroup with col elements for cell alignment and having
multiple colgroups breaks it.

https://jsfiddle.net/cbsuwz5y/

**Comment by mkoryak** [comment]
I should have read your question more carefully.
You need those things, but you probably want to use a single colgroup with
col elements, that way it doesnt break the plugin:

https://jsfiddle.net/cbsuwz5y/1/

sadly, floatthead mutates the table and creates two tables. You will need
to inspect the dom and change your javascript to do something different.

**Comment by burgoyne** [comment]
Thank you for such a quick reply. I will change up my JS to work with this plugin.

**Comment by mkoryak** [comment]
like this:

https://jsfiddle.net/cbsuwz5y/4/

**Comment by burgoyne** [comment]
Thank you so much! It is working great now. Your plugin is amazing.
