### ISSUE TITLE
Center Floating Head in Container

### ISSUE THREAD

**Issue by burgoyne** [mkoryak/floatThead#443]
So I am attempting to center my table inside it's div. I am centering the table by setting margin: 0px auto. In my project, the table is centered, but the header is not (it is off by 35px, which is the size of padding on my container div). 

After inspecting it, it seems that the table element that floatThead creates for the header, is outside my container div... The actual table is inside though. So this results in my table being properly centered, but my header being slightly offset to the right. 

Here is an image showing the offset (data blocked out):
![table head padding](https://user-images.githubusercontent.com/17754882/64627331-68ada180-d3bd-11e9-9b5c-1b6bd3fe0c33.png)

I attempted to duplicate the issue with a fiddle, but it works fine! Has anyone had this issue where they're newly generated table for the header is outside the containing div? 
https://jsfiddle.net/skx1u94d/1/

**Comment by mkoryak** [comment]
Does this issue look like the other open issue?

**Comment by burgoyne** [comment]
I noticed that other thread, but it does not seem to be the same issues. My problem seems to be caused by the generated table being placed outside the container. I assume it is a bug, potentially a configuration issue.

**Comment by burgoyne** [comment]
Looking more into it, it does seem to be the same issue. I am going to try to resolve this based off of those answers.

**Comment by mkoryak** [comment]
duplicate of #437
