### ISSUE TITLE
Support hidden columns in tables that have an existing colgroup

### ISSUE THREAD

**Issue by Bibendus83** [mkoryak/floatThead#445]
Hello!

I have a weird case where I have to hide a certain column but I need to keep it into the HTML.
Adding a display none on the colgroup caused wrong width calculations on the floating thead.

![image](https://user-images.githubusercontent.com/4517370/65342221-9622f800-dbd2-11e9-95a6-18be1d6742a7.png)

Here is the JSFiddle to reproduce it
https://jsfiddle.net/Bibendus/Ldmyrvb0/5/

I made a quick fix for the issue but I don't have a lot of time to review the entire code and check for possible bugs so I'm sharing my solution hoping it's of any help

in the reflow() function I added this piece of code
inside this for cycle
```
            for(i=0; i < numCols; i++){
              $headerCells.eq(i).width(widths[i]);
              $tableCells.eq(i).width(widths[i]);
              // MY FIX - START
              if ($tableCells.eq(i).is(':not(:visible)')) {
                $headerCells.eq(i).css('display', 'none');
              }
              // MY FIX - END
            }
```
This should add a display:none to the colgroup when the existing col of the original table is hidden

**Comment by mkoryak** [comment]
this is actually a bug around my poor support for `<colgroup>`. The workaround which may not work for you is to not use colgroup:

https://jsfiddle.net/ps9knrbj/

Do you _really_ need it ? :)

**Comment by Bibendus83** [comment]
It doesn't hurt to have the bug fixed :)

**Comment by mkoryak** [comment]
I pushed that fix to master. You should try it out and see if works any better.

Why are you using `col`s though?
