### ISSUE TITLE
floatThead does not take into account parent width

### ISSUE THREAD

**Issue by decadence** [mkoryak/floatThead#447]
Firstly thanks for the great plugin!

If table parent has `overflow: auto` and table is wider than parent so floating thead does not take into account parent width and show itself on the full width.
https://jsfiddle.net/q63e1n5r/

Can it be fixed somehow? I expect thead horizontal scroll to be synchronized with table scroll and does not overflow parent width.

**Comment by mkoryak** [comment]
use absolute position mode 

https://jsfiddle.net/p9xbhtrL/

`$("table").floatThead({position:'absolute'});`

**Comment by decadence** [comment]
Thanks!
