### ISSUE TITLE
only in IE and being RTL columns are not aligned  

### ISSUE THREAD

**Issue by eassa** [mkoryak/floatThead#448]
only on ie (i tried with version 11) and when using the RTL (Hebrew language) this problem occure.
i checked and found out that in class="floatThead-container" the transform translateX is incorrect 

![image](https://user-images.githubusercontent.com/14801394/66127617-c9af4a80-e5f4-11e9-99f7-84e6cf91c1a3.png)

**Comment by mkoryak** [comment]
This is going to be hard for me to fix, because at present I do not have access to IE11. 

Can you reproduce this on any other browsers?

**Comment by mkoryak** [comment]
I see 3 extra columns on the right of the table header after the filter column. Was this table configured properly for IE? 
https://mkoryak.github.io/floatThead/examples/row-groups/

**Comment by eassa** [comment]
also on firefox it is the same (only when i have many columns that i need a scrollbar ), (it is the translateX  coordinates are incorrect i think )
       `       var transform = 'translateX(' + pos.left + 'px) translateY(' + pos.top + 'px)';`

**Comment by mkoryak** [comment]
Ok, in that case, can you create a jsfiddle to reproduce this issue. I cant
fix a screenshot :)

**Comment by mkoryak** [comment]
Doesn't look like you're coming back.
