### ISSUE TITLE
Bootstrap tooltips displaying in wrong position

### ISSUE THREAD

**Issue by utilmind** [mkoryak/floatThead#455]
Hello! I have created a page which demonstrates the problem with bootstrap tooltips:

http://utilmind.com/demos/2020/bug-floatthead-tooltips/

I'm going to investigate the problem and will try to find out a solution. But in case if this known issue (despite I did not found it in the list of closed issues), please let me know!

Thanks!

**Comment by mkoryak** [comment]
This is because the floated header lives inside of a div with overflow:hidden, and the tooltip does not like that.

try this, find `.floatThead-container` and remove the overflow prop, now your tooltips magically work, and the plugin does not!

if you want more help, please relocate this to a jsfiddle or jsbin where I can edit the code to provide you with a workaround.

**Comment by utilmind** [comment]
> if you want more help, please relocate this to a jsfiddle or jsbin where I can edit the code to provide you with a workaround.

Misha, thank you! I have copied the code to https://jsfiddle.net/utilmind/r4jkyx93/ and I will greatly appreciate your help!

**Comment by mkoryak** [comment]
Thank you for a quick response, I will look at it tomorrow while I wait for
something to compile :)

**Comment by mkoryak** [comment]
actually, does this solve your problem:

https://jsfiddle.net/7db92m54/

**Comment by utilmind** [comment]
> actually, does this solve your problem:
> Using `position: 'absolute'`
> https://jsfiddle.net/7db92m54/
> 
> No it does not.. only when you have not scrolled into the table. I think we are on to something here..

Yes. right :) It looks much better, but, tooltips still out of viewport when `thead` is in "sticky" state.

![KHir3btsZq](https://user-images.githubusercontent.com/5224442/79814279-d191ca80-834b-11ea-9f81-2a3980367371.png)

**Comment by mkoryak** [comment]
what version of bootstrap are you using? I think they are having troubles
with my positioning

**Comment by utilmind** [comment]
Latest version, 4.4.1 (see the code uses following external script: `<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>`)

And I found that actually when tooltip looks like it works correctly, it does not, demonstrating strange behavior.

By default Bootstrap tooltips should be displayed above the the HTML element with the tooltip, except cases when there is not enough space above.

Here is the demo with another tooltip, over floatThead link
https://jsfiddle.net/utilmind/2o70z8m4/

![IxAZXMZnV4](https://user-images.githubusercontent.com/5224442/79814846-3bf73a80-834d-11ea-8992-232673d3d376.png)

**Comment by mkoryak** [comment]
I looked at this for a while. I would say that the bug is how bootstrap places the tooltip on transform: translated elements. I dont think that there is much that can be done from my side to fix things. 

you can try not using floatThead and use position: sticky. 
sorry I cant help you more.

**Comment by utilmind** [comment]
> you can try not using floatThead and use position: sticky.

Yes, this is what I'm using now, but sticky does not works when table inside of the ".table-responsive" container.

Ok, thanks anyway! Actually I originally thought that it's well known problem or it can be easily fixed. Then I will play with it and try to fix myself. I will post my solution here in case if I will have a luck to fix it.

**Comment by utilmind** [comment]
I have fixed this problem, changing "`overflow-x`" to "`overflow`" in line #55 of jquery.floatThread.js

I did not tested, maybe this fix leads to some side effects, but it's completely fixed my problem. Here is the demo: http://utilmind.com/demos/2020/bug-floatthead-tooltips/

**Comment by mkoryak** [comment]
Nice!

It is not `overflow:hidden` for dropdowns that live inside the header (and do not append themselves to body like this tooltip does). 

I think that this is a perfectly reasonable fix for your use case.

**Comment by richieri** [comment]
Thanks, this also helped me a lot :)
