### ISSUE TITLE
Fix the first column (on the left) and the header of the table (on top)

### ISSUE THREAD

**Issue by q2apro** [mkoryak/floatThead#456]
I could not find any information in the docs how we can fix the first column (on the left). Next to fixing the header of the table (on top).

This would be practical for huge tables, like user lists, to still be able to see what data belongs to what user.

JSFiddle: https://jsfiddle.net/kai_noack/ynokx952/6/

**Comment by mkoryak** [comment]
its not in the docs, but i do mention it in the readme. 2nd bullet point here:

https://github.com/mkoryak/floatThead#things-this-plugin-does-not-do

**Comment by q2apro** [comment]
Not a clean workaround but it works to keep the first row visible:
```
	.evaltable td:nth-child(1) {
		position:sticky;
		left:20px;
	}
```

**Comment by mkoryak** [comment]
I wouldn't want to see something like that in prediction.
