### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by jmariller** [mkoryak/floatThead#457]
Hello,

Would it be possible to add TypeScript definitions for this library? I find floatThead really great, the only thing missing would be those definitions.

Many thanks!

**Comment by mkoryak** [comment]
Pull requests are welcome!

I think I saw something for it in DefinitelyTyped

**Comment by jmariller** [comment]
Done, please see #458.

Most of the credit should go to @InkUisitor who had posted a proposal in DefinitelyTypes which I used as basis for the PR.

**Comment by mkoryak** [comment]
I took a closer look to the TS defs, and they looked incorrect. I made an update, can you check if they work or if my bad typescript knowledge is wrong:

https://github.com/mkoryak/floatThead/commit/f80599961a142aaee0048dede4e459bcef48408f#diff-a174240128da7329291c196cd78bc2bf

**Comment by jmariller** [comment]
Thanks for the update - your adjustments are fine!

Two more things:
-  I picked up the wrong attribute for `package.json` to point at TypeScript definitions file :man_facepalming: sorry about that. It's `types`, not `type` - opened a new PR, see #460.
-  I believe you need to run `build` once so the definition file gets copied into `dist`

**Comment by mkoryak** [comment]
Published  2.2.1. Let me know if it works.

**Comment by jmariller** [comment]
Works fine now, thank you very much!
