### ISSUE TITLE
Floating thead hides its origin on overscroll? 

### ISSUE THREAD

**Issue by steffenhansendev** [mkoryak/floatThead#459]
Thanks for an awesome plugin!

I've made the Angular application at www.karakterraes.dk. It is starting to come together but while testing it on my iPhone with Safari, I get this bug (see screen dumps below), that I do not know how to fix. When I scroll back to the top of the main table and Safari does it's overscroll bounce, what seems to be an extra thead with no content appears and scrolls over the top over the thead that I have stuck below the navigation with the floatthead library. A .row div containing the .table-responsive div clears the navigation bar in the top by means of padding equivalent to the height of the navigation bar.

jsFiddle: [https://jsfiddle.net/dxq72bmL/1/](https://jsfiddle.net/dxq72bmL/1/)

It's easier to see at my url though. 

![on init](https://user-images.githubusercontent.com/60031751/82743352-8ca5ed00-9d6a-11ea-8caa-1c95f919eccc.PNG)
![on scroll](https://user-images.githubusercontent.com/60031751/82743353-8fa0dd80-9d6a-11ea-999e-229909ebcf0f.PNG)

Any help and/or hacks would be very much appreciated. I'm a CS student that has just started to get into frontend development too, so please excuse my ignorance.

**Comment by mkoryak** [comment]
Sure I'll take a look after the US holidays. Thanks for a detailed description.

**Comment by steffenhansendev** [comment]
I noticed that iOS Safari is not supported after posting this, but it goes for Chrome on iOS as well.

**Comment by steffenhansendev** [comment]
To hack this for a tomorrow's upcoming release, I've set margin-top: -1000px on the .row that contains the .col with the .table-responsive. To compensate, I've placed an empty tr with height: 1000px before my actual trs. The 1000 pixels get truncated somehow, so you will still be able to see the bug on the live site, you just have to pull down a bit harder with your finger on the screen.

**Comment by mkoryak** [comment]
Hey, sorry, I misread your bug thinking this was osx, but you said iOS! I dont have an iphone to test this one, so I cannot help you :P 

Also even if I did, debugging on one or an emulator is a very horrible way to spend one's free 
time.

iOS chrome is actually using the Safari renderer engine (because of strict apple guidelines on how things should look on its platform), so you can think of it as the same thing. 

My only advice is to try `overscroll-behavior:contain` on the body / scrolling area
https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

**Comment by steffenhansendev** [comment]
"Also even if I did, debugging on one or an emulator is a very horrible way to spend one's free
time." – Yes indeed! :D I have to deploy the application to the server every time I want to try out a new way of fixing it.

`overscroll-behavior:contain` is not supported by Safari on iOS (yet?). I've put it in place though, hoping Safari developers will get their shit together soon :D 

The negative margin-trick helped to mitigate it quite a lot, so I guess I'll leave it as is for now.
