### ISSUE TITLE
Request: add extra class to the top floated element when its active

### ISSUE THREAD

**Issue by arkid** [mkoryak/floatThead#461]
Just an idea that would have helped me if it was possible out of the box;

It would be really useful for external css styling if when the table header becomes sticky an additional class is added to the code that the function produces in the dom for the sticky header (ie the same element with the class floatThead-container).

Btw, I've seen the example of the 'floated' event at http://mkoryak.github.io/floatThead/  
So kind of like that but by default and on the floated header, not the original main table as that example does.

**Comment by mkoryak** [comment]
Ok, you can do that with what already exists like this:
```
var $table = $('table.demo2');
$table.on("floatThead", function(e, isFloated, $floatContainer){
    $floatContainer.toggleClass("floated", isFloated);
});
$table.floatThead(...);
```

Does this work for what you want to do or did I misunderstand your question?

**Comment by arkid** [comment]
Ah excellent yes thats what im after yes.  I just thought it could be nice also to add it by default to this element too.

**Comment by mkoryak** [comment]
I would rather not add any functionality to the plugin that is already
supported by it's API.
