### ISSUE TITLE
Compatibility with table sorting plugins ?

### ISSUE THREAD

**Issue by arkid** [mkoryak/floatThead#464]
This plugin [Tablesort](https://github.com/tristen/tablesort) allows dynamic sorting of columns on a traditional html table.

I imagine this may be highly problematic to integrate with floatThread although I'd love to be proven wrong.

Testing out the box Tablesort breaks when you then enable floatThread on the same table.   Tableshort attaches itself by default to your real table so the arrows for the table header scroll off the page and are not within the separated table header that floatThread has made in the DOM.

Is this worth pursuing?  Have others tried something like this?   Any feedback appreciated.

**Comment by mkoryak** [comment]
Any table sorting lib will work if that lib caches the table contents on init and does not attempt to reselect them every time you click a header. 
You should also search past issues for 'sort'. I found this in one of them:  

https://jsfiddle.net/xw4046pr/4/

**Comment by arkid** [comment]
Thanks for confirming.  I seem to have this running, should anyone want to use a nice [table sorting plugin](https://github.com/tristen/tablesort) that I can recommend!

https://jsfiddle.net/arkid77/7r9zgsh3/15/
