### ISSUE TITLE
Wrong setHeaderHeight behaviour

### ISSUE THREAD

**Issue by Warmbellycat** [mkoryak/floatThead#465]
Hello!
In some cases underlaying thead gets wrong height.
In my case i have <div aria-hidden="true" class="kv-thead-float"> with header row and filter row (i'm using Yii2 kartik/gridview)
and table with data after that. Thead at table gets wrong height(110px instead of 130px of div with filter).
I have try to debug and found, that function setHeaderHeight() sets wrong value, that value comes from:
`
        $header.children("tr:visible").each(function(){
          headerHeight += $(this).outerHeight(true);
        });
`
As result div partialy overlaps underlaying table data (look like first row of table slides under the div with filter)
This bug appears in Edge, Chrome, but not in FF.
Sorry, but i can't show my code (due to NDA).
Version of floatThead is 2.1.3, jq version 3.4.1

**Comment by Warmbellycat** [comment]
Hmm... More debug - more strange things... Looks like outerheight returns correct value. Something modifies DIV inline style after and adds
`
transform: translateX(295px) translateY(195px);
`

**Comment by Warmbellycat** [comment]
More interesting...
`
 $floatTable.append($header); //append because colgroup must go first in chrome
`
At this line styles of DIV was overwritten, but on next step old styles come back with appended transform:translate.

**Comment by mkoryak** [comment]
Sorry, but without seeing some code that reproduces this somewhere, I can
only say "good luck".

**Comment by Warmbellycat** [comment]
Ok. I'll try to do docker environment for reproduce this problem.

**Comment by mkoryak** [comment]
Why do you need a docker? Isn't this just some html and javascript? If you
rip out the table in question and css styles that apply to it, you should
be able to reproduce this in theory.
Or maybe your company will let me sign an nda and take a look at it
somewhere (as long as that is simpler for everyone)

**Comment by mkoryak** [comment]
Also let's try this: 
Get your table into there bad state, then save the webpage to disk and email me it, after you remove all the private stuff. Obviously the table should still be "broken". I maybe be able to figure out your problem just by looking at the html. My email is sourcecod at google dot com. Yes the E is missing. 
This maybe easier then bringing up a docker, which sounds complicated and I don't really understand how it will help me look at your issue.

**Comment by Warmbellycat** [comment]
> Also let's try this:
> Get your table into there bad state, then save the webpage to disk and email me it, after you remove all the private stuff. Obviously the table should still be "broken". I maybe be able to figure out your problem just by looking at the html. My email is sourcecod at google dot com. Yes the E is missing.
> This maybe easier then bringing up a docker, which sounds complicated and I don't really understand how it will help me look at your issue.

I'm backend-developer, docker - easy way to reproduce full env with bug for me=)
Ok, i'll save page, remove private data and will send to email.

**Comment by mkoryak** [comment]
I have not seen any email from you. Please message here when you send it so it doesnt get lost

**Comment by mkoryak** [comment]
I have not heard for you in 2 weeks. Reopen this issue if you decide that you still need help.
