### ISSUE TITLE
Browser search doesn't scroll to position of result

### ISSUE THREAD

**Issue by ankitsam** [mkoryak/floatThead#467]
When there are multiple tables with floatThead, and searching for text in thead, the browser search feature is unable to scroll to the position of thead of the matched result.
- Steps to reproduce
- Go to [https://jsfiddle.net/6fuLmjyb/ ](https://jsfiddle.net/6fuLmjyb/ )
- Use the browser search feature to search for "whisper".

**Comment by mkoryak** [comment]
The default for window scrolling is `fixed` uses position. This takes the element out of the document flow and so the browser doesnt know how to scroll to them. If you want search to work you must use `absolute` positioning like this:

https://jsfiddle.net/hqLyxn3e/

```js
var $table = $(".table_demo");
$table.floatThead({
    position: 'absolute', // <--- You need this!
    responsiveContainer: function ($table) {
        return $table.closest(".table-responsive");
    },
});
```

**Comment by ankitsam** [comment]
Works, Thank you :pray:
