### ISSUE TITLE
Could you please provide an example in React

### ISSUE THREAD

**Issue by leonwebdev** [mkoryak/floatThead#480]
- Could you please provide an example how to use `floatThead` in React? Because I would like to use this package to make my table header sticky on window top, but the table only will be rendered after an axios request from backend, so I would love to ask for help how to use this package in React.

**Comment by mkoryak** [comment]
No, I can't because I don't use react. Generally speaking though, this
plugin and react will fight each other because they do not expect what the
other one is doing. I suggest that you don't try to make this work with
react unless you like to suffer.

**Comment by leonwebdev** [comment]
Thank you for replying, additionally this plugin is amazing, I use some tricks (setTimeout) to enable this plugin and it works, but it is not a solution for a stable production. Thank you for your fabulous work anyway.
