### ISSUE TITLE
Replacement thead height height larger than original

### ISSUE THREAD

**Issue by deep42** [mkoryak/floatThead#52]
Don't know if there is a specific problem on my end, but the replacement thead for the original table has a bigger height than it should. In my case thead has 24px, but the actual th, that has no borders, just padding, has 20px.

So, I changed the following variable in setHeaderHeight():
var headerHeight = $header.find('th').outerHeight(true); (instead of $header.outerHeight(true))

In initially thought to keep the bigger height, because it looks better, so I added the following line in the same function:
$floatTable.find('thead > tr').height(headerHeight);

**Comment by vinika02** [comment]
Please try this. It's worked for me

      var $table = $('table.table-wages');
            $table.floatThead({
                scrollingTop: 0,
                useAbsolutePositioning: false,
                scrollContainer: function($table){
                    return $table.closest('.table-wages-container');
                }

            });
   // try to resize table thead. tr
   $(".size-row,.floatThead-col").css("height", '48px');

**Comment by mkoryak** [comment]
This example uses options from version 1.x.x,
Though this issue is 5 years old, so maybe that's ok
