### ISSUE TITLE
Header sync is off on a wide table

### ISSUE THREAD

**Issue by billsaysthis** [mkoryak/floatThead#56]
I have a table that can get very wide, dozens of columns and around 4000px wide, and am seeing issues. 
- Many column headers are never visible, due to the way the width of the generated floatThead-container div is calculated and the use of overlay: hidden.
- Scrolling horizontally (by dragging the scrollbar, for example) often doesn't move the headers, scrolling vertically triggers that.

An additional issue, not with the header but the content, is that the rightmost content column is cutoff by the vertical scrollbar--that is, the rightmost 15px or so are overwritten by the scrollbar. On a Mac you may need to go into System Prefs | General and change the Show scrollbars setting to Always show in order to see this.

I've done minimal configuration, as shown here:

``` javascript
  var $table = $('.aggregate-records-table-view').find('> table');
  if ($table) {
    $table.css('table-layout', 'fixed');
    var scrollTop = $('#aggregate-records-viewer').offset().top;
    $table.floatThead({
        scrollingTop: scrollTop,
      scrollContainer: function() { return $('#aggregate-records-viewer'); },
      useAbsolutePositioning: false,
      cellTag: 'td'
    });
  }
```

**Comment by helloworlder** [comment]
I'm using with datatables, and when I horizontally scroll to the right, then sort by one of the columns, the floating header moves into the incorrect position. Not sure if it's a related issue.

I tried  $(window).trigger("resize")  on the datatables fnDrawCallback callback which seems to address the issue. I think it triggers something in the floatTHead internals but really have had no time to find out.

**Comment by mkoryak** [comment]
hello fellow cat avatar,
there is a chance that this plugin no longer supports the latest version of datatables becaused they changed their event api. The last version i tested it on was datatables 1.9.

There should be an event triggered on sort by datatables on the table instance. this plugin listens to that that event and reflows itself:

https://github.com/mkoryak/floatThead/blob/master/jquery.floatThead.js#L749

either the event no longer exists or my impl of `isDataTables()` is no longer working.

I also dont have time to build out a whole datatable install just to test this, so maybe we can meet half way - you provide the jsfiddle with your bug, and ill fix it. Ill create a separate issue for this
