### ISSUE TITLE
Support for printing tables

### ISSUE THREAD

**Issue by dianams** [mkoryak/floatThead#68]
Hello!

This is a really nice and useful plugin. I have implemented it with no problems.

But I need to print the tables in paper. I'm currently working on a css for printing and I don't have idea how to deactivate this plugin when printing... Can you please let me know how to do this?

Thank you very much!!!

**Comment by Bitmapped** [comment]
I have a partial solution. This code works in current versions of Chrome, Firefox, Edge, and IE.

In Firefox, Edge, and IE, floatthead is turned off when the printing starts (so the page prints correctly) and turns back on when printing is done. In Chrome, it turns off when printing occurs. I wasn't able to get it to turn back on correctly.
`window.matchMedia("print").addListener(function() {$table.floatThead('destroy');})
window.onbeforeprint = function() {$table.floatThead('destroy');}
window.onafterprint = function() {$table.floatThead();}`

**Comment by mkoryak** [comment]
interesting. ill have to see why it doesnt work. If this solution works, it would be a pretty big win and i will integrate it into the plugin

**Comment by mkoryak** [comment]
I dont have time to roll this into the plugin right now, but this works:

```js
var fn = function(){ 
  $('table').floatThead('destroy'); 
  fn = function(){ 
    $('table').floatThead();
  }
}

window.matchMedia("print").addListener(function(){ fn() });
```

it can be fixed to work more than once, and be less hacky, but this was my 5 minute attempt to get it working.

**Comment by mkoryak** [comment]
it doesnt appear to work in ie11, but it works in chrome. im going to put this one to bed. if anyone can see any issues with my impl so that it can be made to work in ie11, please let me know

**Comment by Haprog** [comment]
I'm using floatThead version 1.3.2 from cdnjs, so I haven't tried the fixes above yet, but (at least for my case) I only needed to add this little bit of CSS to be able to print the table so that even the table header looks to be in the right place (no additional JS needed).

```css
@media print {
  .floatThead-container {
    position: initial !important;
  }
  .size-row {
    display: none !important;
  }
}
```

I just wanted to mention this here, as it may be useful to someone else too.

**Comment by Bitmapped** [comment]
@Haprog: Have you tested IE 11? Your code doesn't appear to work correctly there.

**Comment by Haprog** [comment]
@Bitmapped: I hadn't. You're right, there is a problem with IE 11 (and probably also older IEs). But this CSS only fix works for me at least with Chrome, Firefox and even Edge.

**Comment by radiok** [comment]
Just adding my own 2 cents, I've been using the following code for a while in IE9, IE11, and Chrome.

	var onPrinting = function () {
		$('table').floatThead('destroy');
	};
	
	var onScreen = function () {
		$('table').floatThead();
	};
	
	//WebKit print detection
	if (window.matchMedia) {
		var mediaQueryList = window.matchMedia('print');
		mediaQueryList.addListener(function (mql) {
		    if (mql.matches) {
		        onPrinting();
		    } 
		    else {
		        onScreen();
		    }
		});
	}
	
	//IE print detection
	window.onbeforeprint = onPrinting;
	window.onafterprint = onScreen;
	
	onScreen();

**Comment by mkoryak** [comment]
I currently have a version of that code in master,  have you tried that?

**Comment by claudchan** [comment]
Hi, there is an issue running on IE9 if use addListener.

Object doesn't support property or method 'addListener'

**Comment by mkoryak** [comment]
people still use ie9 ? can you create a new issue please

**Comment by claudchan** [comment]
New issue created: https://github.com/mkoryak/floatThead/issues/316
