### ISSUE TITLE
add info to the docs about ideal html/css structure

### ISSUE THREAD

**Issue by mkoryak** [mkoryak/floatThead#91]
also add a section to the docs about info needed to submit a bug / question

**Comment by artursudnik** [comment]
I have centered table by "margin: 0 auto;" and header when floated is moved to the left of the page. All CSS styles are applied by matching table class. No wrapper around it.

**Comment by mkoryak** [comment]
ok, if you think this is a bug, please create a new issue and provide a jsfiddle. 
I think that you might be able to solve it by using the option `useAbsolutePositioning:false`  - it is probably happening because with the default positioning method, the table is wrapped by a a div with relative positioning, so that would mess up your `0 auto`

**Comment by artursudnik** [comment]
I added a wrapper around the table and moved all styles that position the table to it. It solved the problem.
